//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as main$0 from "../../../../mrgeoffrich/bacio/desktop/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as leaderservice$0 from "../../../../mrgeoffrich/bacio/internal/leaderservice/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "leaderStatus": $$createType0,
    }));
}

// Private type creation functions
const $$createType0 = leaderservice$0.StatusDTO.createFrom;

configure();
