// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as main$0 from "../../../../mrgeoffrich/bacio/desktop/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as leaderservice$0 from "../../../../mrgeoffrich/bacio/internal/leaderservice/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "leaderStatus": main$0.LeaderStatusDTO;
            "time": string;
        }
    }
}
