// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

export class Issue {
    "id": number;
    "uuid": string;
    "repo_id": number;
    "number": number;

    /**
     * e.g. "MINI-42"
     */
    "key": string;
    "feature_id"?: number | null;
    "feature_slug"?: string;
    "title": string;
    "description"?: string;
    "state": State;
    "assignee"?: string;

    /**
     * WaitingForClaim is true between a dispatch being queued against
     * this issue and an agent recording an open claim on it. Ephemeral
     * runtime state — set by store.AddDispatch, cleared by
     * store.AddAgentClaim / store.CancelDispatch. No omitempty: the
     * field must be visible (including when false) in JSON output.
     */
    "waiting_for_claim": boolean;

    /**
     * Taken is true iff this issue currently has at least one open
     * (unreleased) agent claim held by an alive session — the derived
     * "an agent is actively holding this" signal also surfaced on the
     * show/brief views. Computed at read time via the same join the
     * desktop's ListOpenClaims runs, so list responses don't need a
     * second round trip. No omitempty: the field must be visible
     * (including when false) in JSON output.
     */
    "taken": boolean;
    "tags": string[];

    /**
     * ArchivedAt (BACI-68) is non-nil iff the issue is archived —
     * hidden from default lists / boards, but the row and its audit
     * history are retained. The auto-sweep stamps it for issues older
     * than 4 days in a terminal state; manual `bacio issue archive` /
     * `unarchive` writes or clears it on demand. Reopening an archived
     * issue (state -> todo/...) does NOT auto-unarchive — the user must
     * unarchive explicitly.
     */
    "archived_at"?: time$0.Time | null;

    /**
     * TerminalAt (BACI-138) is non-nil iff the issue is currently in
     * a terminal state (done / cancelled), and carries the timestamp
     * of the most recent transition INTO that state. Cleared whenever
     * state moves out of a terminal value. Drives the kanban Done /
     * Cancelled column ordering (newest-first) without joining the
     * audit log. Omitempty so non-terminal rows don't carry a JSON
     * `terminal_at: null` field. Replaces the pre-BACI-138 sort that
     * proxied via UpdatedAt — that proxy was wrong because tag /
     * title / description edits bump UpdatedAt without changing state.
     */
    "terminal_at"?: time$0.Time | null;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;

    /** Creates a new Issue instance. */
    constructor($$source: Partial<Issue> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("uuid" in $$source)) {
            this["uuid"] = "";
        }
        if (!("repo_id" in $$source)) {
            this["repo_id"] = 0;
        }
        if (!("number" in $$source)) {
            this["number"] = 0;
        }
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = State.$zero;
        }
        if (!("waiting_for_claim" in $$source)) {
            this["waiting_for_claim"] = false;
        }
        if (!("taken" in $$source)) {
            this["taken"] = false;
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Issue instance from a string or object.
     */
    static createFrom($$source: any = {}): Issue {
        const $$createField13_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField13_0($$parsedSource["tags"]);
        }
        return new Issue($$parsedSource as Partial<Issue>);
    }
}

/**
 * QuestionAnswers maps question text -> answer. For a single-select
 * question the value is a string (an option label, or free-text
 * "Other"); for a multi-select question the value is []string. The
 * shape is constrained by ValidateQuestionAnswers (against the
 * question's MultiSelect flag) so a renderer can rely on it.
 */
export type QuestionAnswers = { [_ in string]?: any };

/**
 * QuestionItem is one multi-choice question. Header is the short
 * label rendered next to the question text in the UI (capped at
 * MaxQuestionHeaderLen, matching the AskUserQuestion docs). Options
 * is the 2-4 entry choice set. MultiSelect lets the user pick more
 * than one option (rendered as checkboxes vs. radios).
 * 
 * MultiSelect is a *bool — not a bool — to mirror native
 * AskUserQuestion's "required" contract. The agent must explicitly
 * send `true` or `false`; an absent field is rejected at the
 * validation boundary. Readers should go through IsMultiSelect()
 * rather than dereferencing the pointer so nil is treated as false
 * at render time even if a row somehow slipped past validation.
 */
export class QuestionItem {
    "question": string;
    "header": string;
    "multiSelect"?: boolean | null;
    "options": QuestionOption[];

    /** Creates a new QuestionItem instance. */
    constructor($$source: Partial<QuestionItem> = {}) {
        if (!("question" in $$source)) {
            this["question"] = "";
        }
        if (!("header" in $$source)) {
            this["header"] = "";
        }
        if (!("options" in $$source)) {
            this["options"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuestionItem instance from a string or object.
     */
    static createFrom($$source: any = {}): QuestionItem {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField3_0($$parsedSource["options"]);
        }
        return new QuestionItem($$parsedSource as Partial<QuestionItem>);
    }
}

/**
 * QuestionOption is one choice on a question. Description is the
 * optional fine-print rendered under the label. Preview is the
 * optional monospace block (ASCII mockup, code snippet, diagram)
 * rendered side-by-side with the option list when at least one
 * option carries one — mirrors native AskUserQuestion's preview
 * affordance. Preview is single-select only (native constraint).
 */
export class QuestionOption {
    "label": string;
    "description"?: string;
    "preview"?: string;

    /** Creates a new QuestionOption instance. */
    constructor($$source: Partial<QuestionOption> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuestionOption instance from a string or object.
     */
    static createFrom($$source: any = {}): QuestionOption {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QuestionOption($$parsedSource as Partial<QuestionOption>);
    }
}

/**
 * QuestionPayload mirrors the input shape of Claude Code's built-in
 * AskUserQuestion tool so an agent calling either tool builds the
 * same payload. Validated at the store boundary by
 * ValidateQuestionPayload.
 */
export class QuestionPayload {
    "questions": QuestionItem[];

    /** Creates a new QuestionPayload instance. */
    constructor($$source: Partial<QuestionPayload> = {}) {
        if (!("questions" in $$source)) {
            this["questions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuestionPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): QuestionPayload {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("questions" in $$parsedSource) {
            $$parsedSource["questions"] = $$createField0_0($$parsedSource["questions"]);
        }
        return new QuestionPayload($$parsedSource as Partial<QuestionPayload>);
    }
}

/**
 * QuestionState is the lifecycle marker on agent_session_questions.
 * See the table comment in schema.sql for the full description.
 */
export enum QuestionState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    QuestionOpen = "open",
    QuestionAnswered = "answered",
    QuestionCancelled = "cancelled",
    QuestionAbandoned = "abandoned",
};

/**
 * SessionQuestion is one clarification question an agent asked the
 * user through the bacio channel's `ask_user_question` MCP tool
 * (BACI-53). It mirrors a single AskUserQuestion call: the questions
 * array goes in, the user's answers come back. Local-only — never
 * synced.
 * 
 * RequestUUID is the UUIDv7 the channel mints at ask time. The
 * channel uses it in its in-memory request_uuid -> JSON-RPC id map
 * to correlate the parked reply with the answered row when it
 * re-polls.
 * 
 * IssueKey is the issue key of the session's open claim at ask time,
 * when there was one. Empty for asks made without an active claim
 * (e.g. the agent asking a setup question before claiming anything).
 * 
 * AskedBy is the persistent agent identity that posed the question.
 * AnsweredBy is the actor who responded (typically the OS user via
 * the TUI/desktop, or "api" for REST callers without an X-Actor).
 * Empty until the row leaves the open state.
 */
export class SessionQuestion {
    /**
     * ID / SessionPK are server-time fields — `omitempty` so dry-run
     * projections (which can't know them yet) emit the same JSON shape
     * as real calls minus the unknown fields.
     */
    "id"?: number;
    "session_pk"?: number;
    "session_id"?: string;
    "request_uuid": string;
    "issue_key"?: string;
    "payload": QuestionPayload;
    "answers"?: QuestionAnswers;
    "state": QuestionState;
    "asked_at": time$0.Time;
    "answered_at"?: time$0.Time | null;
    "asked_by": string;
    "answered_by"?: string;

    /** Creates a new SessionQuestion instance. */
    constructor($$source: Partial<SessionQuestion> = {}) {
        if (!("request_uuid" in $$source)) {
            this["request_uuid"] = "";
        }
        if (!("payload" in $$source)) {
            this["payload"] = (new QuestionPayload());
        }
        if (!("state" in $$source)) {
            this["state"] = QuestionState.$zero;
        }
        if (!("asked_at" in $$source)) {
            this["asked_at"] = null;
        }
        if (!("asked_by" in $$source)) {
            this["asked_by"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionQuestion instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionQuestion {
        const $$createField5_0 = $$createType5;
        const $$createField6_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("payload" in $$parsedSource) {
            $$parsedSource["payload"] = $$createField5_0($$parsedSource["payload"]);
        }
        if ("answers" in $$parsedSource) {
            $$parsedSource["answers"] = $$createField6_0($$parsedSource["answers"]);
        }
        return new SessionQuestion($$parsedSource as Partial<SessionQuestion>);
    }
}

export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StateTodo = "todo",
    StateInProgress = "in_progress",

    /**
     * StateNeedsAction parks an issue while an LLM agent is waiting on
     * the user for input — the assignee stays, but the column signals
     * that human attention (not more agent work) is the next step.
     */
    StateNeedsAction = "needs_action",
    StateInReview = "in_review",
    StateDone = "done",
    StateCancelled = "cancelled",
};

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = QuestionOption.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = QuestionItem.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = QuestionPayload.createFrom;
var $$createType6 = (function $$initCreateType6(...args: any[]): any {
    if ($$createType6 === $$initCreateType6) {
        $$createType6 = $$createType7;
    }
    return $$createType6(...args);
});
const $$createType7 = $Create.Map($Create.Any, $Create.Any);
