// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * QuestionAnswers maps question text -> answer. For a single-select
 * question the value is a string (an option label, or free-text
 * "Other"); for a multi-select question the value is []string. The
 * shape is constrained by ValidateQuestionAnswers (against the
 * question's MultiSelect flag) so a renderer can rely on it.
 */
export type QuestionAnswers = { [_ in string]?: any };

/**
 * QuestionItem is one multi-choice question. Header is the short
 * label rendered next to the question text in the UI (capped at
 * MaxQuestionHeaderLen, matching the AskUserQuestion docs). Options
 * is the 2-4 entry choice set. MultiSelect lets the user pick more
 * than one option (rendered as checkboxes vs. radios).
 * 
 * MultiSelect is a *bool — not a bool — to mirror native
 * AskUserQuestion's "required" contract. The agent must explicitly
 * send `true` or `false`; an absent field is rejected at the
 * validation boundary. Readers should go through IsMultiSelect()
 * rather than dereferencing the pointer so nil is treated as false
 * at render time even if a row somehow slipped past validation.
 */
export class QuestionItem {
    "question": string;
    "header": string;
    "multiSelect"?: boolean | null;
    "options": QuestionOption[];

    /** Creates a new QuestionItem instance. */
    constructor($$source: Partial<QuestionItem> = {}) {
        if (!("question" in $$source)) {
            this["question"] = "";
        }
        if (!("header" in $$source)) {
            this["header"] = "";
        }
        if (!("options" in $$source)) {
            this["options"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuestionItem instance from a string or object.
     */
    static createFrom($$source: any = {}): QuestionItem {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField3_0($$parsedSource["options"]);
        }
        return new QuestionItem($$parsedSource as Partial<QuestionItem>);
    }
}

/**
 * QuestionOption is one choice on a question. Description is the
 * optional fine-print rendered under the label. Preview is the
 * optional monospace block (ASCII mockup, code snippet, diagram)
 * rendered side-by-side with the option list when at least one
 * option carries one — mirrors native AskUserQuestion's preview
 * affordance. Preview is single-select only (native constraint).
 */
export class QuestionOption {
    "label": string;
    "description"?: string;
    "preview"?: string;

    /** Creates a new QuestionOption instance. */
    constructor($$source: Partial<QuestionOption> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuestionOption instance from a string or object.
     */
    static createFrom($$source: any = {}): QuestionOption {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QuestionOption($$parsedSource as Partial<QuestionOption>);
    }
}

/**
 * QuestionPayload mirrors the input shape of Claude Code's built-in
 * AskUserQuestion tool so an agent calling either tool builds the
 * same payload. Validated at the store boundary by
 * ValidateQuestionPayload.
 */
export class QuestionPayload {
    "questions": QuestionItem[];

    /** Creates a new QuestionPayload instance. */
    constructor($$source: Partial<QuestionPayload> = {}) {
        if (!("questions" in $$source)) {
            this["questions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuestionPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): QuestionPayload {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("questions" in $$parsedSource) {
            $$parsedSource["questions"] = $$createField0_0($$parsedSource["questions"]);
        }
        return new QuestionPayload($$parsedSource as Partial<QuestionPayload>);
    }
}

/**
 * QuestionState is the lifecycle marker on agent_session_questions.
 * See the table comment in schema.sql for the full description.
 */
export enum QuestionState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    QuestionOpen = "open",
    QuestionAnswered = "answered",
    QuestionCancelled = "cancelled",
    QuestionAbandoned = "abandoned",
};

/**
 * SessionQuestion is one clarification question an agent asked the
 * user through the bacio channel's `ask_user_question` MCP tool
 * (BACI-53). It mirrors a single AskUserQuestion call: the questions
 * array goes in, the user's answers come back. Local-only — never
 * synced.
 * 
 * RequestUUID is the UUIDv7 the channel mints at ask time. The
 * channel uses it in its in-memory request_uuid -> JSON-RPC id map
 * to correlate the parked reply with the answered row when it
 * re-polls.
 * 
 * IssueKey is the issue key of the session's open claim at ask time,
 * when there was one. Empty for asks made without an active claim
 * (e.g. the agent asking a setup question before claiming anything).
 * 
 * AskedBy is the persistent agent identity that posed the question.
 * AnsweredBy is the actor who responded (typically the OS user via
 * the TUI/desktop, or "api" for REST callers without an X-Actor).
 * Empty until the row leaves the open state.
 */
export class SessionQuestion {
    /**
     * ID / SessionPK are server-time fields — `omitempty` so dry-run
     * projections (which can't know them yet) emit the same JSON shape
     * as real calls minus the unknown fields.
     */
    "id"?: number;
    "session_pk"?: number;
    "session_id"?: string;
    "request_uuid": string;
    "issue_key"?: string;
    "payload": QuestionPayload;
    "answers"?: QuestionAnswers;
    "state": QuestionState;
    "asked_at": time$0.Time;
    "answered_at"?: time$0.Time | null;
    "asked_by": string;
    "answered_by"?: string;

    /** Creates a new SessionQuestion instance. */
    constructor($$source: Partial<SessionQuestion> = {}) {
        if (!("request_uuid" in $$source)) {
            this["request_uuid"] = "";
        }
        if (!("payload" in $$source)) {
            this["payload"] = (new QuestionPayload());
        }
        if (!("state" in $$source)) {
            this["state"] = QuestionState.$zero;
        }
        if (!("asked_at" in $$source)) {
            this["asked_at"] = null;
        }
        if (!("asked_by" in $$source)) {
            this["asked_by"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionQuestion instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionQuestion {
        const $$createField5_0 = $$createType4;
        const $$createField6_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("payload" in $$parsedSource) {
            $$parsedSource["payload"] = $$createField5_0($$parsedSource["payload"]);
        }
        if ("answers" in $$parsedSource) {
            $$parsedSource["answers"] = $$createField6_0($$parsedSource["answers"]);
        }
        return new SessionQuestion($$parsedSource as Partial<SessionQuestion>);
    }
}

// Private type creation functions
const $$createType0 = QuestionOption.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = QuestionItem.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = QuestionPayload.createFrom;
var $$createType5 = (function $$initCreateType5(...args: any[]): any {
    if ($$createType5 === $$initCreateType5) {
        $$createType5 = $$createType6;
    }
    return $$createType5(...args);
});
const $$createType6 = $Create.Map($Create.Any, $Create.Any);
