// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * AnthropicBlock is one content block in a message — the union the viewer's
 * AssistantBlock encodes (text | thinking | tool_use), plus the tool_result
 * shape that appears in the request messages[] (a user turn replying to a prior
 * tool_use). Type is the discriminator; the other fields are populated per type:
 *   - "text":        Text
 *   - "thinking":    Thinking
 *   - "tool_use":    ID, Name, Input
 *   - "tool_result": ToolUseID, Content, IsError
 */
export class AnthropicBlock {
    "type": string;

    /**
     * text / thinking
     */
    "text"?: string;
    "thinking"?: string;

    /**
     * tool_use — Input is the accumulated input JSON (parsed from the streamed
     * input_json_delta fragments on the response side, or carried verbatim from
     * the request side). RawMessage so the original JSON survives round-tripping.
     */
    "id"?: string;
    "name"?: string;
    "input"?: json$0.RawMessage;

    /**
     * tool_result — replies to a prior tool_use by id. Content is polymorphic
     * (string or block list) so it's kept as raw JSON, mirroring the viewer's
     * ToolResultContent union.
     */
    "tool_use_id"?: string;
    "content"?: json$0.RawMessage;
    "is_error"?: boolean;

    /** Creates a new AnthropicBlock instance. */
    constructor($$source: Partial<AnthropicBlock> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AnthropicBlock instance from a string or object.
     */
    static createFrom($$source: any = {}): AnthropicBlock {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AnthropicBlock($$parsedSource as Partial<AnthropicBlock>);
    }
}

/**
 * AnthropicMessage is one entry in the request messages[] array: a role
 * ("user" | "assistant") and its content blocks. The request body carries the
 * whole conversation-so-far as these; the per-capture delta is the slice of
 * messages appended since the previous primary capture.
 */
export class AnthropicMessage {
    "role": string;
    "content": AnthropicBlock[];

    /** Creates a new AnthropicMessage instance. */
    constructor($$source: Partial<AnthropicMessage> = {}) {
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AnthropicMessage instance from a string or object.
     */
    static createFrom($$source: any = {}): AnthropicMessage {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("content" in $$parsedSource) {
            $$parsedSource["content"] = $$createField1_0($$parsedSource["content"]);
        }
        return new AnthropicMessage($$parsedSource as Partial<AnthropicMessage>);
    }
}

/**
 * AnthropicTranscript is the assembled per-job conversation: the ordered
 * messages (user/tool_result turns interleaved with the assistant turns) of the
 * primary thread, the summed token usage across the job, and the auxiliary turns
 * (title-gen, structured-output probes) that share the dispatch but aren't part
 * of the main conversation. Model is the primary thread's model.
 */
export class AnthropicTranscript {
    "dispatch_id"?: number | null;
    "model"?: string;
    "messages": AnthropicMessage[];
    "usage": AnthropicUsage;

    /**
     * Auxiliary turns (one per non-primary capture) — kept so the full picture
     * is visible without polluting the primary thread. Each is one assistant
     * turn with its own usage; ordered by capture sequence.
     */
    "auxiliary"?: AnthropicTurn[];

    /** Creates a new AnthropicTranscript instance. */
    constructor($$source: Partial<AnthropicTranscript> = {}) {
        if (!("messages" in $$source)) {
            this["messages"] = [];
        }
        if (!("usage" in $$source)) {
            this["usage"] = (new AnthropicUsage());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AnthropicTranscript instance from a string or object.
     */
    static createFrom($$source: any = {}): AnthropicTranscript {
        const $$createField2_0 = $$createType3;
        const $$createField3_0 = $$createType4;
        const $$createField4_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField2_0($$parsedSource["messages"]);
        }
        if ("usage" in $$parsedSource) {
            $$parsedSource["usage"] = $$createField3_0($$parsedSource["usage"]);
        }
        if ("auxiliary" in $$parsedSource) {
            $$parsedSource["auxiliary"] = $$createField4_0($$parsedSource["auxiliary"]);
        }
        return new AnthropicTranscript($$parsedSource as Partial<AnthropicTranscript>);
    }
}

/**
 * AnthropicTurn is the single assistant turn reconstructed from one capture's
 * response SSE stream: the ordered content blocks the model emitted, the merged
 * token usage, the stop reason, and the model name. This is the response half
 * of a capture; the request half is the messages[] / delta.
 */
export class AnthropicTurn {
    "model"?: string;
    "blocks": AnthropicBlock[];
    "usage": AnthropicUsage;
    "stop_reason"?: string;

    /** Creates a new AnthropicTurn instance. */
    constructor($$source: Partial<AnthropicTurn> = {}) {
        if (!("blocks" in $$source)) {
            this["blocks"] = [];
        }
        if (!("usage" in $$source)) {
            this["usage"] = (new AnthropicUsage());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AnthropicTurn instance from a string or object.
     */
    static createFrom($$source: any = {}): AnthropicTurn {
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("blocks" in $$parsedSource) {
            $$parsedSource["blocks"] = $$createField1_0($$parsedSource["blocks"]);
        }
        if ("usage" in $$parsedSource) {
            $$parsedSource["usage"] = $$createField2_0($$parsedSource["usage"]);
        }
        return new AnthropicTurn($$parsedSource as Partial<AnthropicTurn>);
    }
}

/**
 * AnthropicUsage is the merged token usage for one assistant turn. Anthropic
 * splits usage across two SSE events — input/cache tokens arrive on
 * message_start.message.usage and the final output_tokens (+ the thinking-token
 * breakdown) on message_delta.usage — so the parser merges both into one struct.
 * The viewer's TokenUsage carries input/output/cache fields with the same names.
 */
export class AnthropicUsage {
    "input_tokens"?: number;
    "output_tokens"?: number;
    "cache_creation_input_tokens"?: number;
    "cache_read_input_tokens"?: number;

    /**
     * ThinkingTokens is output_tokens_details.thinking_tokens off message_delta —
     * the slice of OutputTokens that was extended thinking, surfaced separately so
     * a reader can see the thinking cost without re-deriving it.
     */
    "thinking_tokens"?: number;

    /** Creates a new AnthropicUsage instance. */
    constructor($$source: Partial<AnthropicUsage> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AnthropicUsage instance from a string or object.
     */
    static createFrom($$source: any = {}): AnthropicUsage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AnthropicUsage($$parsedSource as Partial<AnthropicUsage>);
    }
}

/**
 * DispatchMode is the slug of the prompt template a dispatch was queued
 * against — for the built-in templates that ship with bacio it's one of
 * "plan", "design", "implement", "review", "ship", or "fix_review"; for
 * a user-created template it's whatever the user named it. "" = untyped (the
 * pre-Mode default; delivery treats it as unspecified). The mode is the
 * per-dispatch snapshot of which template was used; it deliberately
 * outlives the template (a deleted template's historical dispatches
 * keep the slug verbatim — renderers should treat an unrecognised slug
 * as "removed", not error out). The shape rule is a slug
 * (^[a-z0-9][a-z0-9-_]*$) capped at 60 chars; the registered set lives
 * in the prompt_templates store table, not this enum.
 */
export enum DispatchMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * DispatchModePlan etc. are deprecated aliases — kept so older callers
     * that still reference the typed constants keep compiling. New code
     * should use the BuiltinTemplate* string constants above and the
     * runtime slug values from the prompt_templates table.
     */
    DispatchModePlan = "plan",
    DispatchModeImplement = "implement",
    DispatchModeReview = "review",
    DispatchModeShip = "ship",
    DispatchModeFixReview = "fix_review",
};

/**
 * EngineMode is the per-issue controller-engine drive mode while the
 * card is in_pipeline. "off" = the user advances one job at a time via
 * Start; "auto" = the engine runs the chain consecutively, halting on an
 * open question and resuming when it is answered.
 */
export enum EngineMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    EngineOff = "off",
    EngineAuto = "auto",
};

export class Issue {
    "id": number;
    "uuid": string;
    "repo_id": number;
    "number": number;

    /**
     * e.g. "MINI-42"
     */
    "key": string;
    "feature_id"?: number | null;
    "feature_slug"?: string;

    /**
     * FeatureEmoji (BACI-172) is the per-feature glyph denormalised
     * onto the issue row via the feature join in issueSelect. Empty
     * when the issue has no feature, or when the feature has no
     * emoji set. The kanban / BoardCard render reads this directly
     * so the card row can decorate without a second lookup.
     */
    "feature_emoji"?: string;

    /**
     * FeatureBranchName (BACI-231) is the parent feature's integration
     * branch denormalised onto the issue row via the same join. Empty
     * when the issue has no feature or the feature ships straight to
     * main (NULL branch_name). The BoardCard denorm reads this so the
     * kanban card chip and the ActivityTray auto-grouping don't need a
     * second feature lookup per card.
     */
    "feature_branch_name"?: string;
    "title": string;
    "description"?: string;
    "state": State;
    "assignee"?: string;

    /**
     * Taken is true iff this issue currently has at least one open
     * (unreleased) agent claim held by an alive session — the derived
     * "an agent is actively holding this" signal also surfaced on the
     * show/brief views. Computed at read time via the same join the
     * desktop's ListOpenClaims runs, so list responses don't need a
     * second round trip. No omitempty: the field must be visible
     * (including when false) in JSON output.
     */
    "taken": boolean;
    "tags": string[];

    /**
     * ArchivedAt (BACI-68) is non-nil iff the issue is archived —
     * hidden from default lists / boards, but the row and its audit
     * history are retained. The auto-sweep stamps it for issues whose
     * terminal_at is older than the configured retention window
     * (BACI-162; default 7 days, editable via `bacio settings archive`
     * or the desktop Settings panel); manual `bacio issue archive` /
     * `unarchive` writes or clears it on demand. Reopening an archived
     * issue (state -> todo/...) does NOT auto-unarchive — the user must
     * unarchive explicitly.
     */
    "archived_at"?: time$0.Time | null;

    /**
     * TerminalAt (BACI-138) is non-nil iff the issue is currently in
     * a terminal state (done / cancelled), and carries the timestamp
     * of the most recent transition INTO that state. Cleared whenever
     * state moves out of a terminal value. Drives the kanban Done /
     * Cancelled column ordering (newest-first) without joining the
     * audit log. Omitempty so non-terminal rows don't carry a JSON
     * `terminal_at: null` field. Replaces the pre-BACI-138 sort that
     * proxied via UpdatedAt — that proxy was wrong because tag /
     * title / description edits bump UpdatedAt without changing state.
     */
    "terminal_at"?: time$0.Time | null;

    /**
     * BaseBranch (BACI-232) is the per-issue override for the branch a
     * PR for this issue is opened against. nil = inherit from the
     * parent feature's BranchName (itself nil = ship to main, the
     * legacy default). Lets a one-off urgent fix peel off the feature
     * workflow and target main directly even when its parent feature
     * lives on feat/X, and lets the terminal merge-feature issue target
     * main from within a non-main feature. Validated at the store
     * boundary by ValidateBranchName (same git-ref rules as
     * features.branch_name). Pointer mirrors Feature.BranchName's
     * nullable shape. The resolver that combines this with
     * feature.branch_name is BACI-226; this field just records the
     * override.
     */
    "base_branch"?: string | null;

    /**
     * Priority is the manual ordering key within a (repo, state) band,
     * used by the Pipeline page's Backlog (todo) and Shipping
     * (to_be_shipped) columns. Lower sorts first — position 1 (next to
     * go) carries the smallest value. 0 is the unordered default; the
     * other columns ignore it. Reordering writes this via
     * Store.ReorderIssue, so the queue order survives reloads rather
     * than living in board-local display state. No omitempty: the field
     * is always visible so the Pipeline reads it without a fallback.
     */
    "priority": number;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;

    /**
     * EngineMode / EnginePauseReason are the per-issue controller-engine
     * fields, meaningful only while the issue is in_pipeline. EngineMode
     * is "off" (manual Start advances one job) or "auto" (the engine
     * runs the chain consecutively, halting on an open question).
     * EnginePauseReason is "" or "open_question". Both default to their
     * zero value for non-pipeline issues. Populated by the boardcards
     * denorm in a later phase; carried here so the engine and the read
     * surfaces share one shape.
     */
    "engine_mode"?: EngineMode;
    "engine_pause_reason"?: string;

    /** Creates a new Issue instance. */
    constructor($$source: Partial<Issue> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("uuid" in $$source)) {
            this["uuid"] = "";
        }
        if (!("repo_id" in $$source)) {
            this["repo_id"] = 0;
        }
        if (!("number" in $$source)) {
            this["number"] = 0;
        }
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = State.$zero;
        }
        if (!("taken" in $$source)) {
            this["taken"] = false;
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("priority" in $$source)) {
            this["priority"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Issue instance from a string or object.
     */
    static createFrom($$source: any = {}): Issue {
        const $$createField14_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField14_0($$parsedSource["tags"]);
        }
        return new Issue($$parsedSource as Partial<Issue>);
    }
}

/**
 * JobStatus is the lifecycle of a single pipeline job — one stage in a
 * card's process chain. The controller engine owns every transition:
 * pending → running (the engine queued a dispatch for the stage) →
 * complete (that dispatch acked) | cancelled (Stop/Cancel). Agents do
 * not write this; it is the engine's source of truth for "where in the
 * chain is this card".
 */
export enum JobStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    JobPending = "pending",
    JobRunning = "running",
    JobComplete = "complete",
    JobCancelled = "cancelled",
};

/**
 * Notification is one BACI-287 agent→user notification: a non-blocking,
 * fire-and-forget message a running agent sends the user via the bacio
 * channel's `send_user_notification` MCP tool. Unlike a SessionQuestion
 * (BACI-53) it carries no answer and never blocks the agent — the channel
 * inserts the row and returns immediately, so there is no lifecycle beyond
 * unread→read. Local-only — never synced.
 * 
 * RepoID scopes the row; RepoPrefix is the repo's 4-char key, lifted by the
 * store's join so the cross-repo bell can label each row without a second
 * lookup. IssueID/IssueKey are optional — a present issue makes the row
 * deep-link to that ticket. SessionPK is the agent_sessions PK of the
 * sending session when one was registered; nil for a notification fired
 * before the channel session registered. SourceAgent is the persistent
 * agent identity that sent it (or the "bacio-channel" fallback).
 * 
 * ReadAt is the only lifecycle signal: nil = unread (counts toward the
 * bell badge), non-nil = read.
 */
export class Notification {
    "id": number;
    "repo_id": number;
    "repo_prefix"?: string;
    "issue_id"?: number | null;
    "issue_key"?: string;
    "body": string;
    "source_agent": string;
    "session_pk"?: number | null;
    "created_at": time$0.Time;
    "read_at"?: time$0.Time | null;

    /** Creates a new Notification instance. */
    constructor($$source: Partial<Notification> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("repo_id" in $$source)) {
            this["repo_id"] = 0;
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("source_agent" in $$source)) {
            this["source_agent"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Notification instance from a string or object.
     */
    static createFrom($$source: any = {}): Notification {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Notification($$parsedSource as Partial<Notification>);
    }
}

/**
 * PipelineJob is one persisted stage of a card's process chain
 * (pipeline_jobs row). Mode is a dispatch-template slug (plan,
 * implement, …) or ShipJobMode for the hand-off. DispatchID points at
 * the agent_dispatches row once the engine queues the stage (nil while
 * pending; ON DELETE SET NULL so a retention prune of the dispatch
 * leaves the job's history intact).
 */
export class PipelineJob {
    "id": number;
    "issue_id": number;
    "sequence": number;
    "mode": string;
    "status": JobStatus;
    "dispatch_id"?: number | null;
    "created_at": time$0.Time;
    "started_at"?: time$0.Time | null;
    "completed_at"?: time$0.Time | null;

    /** Creates a new PipelineJob instance. */
    constructor($$source: Partial<PipelineJob> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("issue_id" in $$source)) {
            this["issue_id"] = 0;
        }
        if (!("sequence" in $$source)) {
            this["sequence"] = 0;
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = JobStatus.$zero;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PipelineJob instance from a string or object.
     */
    static createFrom($$source: any = {}): PipelineJob {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PipelineJob($$parsedSource as Partial<PipelineJob>);
    }
}

/**
 * ProxyMessage is one persisted proxy_messages row: the parsed detail of one
 * captured Anthropic SSE turn, durable so a job's transcript can be assembled
 * without re-reading the raw .http file. It mirrors the columns in schema.sql.
 * DeltaJSON / TurnJSON are the serialised AnthropicMessage[] / AnthropicTurn
 * (a truncation marker string when the body exceeded MaxProxyMessageBody).
 */
export class ProxyMessage {
    "id": number;
    "proxy_request_id": number;
    "dispatch_id"?: number | null;
    "session_id"?: string;
    "claude_agent_id"?: string;
    "model"?: string;
    "system_fingerprint"?: string;
    "message_count": number;
    "is_primary": boolean;
    "stop_reason"?: string;
    "delta_json"?: string;
    "turn_json"?: string;
    "usage": AnthropicUsage;
    "started_at": time$0.Time;

    /** Creates a new ProxyMessage instance. */
    constructor($$source: Partial<ProxyMessage> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("proxy_request_id" in $$source)) {
            this["proxy_request_id"] = 0;
        }
        if (!("message_count" in $$source)) {
            this["message_count"] = 0;
        }
        if (!("is_primary" in $$source)) {
            this["is_primary"] = false;
        }
        if (!("usage" in $$source)) {
            this["usage"] = (new AnthropicUsage());
        }
        if (!("started_at" in $$source)) {
            this["started_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyMessage instance from a string or object.
     */
    static createFrom($$source: any = {}): ProxyMessage {
        const $$createField12_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("usage" in $$parsedSource) {
            $$parsedSource["usage"] = $$createField12_0($$parsedSource["usage"]);
        }
        return new ProxyMessage($$parsedSource as Partial<ProxyMessage>);
    }
}

/**
 * QuestionAnswers maps question text -> answer. For a single-select
 * question the value is a string (an option label, or free-text
 * "Other"); for a multi-select question the value is []string. The
 * shape is constrained by ValidateQuestionAnswers (against the
 * question's MultiSelect flag) so a renderer can rely on it.
 */
export type QuestionAnswers = { [_ in string]?: any };

/**
 * QuestionItem is one multi-choice question. Header is the short
 * label rendered next to the question text in the UI (capped at
 * MaxQuestionHeaderLen, matching the AskUserQuestion docs). Options
 * is the 2-4 entry choice set. MultiSelect lets the user pick more
 * than one option (rendered as checkboxes vs. radios).
 * 
 * MultiSelect is a *bool — not a bool — to mirror native
 * AskUserQuestion's "required" contract. The agent must explicitly
 * send `true` or `false`; an absent field is rejected at the
 * validation boundary. Readers should go through IsMultiSelect()
 * rather than dereferencing the pointer so nil is treated as false
 * at render time even if a row somehow slipped past validation.
 */
export class QuestionItem {
    "question": string;
    "header": string;
    "multiSelect"?: boolean | null;
    "options": QuestionOption[];

    /** Creates a new QuestionItem instance. */
    constructor($$source: Partial<QuestionItem> = {}) {
        if (!("question" in $$source)) {
            this["question"] = "";
        }
        if (!("header" in $$source)) {
            this["header"] = "";
        }
        if (!("options" in $$source)) {
            this["options"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuestionItem instance from a string or object.
     */
    static createFrom($$source: any = {}): QuestionItem {
        const $$createField3_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField3_0($$parsedSource["options"]);
        }
        return new QuestionItem($$parsedSource as Partial<QuestionItem>);
    }
}

/**
 * QuestionOption is one choice on a question. Description is the
 * optional fine-print rendered under the label. Preview is the
 * optional monospace block (ASCII mockup, code snippet, diagram)
 * rendered side-by-side with the option list when at least one
 * option carries one — mirrors native AskUserQuestion's preview
 * affordance. Preview is single-select only (native constraint).
 */
export class QuestionOption {
    "label": string;
    "description"?: string;
    "preview"?: string;

    /** Creates a new QuestionOption instance. */
    constructor($$source: Partial<QuestionOption> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuestionOption instance from a string or object.
     */
    static createFrom($$source: any = {}): QuestionOption {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QuestionOption($$parsedSource as Partial<QuestionOption>);
    }
}

/**
 * QuestionPayload mirrors the input shape of Claude Code's built-in
 * AskUserQuestion tool so an agent calling either tool builds the
 * same payload. Validated at the store boundary by
 * ValidateQuestionPayload.
 */
export class QuestionPayload {
    "questions": QuestionItem[];

    /** Creates a new QuestionPayload instance. */
    constructor($$source: Partial<QuestionPayload> = {}) {
        if (!("questions" in $$source)) {
            this["questions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuestionPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): QuestionPayload {
        const $$createField0_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("questions" in $$parsedSource) {
            $$parsedSource["questions"] = $$createField0_0($$parsedSource["questions"]);
        }
        return new QuestionPayload($$parsedSource as Partial<QuestionPayload>);
    }
}

/**
 * QuestionState is the lifecycle marker on agent_session_questions.
 * See the table comment in schema.sql for the full description.
 */
export enum QuestionState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    QuestionOpen = "open",
    QuestionAnswered = "answered",
    QuestionCancelled = "cancelled",
    QuestionAbandoned = "abandoned",
};

/**
 * SessionQuestion is one clarification question an agent asked the
 * user through the bacio channel's `ask_user_question` MCP tool
 * (BACI-53). It mirrors a single AskUserQuestion call: the questions
 * array goes in, the user's answers come back. Local-only — never
 * synced.
 * 
 * RequestUUID is the UUIDv7 the channel mints at ask time. The
 * channel uses it in its in-memory request_uuid -> JSON-RPC id map
 * to correlate the parked reply with the answered row when it
 * re-polls.
 * 
 * IssueKey is the issue key of the session's open claim at ask time,
 * when there was one. Empty for asks made without an active claim
 * (e.g. the agent asking a setup question before claiming anything).
 * 
 * AskedBy is the persistent agent identity that posed the question.
 * AnsweredBy is the actor who responded (typically the OS user via
 * the TUI/desktop, or "api" for REST callers without an X-Actor).
 * Empty until the row leaves the open state.
 */
export class SessionQuestion {
    /**
     * ID / SessionPK are server-time fields — `omitempty` so dry-run
     * projections (which can't know them yet) emit the same JSON shape
     * as real calls minus the unknown fields.
     */
    "id"?: number;
    "session_pk"?: number;
    "session_id"?: string;
    "request_uuid": string;
    "issue_key"?: string;

    /**
     * PipelineJobID (Pipeline) is the pipeline_jobs row this question is
     * parented to — the running job of the asking session's in_pipeline
     * card. An open question on the current job is the controller
     * engine's "halt Auto, waiting on the user" signal (§6.1). Nil (and
     * omitted) for legacy / non-pipeline questions.
     */
    "pipeline_job_id"?: number | null;
    "payload": QuestionPayload;
    "answers"?: QuestionAnswers;
    "state": QuestionState;
    "asked_at": time$0.Time;
    "answered_at"?: time$0.Time | null;
    "asked_by": string;
    "answered_by"?: string;

    /** Creates a new SessionQuestion instance. */
    constructor($$source: Partial<SessionQuestion> = {}) {
        if (!("request_uuid" in $$source)) {
            this["request_uuid"] = "";
        }
        if (!("payload" in $$source)) {
            this["payload"] = (new QuestionPayload());
        }
        if (!("state" in $$source)) {
            this["state"] = QuestionState.$zero;
        }
        if (!("asked_at" in $$source)) {
            this["asked_at"] = null;
        }
        if (!("asked_by" in $$source)) {
            this["asked_by"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionQuestion instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionQuestion {
        const $$createField6_0 = $$createType12;
        const $$createField7_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("payload" in $$parsedSource) {
            $$parsedSource["payload"] = $$createField6_0($$parsedSource["payload"]);
        }
        if ("answers" in $$parsedSource) {
            $$parsedSource["answers"] = $$createField7_0($$parsedSource["answers"]);
        }
        return new SessionQuestion($$parsedSource as Partial<SessionQuestion>);
    }
}

export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StateTodo = "todo",
    StateInReview = "in_review",
    StateDone = "done",
    StateCancelled = "cancelled",

    /**
     * StateInPipeline / StateToBeShipped are the Pipeline-page columns.
     * A card's column is its issue state: In Pipeline = a chain of
     * dispatch jobs is being run against it by the controller engine;
     * To Be Shipped = the FIFO queue of finished cards waiting to ship.
     * Both are non-terminal. They are appended after the legacy set so
     * every surface that builds columns from AllStates() keeps its
     * existing ordering; the Pipeline UI keys on these states directly.
     */
    StateInPipeline = "in_pipeline",
    StateToBeShipped = "to_be_shipped",
};

/**
 * UserMessage is one BACI-286 user→agent steer message: a free-form
 * note the user pushes at a specific busy session, delivered by the
 * bacio channel at the worker's next turn boundary as a
 * `<channel kind="message">` tag. Unlike an AgentDispatch it is NOT
 * matched/bound and carries no ack — it is fire-and-forget, scoped to a
 * single session.
 * 
 * SessionPK is the agent_sessions PK; SessionID is the external session
 * id lifted alongside it by the store's join so callers (the channel,
 * the REST surface) don't need a second lookup. ConsumedAt is the only
 * delivery signal: nil = un-consumed (not yet pushed), non-nil = the
 * channel drained + pushed it. Like a dispatch's `delivered`, that is
 * not proof the agent acted on the message.
 */
export class UserMessage {
    "id": number;
    "session_pk": number;
    "session_id": string;
    "repo_id": number;
    "body": string;
    "created_by": string;
    "created_at": time$0.Time;
    "consumed_at"?: time$0.Time | null;

    /** Creates a new UserMessage instance. */
    constructor($$source: Partial<UserMessage> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("session_pk" in $$source)) {
            this["session_pk"] = 0;
        }
        if (!("session_id" in $$source)) {
            this["session_id"] = "";
        }
        if (!("repo_id" in $$source)) {
            this["repo_id"] = 0;
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("created_by" in $$source)) {
            this["created_by"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserMessage instance from a string or object.
     */
    static createFrom($$source: any = {}): UserMessage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserMessage($$parsedSource as Partial<UserMessage>);
    }
}

// Private type creation functions
const $$createType0 = AnthropicBlock.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = AnthropicMessage.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = AnthropicUsage.createFrom;
const $$createType5 = AnthropicTurn.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Array($Create.Any);
const $$createType8 = QuestionOption.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = QuestionItem.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = QuestionPayload.createFrom;
var $$createType13 = (function $$initCreateType13(...args: any[]): any {
    if ($$createType13 === $$initCreateType13) {
        $$createType13 = $$createType14;
    }
    return $$createType13(...args);
});
const $$createType14 = $Create.Map($Create.Any, $Create.Any);
