// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * BoardCard is one kanban card — one bacio issue, shaped for the
 * imported UI kit. Fields beyond the issue itself: Taken (an agent
 * holds an open claim on this issue), WaitingState (a dispatch is
 * queued or delivered but no claim yet — the struct carries why and
 * the mode involved, BACI-145), ActiveVerb (the lower-cased
 * prompt-template label of the newest open claim's dispatch — e.g.
 * "designing", "planning"), and TodosDone / TodosTotal (the TodoWrite
 * progress of the claiming session).
 */
export class BoardCard {
    "key": string;
    "column": string;
    "columnLabel": string;
    "title": string;
    "tags": string[];
    "assignees": string[];
    "claude": boolean;
    "taken": boolean;

    /**
     * WaitingState (BACI-145) explains a card's pre-claim spinner.
     * nil when the issue isn't waiting on a dispatch (the common case);
     * non-nil when iss.WaitingForClaim is true, carrying the
     * no-agent / blocked-by-cap / delivered distinction plus the mode
     * the cap or worker job is on. Replaces the older
     * `waitingForClaim` + `waitingDispatchDelivered` booleans on the
     * wire so the React tree and TUI render the same label.
     */
    "waitingState"?: WaitingState | null;

    /**
     * ActiveVerb is the lower-cased display label of the prompt template
     * behind the newest open claim's most recent non-cancelled dispatch
     * — e.g. "designing", "planning", or a custom template's lowered
     * Name. Empty when the issue isn't taken, when no dispatch matches,
     * or when the template was deleted.
     */
    "activeVerb"?: string;

    /**
     * TodosDone and TodosTotal mirror the TodoWrite progress of the
     * session that holds the newest open claim on this issue. Both
     * zero when the issue isn't taken or the session never wrote a
     * TodoList. The UI hides the Tasks counter when TodosTotal == 0.
     */
    "todosDone": number;
    "todosTotal": number;

    /**
     * OpenQuestions are the BACI-53 ask_user_question rows posed by
     * the winning claim's session against THIS issue. Drives the
     * "? N — <header>" pill on the kanban card and the click-to-open
     * answer modal. Empty when the issue isn't taken or the agent
     * hasn't asked anything yet. The full QuestionPayload is fetched
     * on demand via /agents/questions/{id} when the user opens the
     * modal — the bare ID + a short summary is enough to render the
     * badge.
     */
    "openQuestions"?: BoardCardQuestion[];

    /**
     * Todos (BACI-75) carries the per-task TodoWrite rows of the
     * session that holds the newest open claim, scoped to THIS card's
     * issue. Same data the TodosDone/TodosTotal counts summarise —
     * surfaced so the kanban card's expandable "Tasks n/m" pill can
     * render the list inline without a follow-up fetch. Empty (and
     * omitted from JSON) on untaken cards / when the session never
     * wrote a TodoList for this issue.
     */
    "todos"?: BoardCardTodo[];

    /**
     * Archived (BACI-68) mirrors the underlying issue's archived_at —
     * true iff the column is non-NULL. When display.show_archived is
     * on, the card surfaces with this flag set so the UI can render
     * it visibly muted (lower opacity, "archived" pill, etc.). When
     * display.show_archived is off, archived rows are filtered out
     * earlier by the IncludeArchived parameter on Assemble — so this
     * is only ever true on a board the user has explicitly opted in
     * to seeing.
     */
    "archived"?: boolean;

    /**
     * BlockedBy (BACI-114) carries the keys + states of every open-
     * state `blocks` edge pointing AT this issue. Empty (and omitted
     * from JSON) when the issue is unblocked. Used by the kanban
     * blocked-icon indicator and the click-to-show-blockers popover
     * on each card; the issue-workspace rail's full relations panel
     * goes through the brief's RelationsDTO instead so the chip
     * surface covers all four edge types, not just blocks.
     */
    "blockedBy"?: BoardCardBlocker[];

    /** Creates a new BoardCard instance. */
    constructor($$source: Partial<BoardCard> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("column" in $$source)) {
            this["column"] = "";
        }
        if (!("columnLabel" in $$source)) {
            this["columnLabel"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("assignees" in $$source)) {
            this["assignees"] = [];
        }
        if (!("claude" in $$source)) {
            this["claude"] = false;
        }
        if (!("taken" in $$source)) {
            this["taken"] = false;
        }
        if (!("todosDone" in $$source)) {
            this["todosDone"] = 0;
        }
        if (!("todosTotal" in $$source)) {
            this["todosTotal"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BoardCard instance from a string or object.
     */
    static createFrom($$source: any = {}): BoardCard {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        const $$createField8_0 = $$createType2;
        const $$createField12_0 = $$createType4;
        const $$createField13_0 = $$createType6;
        const $$createField15_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        if ("assignees" in $$parsedSource) {
            $$parsedSource["assignees"] = $$createField5_0($$parsedSource["assignees"]);
        }
        if ("waitingState" in $$parsedSource) {
            $$parsedSource["waitingState"] = $$createField8_0($$parsedSource["waitingState"]);
        }
        if ("openQuestions" in $$parsedSource) {
            $$parsedSource["openQuestions"] = $$createField12_0($$parsedSource["openQuestions"]);
        }
        if ("todos" in $$parsedSource) {
            $$parsedSource["todos"] = $$createField13_0($$parsedSource["todos"]);
        }
        if ("blockedBy" in $$parsedSource) {
            $$parsedSource["blockedBy"] = $$createField15_0($$parsedSource["blockedBy"]);
        }
        return new BoardCard($$parsedSource as Partial<BoardCard>);
    }
}

/**
 * BoardCardBlocker (BACI-114) is one open `blocks` edge pointing at
 * this card. Key is the canonical PREFIX-N of the blocker; State is
 * the blocker's state at assembly time. Title is intentionally NOT
 * on the wire — the React popover joins it from the same `cards`
 * array (Option A: thin renderer over data the brief already has).
 */
export class BoardCardBlocker {
    "key": string;
    "state": model$0.State;

    /** Creates a new BoardCardBlocker instance. */
    constructor($$source: Partial<BoardCardBlocker> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = model$0.State.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BoardCardBlocker instance from a string or object.
     */
    static createFrom($$source: any = {}): BoardCardBlocker {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BoardCardBlocker($$parsedSource as Partial<BoardCardBlocker>);
    }
}

/**
 * BoardCardQuestion is one open ask_user_question row surfaced on
 * the issue's kanban card. Header is the user-facing tag (≤12 chars,
 * the same field AskUserQuestion uses); FirstQuestion is the full
 * text of the first question in the payload (intended as the brief
 * detail next to the pill); Count is len(payload.questions) so a
 * multi-question modal can advertise "answer 3 questions".
 */
export class BoardCardQuestion {
    "id": number;
    "header": string;
    "firstQuestion": string;
    "count": number;
    "askedAt": time$0.Time;

    /** Creates a new BoardCardQuestion instance. */
    constructor($$source: Partial<BoardCardQuestion> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("header" in $$source)) {
            this["header"] = "";
        }
        if (!("firstQuestion" in $$source)) {
            this["firstQuestion"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }
        if (!("askedAt" in $$source)) {
            this["askedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BoardCardQuestion instance from a string or object.
     */
    static createFrom($$source: any = {}): BoardCardQuestion {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BoardCardQuestion($$parsedSource as Partial<BoardCardQuestion>);
    }
}

/**
 * BoardCardTodo is one TodoWrite row surfaced on a kanban card —
 * the inline-expansion list under the "Tasks n/m" pill. A thinner
 * sibling of agentcards.SessionTodoDTO: no IssueKey field, because
 * rows are pre-filtered server-side to this card's own issue.
 */
export class BoardCardTodo {
    "content": string;
    "status": string;

    /** Creates a new BoardCardTodo instance. */
    constructor($$source: Partial<BoardCardTodo> = {}) {
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BoardCardTodo instance from a string or object.
     */
    static createFrom($$source: any = {}): BoardCardTodo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BoardCardTodo($$parsedSource as Partial<BoardCardTodo>);
    }
}

/**
 * WaitingKind classifies WHY a card's queued / delivered dispatch
 * hasn't yet flowed into an open claim (BACI-145). The three values
 * map to the three distinct waiting reasons the kanban surfaces:
 * 
 *   - WaitingNoAgent: dispatch is queued, no free agent in the
 *     candidate pool — the matcher hasn't bound it yet.
 *   - WaitingBlockedByMode: dispatch is queued, the matcher *could*
 *     bind it except the template's concurrency_limit is full for
 *     this (repo, mode).
 *   - WaitingDelivered: the worker has the Task in hand (BACI-130 sub-
 *     state). The spinner stays but the cancel affordance drops.
 * 
 * Stable string values so the wire shape doesn't churn between
 * frontend re-deploys and so the TS helper can switch on the same
 * literals.
 */
export enum WaitingKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    WaitingNoAgent = "queued_no_agent",
    WaitingBlockedByMode = "queued_blocked",
    WaitingDelivered = "delivered",
};

/**
 * WaitingState (BACI-145) carries the reason a card's queued or
 * delivered dispatch is waiting, plus — when applicable — the mode
 * the cap or worker job is on. Drives the explanatory label next to
 * the spinner on the kanban card, the issue workspace lock banner,
 * and the TUI board's per-card waiting label.
 * 
 * Mode and ActionLabel are populated when WaitingKind is
 * WaitingBlockedByMode (the cap is on this mode) or WaitingDelivered
 * (the worker is running this mode). Empty for WaitingNoAgent — the
 * label doesn't name a mode in that case.
 */
export class WaitingState {
    "kind": WaitingKind;
    "mode"?: model$0.DispatchMode;
    "actionLabel"?: string;

    /** Creates a new WaitingState instance. */
    constructor($$source: Partial<WaitingState> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = WaitingKind.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WaitingState instance from a string or object.
     */
    static createFrom($$source: any = {}): WaitingState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WaitingState($$parsedSource as Partial<WaitingState>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = WaitingState.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = BoardCardQuestion.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = BoardCardTodo.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = BoardCardBlocker.createFrom;
const $$createType8 = $Create.Array($$createType7);
