// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BoardCard is one kanban card — one bacio issue, shaped for the
 * imported UI kit. Fields beyond the issue itself: Taken (an agent
 * holds an open claim on this issue), WaitingForClaim (a dispatch is
 * queued but no claim yet), ActiveVerb (the lower-cased
 * prompt-template label of the newest open claim's dispatch — e.g.
 * "designing", "planning"), and TodosDone / TodosTotal (the TodoWrite
 * progress of the claiming session).
 */
export class BoardCard {
    "key": string;
    "column": string;
    "columnLabel": string;
    "title": string;
    "tags": string[];
    "assignees": string[];
    "claude": boolean;
    "taken": boolean;
    "waitingForClaim": boolean;

    /**
     * ActiveVerb is the lower-cased display label of the prompt template
     * behind the newest open claim's most recent non-cancelled dispatch
     * — e.g. "designing", "planning", or a custom template's lowered
     * Name. Empty when the issue isn't taken, when no dispatch matches,
     * or when the template was deleted.
     */
    "activeVerb"?: string;

    /**
     * TodosDone and TodosTotal mirror the TodoWrite progress of the
     * session that holds the newest open claim on this issue. Both
     * zero when the issue isn't taken or the session never wrote a
     * TodoList. The UI hides the Tasks counter when TodosTotal == 0.
     */
    "todosDone": number;
    "todosTotal": number;

    /** Creates a new BoardCard instance. */
    constructor($$source: Partial<BoardCard> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("column" in $$source)) {
            this["column"] = "";
        }
        if (!("columnLabel" in $$source)) {
            this["columnLabel"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("assignees" in $$source)) {
            this["assignees"] = [];
        }
        if (!("claude" in $$source)) {
            this["claude"] = false;
        }
        if (!("taken" in $$source)) {
            this["taken"] = false;
        }
        if (!("waitingForClaim" in $$source)) {
            this["waitingForClaim"] = false;
        }
        if (!("todosDone" in $$source)) {
            this["todosDone"] = 0;
        }
        if (!("todosTotal" in $$source)) {
            this["todosTotal"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BoardCard instance from a string or object.
     */
    static createFrom($$source: any = {}): BoardCard {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        if ("assignees" in $$parsedSource) {
            $$parsedSource["assignees"] = $$createField5_0($$parsedSource["assignees"]);
        }
        return new BoardCard($$parsedSource as Partial<BoardCard>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
