package client

import (
	"context"
	"errors"
	"fmt"
	"path/filepath"
	"slices"
	"strings"
	"time"

	"github.com/mrgeoffrich/bacio/internal/cli/inputs"
	"github.com/mrgeoffrich/bacio/internal/model"
	"github.com/mrgeoffrich/bacio/internal/store"
)

// resolveBaseBranchForIssueKey is the BACI-226 resolver entry point
// for the targeted-pending dispatch creation paths: given the
// caller's issue_key (which may legitimately be empty for an
// issue-less dispatch like a setup nudge), load the issue + its
// optional feature and resolve via model.ResolveBaseBranch. Returns
// "" when the issue_key is empty so the stub omits the
// <base_branch> tag (no PR to target) — read sites use the
// resolver's fallback to recover a usable value.
func (c *localClient) resolveBaseBranchForIssueKey(ctx context.Context, repo *model.Repo, issueKey string) (string, error) {
	if issueKey == "" {
		return "", nil
	}
	iss, err := c.GetIssueByKey(ctx, repo, issueKey)
	if err != nil {
		return "", err
	}
	return c.resolveBaseBranchForIssue(iss), nil
}

// resolveBaseBranchForIssue is the BACI-226 resolver pass once an
// issue is already in hand (the auto-dispatch path, the TUI picker,
// etc.). Falls back to model.DefaultBaseBranch when the feature
// lookup fails — the resolver's invariant is "never empty" and
// blocking the dispatch on a vanished feature would be punitive for
// what is purely a derived field.
func (c *localClient) resolveBaseBranchForIssue(iss *model.Issue) string {
	if iss == nil {
		return model.DefaultBaseBranch
	}
	var feat *model.Feature
	if iss.FeatureID != nil {
		f, err := c.store.GetFeatureByID(*iss.FeatureID)
		if err == nil {
			feat = f
		}
	}
	return model.ResolveBaseBranch(iss, feat)
}

func (c *localClient) CreateDispatch(ctx context.Context, repo *model.Repo, in inputs.AgentDispatchInput, dryRun bool) (*model.AgentDispatch, error) {
	if in.TargetAgent == "" && in.TargetSession == "" {
		return nil, fmt.Errorf("dispatch requires a target — pass --to <agent> and/or --session <id>")
	}

	var agentID *int64
	if in.TargetAgent != "" {
		ag, err := c.store.GetAgentByName(in.TargetAgent)
		if err != nil {
			if errors.Is(err, store.ErrNotFound) {
				return nil, fmt.Errorf("no agent identity named %q is registered", in.TargetAgent)
			}
			return nil, err
		}
		agentID = &ag.ID
	}
	if in.TargetSession != "" {
		if _, err := c.store.GetAgentSession(in.TargetSession); err != nil {
			if errors.Is(err, store.ErrNotFound) {
				return nil, fmt.Errorf("session %q is not registered", in.TargetSession)
			}
			return nil, err
		}
	}

	var issueID *int64
	var issueKey string
	if in.IssueKey != "" {
		iss, err := c.GetIssueByKey(ctx, repo, in.IssueKey)
		if err != nil {
			if errors.Is(err, store.ErrNotFound) {
				return nil, fmt.Errorf("issue %s does not exist in repo %s", in.IssueKey, repo.Prefix)
			}
			return nil, err
		}
		issueID = &iss.ID
		issueKey = iss.Key
	}

	mode := model.DispatchMode(in.Mode)
	// BACI-76: the per-mode brief no longer goes in the dispatch
	// payload — it is the per-mode subagent's system prompt now
	// (`.claude/agents/bacio-<mode>-worker.md`, generated by
	// `bacio install-agent`). The payload is the rewritten preamble
	// (telling the supervisor to spawn that subagent) plus a tiny stub
	// naming the ticket, mode, and subagent type. An untyped mode
	// produces no stub, so the payload is just the free-form note.
	preamble, err := c.store.GetDispatchPreamble()
	if err != nil {
		return nil, err
	}
	// BACI-226: stamp <base_branch> into the stub at creation time so
	// targeted-pending dispatches (which never go through the matcher
	// bind step) carry the correct value from the start. Queued
	// dispatches re-render at BindQueuedDispatch with the bind-time
	// resolved value, but seeding the initial render here keeps the
	// pre-bind payload coherent for any consumer that reads it before
	// the matcher fires.
	baseBranch, err := c.resolveBaseBranchForIssueKey(ctx, repo, in.IssueKey)
	if err != nil {
		return nil, err
	}
	stub := model.DispatchStub{IssueKey: issueKey, Mode: string(mode), BaseBranch: baseBranch}
	if mode != "" {
		stub.SubagentType = model.SubagentTypeForTemplate(string(mode))
	}
	payload := model.ComposeDispatchPayload(preamble, stub, in.Message)

	if dryRun {
		return &model.AgentDispatch{
			RepoID:          repo.ID,
			RepoPrefix:      repo.Prefix,
			TargetAgentID:   agentID,
			TargetAgentName: in.TargetAgent,
			TargetSessionID: in.TargetSession,
			IssueID:         issueID,
			IssueKey:        issueKey,
			Mode:            mode,
			Payload:         payload,
			Status:          model.DispatchPending,
			CreatedBy:       c.actor,
			CreatedAt:       time.Now().UTC(),
		}, nil
	}

	d, err := c.store.AddDispatch(store.AddDispatchIn{
		RepoID:          repo.ID,
		TargetAgentID:   agentID,
		TargetSessionID: in.TargetSession,
		IssueID:         issueID,
		Mode:            mode,
		Payload:         payload,
		CreatedBy:       c.actor,
	})
	if err != nil {
		return nil, err
	}
	c.recordOp(model.HistoryEntry{
		RepoID: &repo.ID, RepoPrefix: repo.Prefix,
		Op: "agent.dispatch", Kind: "agent",
		TargetID: &d.ID, TargetLabel: dispatchTargetLabel(d),
		Details: dispatchDetails(d),
	})
	return d, nil
}

// AutoDispatchIssue (BACI-40, rewired by BACI-51) is the state-gated
// auto-pick dispatch verb shared by the desktop per-card action button,
// the REST `POST /repos/{prefix}/issues/{key}/dispatch` route, and the
// CLI's target-less `bacio agent dispatch <key> --mode <stage>`.
//
// As of BACI-51 this is the **enqueue path**: it re-checks the mode's
// state-gate, then inserts a target-less `queued` dispatch the
// background matcher will bind to a free agent when one frees up.
// Never errors with "no free agent" — that case is now expressed as a
// queued row in the per-(repo, mode) FIFO. Targeted dispatches
// (CreateDispatch with --to/--session) still go straight to pending.
func (c *localClient) AutoDispatchIssue(ctx context.Context, repo *model.Repo, issueKey, mode string, dryRun bool) (*model.AgentDispatch, error) {
	if repo == nil {
		return nil, fmt.Errorf("AutoDispatchIssue requires a repo")
	}
	parsedMode, err := model.ParseDispatchMode(mode)
	if err != nil {
		return nil, err
	}
	if parsedMode == "" {
		return nil, fmt.Errorf("a dispatch mode is required")
	}

	// State-gate: the prompt for this stage must be valid to run from
	// the issue's current state. The desktop UI already gates the
	// per-card action button on this; re-check here so a stale UI or
	// a CLI/REST caller can't queue a prompt the state doesn't allow.
	iss, err := c.GetIssueByKey(ctx, repo, issueKey)
	if err != nil {
		return nil, err
	}
	// BACI-68: refuse to dispatch an archived issue. The kanban card
	// for an archived todo wouldn't render an action button by default,
	// but the REST/CLI entry points (and a stale desktop view) could
	// still send a dispatch through — block it here so the manual
	// archive lever isn't quietly bypassed.
	if iss.ArchivedAt != nil {
		return nil, fmt.Errorf("issue %s is archived; unarchive it before dispatching", iss.Key)
	}
	gates, err := c.GetPromptStates(ctx)
	if err != nil {
		return nil, err
	}
	if !slices.Contains(gates[mode], string(iss.State)) {
		return nil, fmt.Errorf("the %s prompt can't run from a %s issue", mode, iss.State)
	}

	// BACI-76: the queued dispatch carries the rewritten preamble plus
	// a tiny stub (ticket / mode / subagent type) — not the full
	// per-mode brief, which is now the subagent's system prompt. The
	// matcher's later bind + drain hands this short payload to the
	// supervisor, which spawns the named per-mode subagent.
	preamble, err := c.store.GetDispatchPreamble()
	if err != nil {
		return nil, err
	}
	// BACI-226: render <base_branch> into the queue-time stub using
	// the resolver against the current issue + feature. The matcher
	// re-renders the payload at BindQueuedDispatch using the freshly-
	// resolved bind-time value (which is also the value the BACI-227
	// concurrency cap groups by), so a per-issue / per-feature override
	// added between queue and bind still reaches the worker.
	baseBranch := c.resolveBaseBranchForIssue(iss)
	payload := model.ComposeDispatchPayload(preamble, model.DispatchStub{
		IssueKey:     iss.Key,
		Mode:         string(parsedMode),
		BaseBranch:   baseBranch,
		SubagentType: model.SubagentTypeForTemplate(string(parsedMode)),
	}, "")

	if dryRun {
		return &model.AgentDispatch{
			RepoID:     repo.ID,
			RepoPrefix: repo.Prefix,
			IssueID:    &iss.ID,
			IssueKey:   iss.Key,
			Mode:       parsedMode,
			Payload:    payload,
			BaseBranch: baseBranch,
			Status:     model.DispatchQueued,
			CreatedBy:  c.actor,
			CreatedAt:  time.Now().UTC(),
		}, nil
	}

	d, err := c.store.AddDispatch(store.AddDispatchIn{
		RepoID:        repo.ID,
		IssueID:       &iss.ID,
		Mode:          parsedMode,
		Payload:       payload,
		CreatedBy:     c.actor,
		InitialStatus: model.DispatchQueued,
	})
	if err != nil {
		return nil, err
	}
	c.recordOp(model.HistoryEntry{
		RepoID: &repo.ID, RepoPrefix: repo.Prefix,
		Op: "agent.queue", Kind: "agent",
		TargetID: &d.ID, TargetLabel: iss.Key,
		Details: dispatchDetails(d),
	})
	return d, nil
}

// AutoDispatchIssueWithFollowOn (BACI-209) is the compound enqueue verb
// that writes a primary queued dispatch AND a dormant follow-on linked
// to it, both in one store transaction. The desktop kanban's
// "Plan, then Implement" picker is the first caller; the REST route
// `POST /repos/{prefix}/issues/{key}/dispatch-chain` and
// `bacio agent dispatch-chain` all route through here so the
// gate + payload + audit-row shape stays in one place.
//
// Semantics:
//   - The primary state-gate is re-checked against the issue's current
//     state — same as AutoDispatchIssue. A gate-miss returns an error
//     before any insert.
//   - The follow-on's gate is NOT checked here. Same posture as
//     QueueFollowOnDispatch (BACI-195): the gate runs at fire time
//     when the controller's promote sweep clears the dormant link.
//     Queueing `implement` while the parent is still planning is the
//     canonical case the dropped queue-time gate enabled.
//   - Two audit rows: `agent.queue` for the parent (same as
//     AutoDispatchIssue's emit) plus `agent.followon.queue` for the
//     dormant follow-on. Existing `bacio history --op` queries keep
//     working unchanged.
//   - dry-run projects both rows without touching the DB. The caller
//     emits the parent's projection (the kanban primary affordance);
//     the follow-on rides on the next BoardCard refresh via
//     card.followOn.
func (c *localClient) AutoDispatchIssueWithFollowOn(ctx context.Context, repo *model.Repo, issueKey, mode, followOnMode string, dryRun bool) (parent, followOn *model.AgentDispatch, err error) {
	if repo == nil {
		return nil, nil, fmt.Errorf("AutoDispatchIssueWithFollowOn requires a repo")
	}
	parsedMode, err := model.ParseDispatchMode(mode)
	if err != nil {
		return nil, nil, err
	}
	if parsedMode == "" {
		return nil, nil, fmt.Errorf("a dispatch mode is required")
	}
	parsedFollow, err := model.ParseDispatchMode(followOnMode)
	if err != nil {
		return nil, nil, err
	}
	if parsedFollow == "" {
		return nil, nil, fmt.Errorf("a follow-on dispatch mode is required")
	}
	if parsedFollow == parsedMode {
		// Defence at the boundary — the UI's dropdown skips the same-mode
		// pair, but a stale UI / CLI caller might still send one. Chaining
		// the same mode is meaningless (the controller's gate sweep would
		// either re-queue the same work or gate-fail-cancel it).
		return nil, nil, fmt.Errorf("follow-on mode %q matches the primary mode; pick a different next stage", parsedFollow)
	}

	iss, err := c.GetIssueByKey(ctx, repo, issueKey)
	if err != nil {
		return nil, nil, err
	}
	if iss.ArchivedAt != nil {
		return nil, nil, fmt.Errorf("issue %s is archived; unarchive it before dispatching", iss.Key)
	}
	gates, err := c.GetPromptStates(ctx)
	if err != nil {
		return nil, nil, err
	}
	if !slices.Contains(gates[mode], string(iss.State)) {
		return nil, nil, fmt.Errorf("the %s prompt can't run from a %s issue", mode, iss.State)
	}

	// Compose the parent's payload the same way AutoDispatchIssue does —
	// preamble + a stub naming the ticket, mode, and subagent type.
	preamble, err := c.store.GetDispatchPreamble()
	if err != nil {
		return nil, nil, err
	}
	// BACI-226: same base-branch handling as AutoDispatchIssue's
	// single-row path. The chain's follow-on row is bound by the
	// matcher later and re-rendered at bind time, so we only need to
	// seed the parent's payload here.
	baseBranch := c.resolveBaseBranchForIssue(iss)
	payload := model.ComposeDispatchPayload(preamble, model.DispatchStub{
		IssueKey:     iss.Key,
		Mode:         string(parsedMode),
		BaseBranch:   baseBranch,
		SubagentType: model.SubagentTypeForTemplate(string(parsedMode)),
	}, "")

	if dryRun {
		now := time.Now().UTC()
		projParent := &model.AgentDispatch{
			RepoID:     repo.ID,
			RepoPrefix: repo.Prefix,
			IssueID:    &iss.ID,
			IssueKey:   iss.Key,
			Mode:       parsedMode,
			Payload:    payload,
			Status:     model.DispatchQueued,
			CreatedBy:  c.actor,
			CreatedAt:  now,
		}
		// The dry-run projection can't know the parent's id yet (no
		// INSERT ran), so QueuedAfterDispatchID is left nil on the
		// projected follow-on — same shape QueueFollowOnDispatch's
		// dry-run would produce against a not-yet-inserted parent.
		projFollow := &model.AgentDispatch{
			RepoID:     repo.ID,
			RepoPrefix: repo.Prefix,
			IssueID:    &iss.ID,
			IssueKey:   iss.Key,
			Mode:       parsedFollow,
			Status:     model.DispatchQueued,
			CreatedBy:  c.actor,
			CreatedAt:  now,
		}
		return projParent, projFollow, nil
	}

	parent, followOn, err = c.store.AddDispatchWithFollowOn(store.AddDispatchWithFollowOnIn{
		RepoID:       repo.ID,
		IssueID:      &iss.ID,
		Mode:         parsedMode,
		Payload:      payload,
		CreatedBy:    c.actor,
		FollowOnMode: parsedFollow,
	})
	if err != nil {
		return nil, nil, err
	}
	c.recordOp(model.HistoryEntry{
		RepoID: &repo.ID, RepoPrefix: repo.Prefix,
		Op: "agent.queue", Kind: "agent",
		TargetID: &parent.ID, TargetLabel: iss.Key,
		Details: dispatchDetails(parent),
	})
	c.recordOp(model.HistoryEntry{
		RepoID: &repo.ID, RepoPrefix: repo.Prefix,
		Op: "agent.followon.queue", Kind: "agent",
		TargetID: &followOn.ID, TargetLabel: iss.Key,
		Details: followOnDetailsForClient(followOn),
	})
	return parent, followOn, nil
}

// QueueFollowOnDispatch (BACI-179, BACI-195) queues a dormant follow-on
// dispatch against an issue's currently-in-flight (parent) dispatch.
// Resolves the parent via WaitingDispatchForIssue — the open dispatch
// the claimed issue is wearing — then delegates to
// store.AddFollowOnDispatch for the validate+insert. Returns the new
// dormant row.
//
// Validates the mode (must be parseable, must be non-empty). NB: the
// state-gate is **not** checked here — the whole point of a follow-on
// is to queue the *next* mode while the current one is still running,
// so the issue is almost always in a state the next-mode gate doesn't
// admit at queue time (e.g. queueing `implement` while a research-mode
// parent has the issue in_progress; implement's gate is `todo`). The
// gate is re-evaluated at **fire time** by the controller's promote
// sweep, which sees the issue's post-release state and either promotes
// the row to a regular queued dispatch (gate passes) or cancels it
// with op=agent.followon.gate_fail (gate fails). BACI-195 dropped the
// queue-time check that was previously here — see the matching
// fire-time logic in store.PromoteReadyFollowOns /
// controller.FollowOnSweepIfLeader.
//
// Writes one `agent.followon.queue` audit row attributed to the
// calling actor (vs the orphan-cancel sweep's bacio-controller
// attribution) so `bacio history --op agent.followon.queue` records
// who queued each follow-on.
//
// Phase 1 callers go through this method directly (e.g. tests / phase
// 2 wiring); Phase 2 promotes it to the Client interface so the CLI
// and REST surface share the same path.
func (c *localClient) QueueFollowOnDispatch(ctx context.Context, repo *model.Repo, issueKey string, mode string, dryRun bool) (*model.AgentDispatch, error) {
	if repo == nil {
		return nil, fmt.Errorf("QueueFollowOnDispatch requires a repo")
	}
	parsedMode, err := model.ParseDispatchMode(mode)
	if err != nil {
		return nil, err
	}
	if parsedMode == "" {
		return nil, fmt.Errorf("a dispatch mode is required")
	}
	iss, err := c.GetIssueByKey(ctx, repo, issueKey)
	if err != nil {
		return nil, err
	}
	parent, err := c.store.WaitingDispatchForIssue(repo.ID, iss.ID)
	if err != nil {
		return nil, err
	}
	if parent != nil {
		// Parent-acks variant: an in-flight dispatch is already on the
		// issue, queue the follow-on linked to it (BACI-179 path).
		if dryRun {
			// Project the would-be row — mirrors AutoDispatchIssue's dry-run
			// shape so the caller sees the same fields as a real insert.
			return &model.AgentDispatch{
				RepoID:                repo.ID,
				RepoPrefix:            repo.Prefix,
				IssueID:               &iss.ID,
				IssueKey:              iss.Key,
				Mode:                  parsedMode,
				Status:                model.DispatchQueued,
				CreatedBy:             c.actor,
				CreatedAt:             time.Now().UTC(),
				QueuedAfterDispatchID: &parent.ID,
			}, nil
		}
		d, err := c.store.AddFollowOnDispatch(repo.ID, parent.ID, parsedMode, c.actor)
		if err != nil {
			return nil, err
		}
		c.recordOp(model.HistoryEntry{
			RepoID: &repo.ID, RepoPrefix: repo.Prefix,
			Op: "agent.followon.queue", Kind: "agent",
			TargetID: &d.ID, TargetLabel: iss.Key,
			Details: followOnDetailsForClient(d),
		})
		return d, nil
	}
	// BACI-217: no in-flight parent dispatch — fall through to the
	// blockers-clear variant if the issue is blocked by at least one
	// open issue. Either branch lands an `agent.followon.queue` audit
	// row with the gate stamped in Details; an issue that is neither
	// in-flight nor blocked keeps today's error message verbatim.
	blockers, err := c.store.BlockersFor([]int64{iss.ID})
	if err != nil {
		return nil, err
	}
	openBlockers := 0
	for _, b := range blockers[iss.ID] {
		if b.BlockerState != model.StateDone && b.BlockerState != model.StateCancelled {
			openBlockers++
		}
	}
	if openBlockers == 0 {
		return nil, fmt.Errorf("issue %s has no active dispatch to follow on from", iss.Key)
	}
	if dryRun {
		// Project the would-be blockers-clear row — same shape as the
		// parent-acks dry-run, but with the blockers flag set and the
		// parent-id absent. The chip's "blocked by N" label is derived
		// server-side at next BoardCard refresh.
		return &model.AgentDispatch{
			RepoID:                   repo.ID,
			RepoPrefix:               repo.Prefix,
			IssueID:                  &iss.ID,
			IssueKey:                 iss.Key,
			Mode:                     parsedMode,
			Status:                   model.DispatchQueued,
			CreatedBy:                c.actor,
			CreatedAt:                time.Now().UTC(),
			QueuedUntilBlockersClear: true,
		}, nil
	}
	d, err := c.store.AddBlockerFollowOnDispatch(repo.ID, iss.ID, parsedMode, c.actor)
	if err != nil {
		return nil, err
	}
	c.recordOp(model.HistoryEntry{
		RepoID: &repo.ID, RepoPrefix: repo.Prefix,
		Op: "agent.followon.queue", Kind: "agent",
		TargetID: &d.ID, TargetLabel: iss.Key,
		Details: followOnDetailsForClient(d),
	})
	return d, nil
}

// CancelFollowOnDispatch (BACI-179) cancels the dormant follow-on
// attached to an issue. Idempotent: returns (nil, nil) when there is
// nothing to cancel. Writes one `agent.followon.cancel` audit row
// attributed to the calling actor when a row actually flipped — the
// orphan-cancel sweep writes the same op with `bacio-controller` as
// the actor so `bacio history --op agent.followon.cancel` distinguishes
// the two paths.
func (c *localClient) CancelFollowOnDispatch(ctx context.Context, repo *model.Repo, issueKey string, dryRun bool) (*model.AgentDispatch, error) {
	if repo == nil {
		return nil, fmt.Errorf("CancelFollowOnDispatch requires a repo")
	}
	iss, err := c.GetIssueByKey(ctx, repo, issueKey)
	if err != nil {
		return nil, err
	}
	existing, err := c.store.FollowOnForIssue(repo.ID, iss.ID)
	if err != nil {
		return nil, err
	}
	if existing == nil {
		// Idempotent no-op — mirror CancelDispatch's already-cancelled path.
		return nil, nil
	}
	if dryRun {
		proj := *existing
		proj.Status = model.DispatchCancelled
		return &proj, nil
	}
	cancelled, err := c.store.CancelFollowOnDispatch(repo.ID, iss.ID)
	if err != nil {
		return nil, err
	}
	if cancelled == nil {
		// Raced with the orphan-cancel sweep — that sweep already wrote
		// its own audit row, nothing to add here.
		return nil, nil
	}
	c.recordOp(model.HistoryEntry{
		RepoID: &repo.ID, RepoPrefix: repo.Prefix,
		Op: "agent.followon.cancel", Kind: "agent",
		TargetID: &cancelled.ID, TargetLabel: iss.Key,
		Details: followOnDetailsForClient(cancelled),
	})
	return cancelled, nil
}

// followOnDetailsForClient composes the audit-log Details string for
// client-driven follow-on ops (queue / cancel). Mirrors the
// controller-side followOnDetails helper — kept package-local here so
// the client doesn't import the controller package just for the
// helper. Same shape so a reader of `bacio history --op
// agent.followon.queue` sees identical fields regardless of which
// writer the row came from. BACI-217: also stamps `gate=parent` /
// `gate=blockers` so the audit log distinguishes the two variants.
func followOnDetailsForClient(d *model.AgentDispatch) string {
	if d == nil {
		return ""
	}
	parts := []string{fmt.Sprintf("dispatch_id=%d", d.ID)}
	if d.IssueKey != "" {
		parts = append(parts, "issue="+d.IssueKey)
	}
	if d.Mode != "" {
		parts = append(parts, "mode="+string(d.Mode))
	}
	if d.QueuedAfterDispatchID != nil {
		parts = append(parts, fmt.Sprintf("parent_dispatch_id=%d", *d.QueuedAfterDispatchID))
		parts = append(parts, "gate=parent")
	} else if d.QueuedUntilBlockersClear {
		parts = append(parts, "gate=blockers")
	}
	return strings.Join(parts, ",")
}

// WaitingDispatchForIssue returns the active (queued/pending/delivered)
// dispatch targeting an issue or (nil, nil) if none. Backs the
// spinner-as-cancel UI added in BACI-51.
func (c *localClient) WaitingDispatchForIssue(ctx context.Context, repo *model.Repo, issueKey string) (*model.AgentDispatch, error) {
	if repo == nil {
		return nil, fmt.Errorf("WaitingDispatchForIssue requires a repo")
	}
	iss, err := c.GetIssueByKey(ctx, repo, issueKey)
	if err != nil {
		return nil, err
	}
	return c.store.WaitingDispatchForIssue(repo.ID, iss.ID)
}

// InflightByModeForRepo (BACI-145) is the bulked sibling of
// CountInFlightByMode — one read per repo for the kanban / brief
// assembler's WaitingState derivation. Modes with zero in-flight rows
// are omitted from the map.
//
// BACI-227: superseded for the kanban / brief deriver by
// InflightByModeBaseForRepo. Retained for client-interface symmetry.
func (c *localClient) InflightByModeForRepo(ctx context.Context, repo *model.Repo) (map[model.DispatchMode]int, error) {
	if repo == nil {
		return nil, fmt.Errorf("InflightByModeForRepo requires a repo")
	}
	return c.store.InflightByModeForRepo(repo.ID)
}

// InflightByModeBaseForRepo (BACI-227) is the per-(mode, branch)
// sibling of InflightByModeForRepo. The kanban / brief WaitingState
// deriver reads this map so the per-card concurrency-cap label tracks
// the matcher's per-branch gate exactly.
func (c *localClient) InflightByModeBaseForRepo(ctx context.Context, repo *model.Repo) (map[store.InflightKey]int, error) {
	if repo == nil {
		return nil, fmt.Errorf("InflightByModeBaseForRepo requires a repo")
	}
	return c.store.InflightByModeBaseForRepo(repo.ID)
}

func (c *localClient) InboxDispatches(ctx context.Context, sessionID string) ([]*model.AgentDispatch, error) {
	sess, err := c.store.GetAgentSession(sessionID)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, fmt.Errorf("session %q is not registered — run `bacio agent register` first", sessionID)
		}
		return nil, err
	}
	// A session's inbox is everything aimed at the bare session id OR at
	// the agent identity behind it. Open items only (pending/delivered);
	// acked/cancelled are history.
	return c.store.ListDispatches(store.DispatchFilter{
		TargetAgentID:   sess.AgentID,
		TargetSessionID: sess.SessionID,
		Statuses:        []model.DispatchStatus{model.DispatchPending, model.DispatchDelivered},
	})
}

func (c *localClient) AckDispatch(ctx context.Context, in inputs.AgentAckInput, dryRun bool) (*model.AgentDispatch, error) {
	d, err := c.store.GetDispatch(in.ID)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, fmt.Errorf("no dispatch with id %d", in.ID)
		}
		return nil, err
	}
	if dryRun {
		proj := *d
		now := time.Now().UTC()
		proj.Status = model.DispatchAcked
		proj.AckedAt = &now
		proj.AckNote = in.Note
		return &proj, nil
	}
	acked, err := c.store.AckDispatch(in.ID, in.Note)
	if err != nil {
		return nil, err
	}
	c.recordOp(model.HistoryEntry{
		RepoID: &acked.RepoID, RepoPrefix: acked.RepoPrefix,
		Op: "agent.ack", Kind: "agent",
		TargetID: &acked.ID, TargetLabel: dispatchTargetLabel(acked),
		Details: dispatchDetails(acked),
	})
	return acked, nil
}

func (c *localClient) CancelDispatch(ctx context.Context, in inputs.AgentCancelInput, dryRun bool) (*model.AgentDispatch, error) {
	d, err := c.store.GetDispatch(in.ID)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, fmt.Errorf("no dispatch with id %d", in.ID)
		}
		return nil, err
	}
	if d.Status == model.DispatchAcked {
		return nil, fmt.Errorf("dispatch %d is already acked; cannot cancel", in.ID)
	}
	// BACI-130: a delivered dispatch is past the point where cancelling
	// the row does anything useful — the worker has the Task in hand
	// and the work is happening. Mirror the store-level reject here so
	// `--dry-run` reports the conflict instead of synthesising a
	// "would-be cancelled" projection.
	if d.Status == model.DispatchDelivered {
		return nil, fmt.Errorf("dispatch %d has been delivered; cannot cancel", in.ID)
	}
	if dryRun {
		proj := *d
		proj.Status = model.DispatchCancelled
		return &proj, nil
	}
	cancelled, err := c.store.CancelDispatch(in.ID)
	if err != nil {
		return nil, err
	}
	c.recordOp(model.HistoryEntry{
		RepoID: &cancelled.RepoID, RepoPrefix: cancelled.RepoPrefix,
		Op: "agent.cancel", Kind: "agent",
		TargetID: &cancelled.ID, TargetLabel: dispatchTargetLabel(cancelled),
		Details: dispatchDetails(cancelled),
	})
	return cancelled, nil
}

func (c *localClient) DrainDispatches(ctx context.Context, sessionID string) ([]*model.AgentDispatch, error) {
	sess, err := c.store.GetAgentSession(sessionID)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, fmt.Errorf("session %q is not registered", sessionID)
		}
		return nil, err
	}
	// Drain pending AND delivered — anything not yet acked. `delivered`
	// only means "we tried to hand it over once"; if that push was lost
	// (a dead channel process, a notification the session never surfaced)
	// the dispatch would be silently stranded. Re-surfacing un-acked
	// dispatches on every hook drain is the reliable recovery path — only
	// an ack retires a dispatch.
	open, err := c.store.ListDispatches(store.DispatchFilter{
		TargetAgentID:   sess.AgentID,
		TargetSessionID: sess.SessionID,
		Statuses:        []model.DispatchStatus{model.DispatchPending, model.DispatchDelivered},
	})
	if err != nil {
		return nil, err
	}
	return c.markDrained(open, sess.SessionID)
}

// markDrained flips any still-pending dispatches to delivered and returns
// the list unchanged otherwise. Already-delivered rows are passed through
// as-is (re-emitted by the caller until acked).
//
// BACI-160 gap 3: writes one `agent.deliver` history row per successful
// pending→delivered transition. Without this the moment a dispatch
// first reaches the worker is invisible in `bacio history` — readers
// would have to JOIN agent_dispatches.delivered_at instead of filtering
// the audit log by op. Only the in-loop pending check gates the audit
// write (already-delivered rows fall to the unchanged-passthrough
// branch above and never re-stamp).
//
// BACI-202: every pending→delivered emission is gated on a per-
// (dispatch, session) uniqueness claim against `dispatch_deliveries`.
// Two sessions sharing one agent identity (different claude_pid, same
// target_agent_id) would otherwise both surface the same dispatch
// through ListDispatches's agent-id-OR-session-id filter and double-
// deliver it. The losing session's drain falls through silently — no
// MarkDispatchDelivered call, no agent.deliver audit row, no entry in
// the returned slice — and the BACI-202 `dispatch_deliveries` row that
// the WINNING session inserted is the storage-layer source of truth
// for the uniqueness invariant. An empty sessionID short-circuits the
// gate so the legacy `DrainAgentDispatches` shape (which has no live
// callers but stays in the Client interface for symmetry) still
// drains to delivered without uniqueness gating.
func (c *localClient) markDrained(open []*model.AgentDispatch, sessionID string) ([]*model.AgentDispatch, error) {
	out := make([]*model.AgentDispatch, 0, len(open))
	for _, d := range open {
		if d.Status == model.DispatchPending {
			// BACI-202: claim the per-(dispatch, session) delivery slot
			// BEFORE the status flip + audit write. The losing session
			// of two concurrent drains gets claimed=false here and
			// skips the rest of this branch entirely.
			if sessionID != "" {
				claimed, err := c.store.ClaimDispatchDelivery(d.ID, sessionID)
				if err != nil {
					return nil, err
				}
				if !claimed {
					continue
				}
			}
			delivered, err := c.store.MarkDispatchDelivered(d.ID)
			if err != nil {
				return nil, err
			}
			c.recordOp(model.HistoryEntry{
				RepoID: &delivered.RepoID, RepoPrefix: delivered.RepoPrefix,
				Op: "agent.deliver", Kind: "agent",
				TargetID: &delivered.ID, TargetLabel: dispatchTargetLabel(delivered),
				Details: dispatchDetails(delivered),
			})
			out = append(out, delivered)
			continue
		}
		out = append(out, d)
	}
	return out, nil
}

func (c *localClient) RepoDispatches(ctx context.Context, repo *model.Repo) ([]*model.AgentDispatch, error) {
	if repo == nil {
		return nil, fmt.Errorf("RepoDispatches requires a repo")
	}
	return c.store.ListDispatches(store.DispatchFilter{RepoID: &repo.ID})
}

// SessionDispatches returns every dispatch targeting one session,
// newest first, regardless of status. Mirrors the targetsSession
// predicate used by the card surfaces — matches both the bare
// session id and the agent identity behind it. Empty agent id is
// fine (a registered session may not yet have an agent identity
// resolved); in that case only the session-id half of the filter
// applies. An unknown session returns the typed ErrNotFound from
// the underlying GetAgentSession so the caller can distinguish a
// missing session from "no dispatches".
func (c *localClient) SessionDispatches(ctx context.Context, sessionID string) ([]*model.AgentDispatch, error) {
	if sessionID == "" {
		return nil, fmt.Errorf("SessionDispatches requires a session_id")
	}
	sess, err := c.store.GetAgentSession(sessionID)
	if err != nil {
		return nil, err
	}
	return c.store.ListDispatches(store.DispatchFilter{
		TargetAgentID:   sess.AgentID,
		TargetSessionID: sess.SessionID,
	})
}

func (c *localClient) DrainAgentDispatches(ctx context.Context, repo *model.Repo, agentName string) ([]*model.AgentDispatch, error) {
	// An unscoped channel (no repo / no agents.json identity yet) has
	// nothing to drain — that's not an error, the channel just idles.
	if repo == nil || agentName == "" {
		return nil, nil
	}
	ag, err := c.store.GetAgentByName(agentName)
	if err != nil {
		// The identity isn't registered yet (no hook / register has run
		// in this repo) — transient, not an error. Idle until it is.
		if errors.Is(err, store.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	// Same pending-AND-delivered drain as DrainDispatches: an un-acked
	// dispatch stays drainable so a lost push can still be recovered. The
	// channel caller dedups within a process so it doesn't re-push every
	// poll tick; a fresh channel process re-pushes un-acked work.
	open, err := c.store.ListDispatches(store.DispatchFilter{
		RepoID:        &repo.ID,
		TargetAgentID: &ag.ID,
		Statuses:      []model.DispatchStatus{model.DispatchPending, model.DispatchDelivered},
	})
	if err != nil {
		return nil, err
	}
	// BACI-202: no session id is in scope on this path (legacy agent-
	// scoped drain). Pass "" so markDrained skips the per-(dispatch,
	// session) uniqueness gate. DrainAgentDispatches has no live
	// callers — the channel and the hook both call DrainDispatches with
	// a concrete session id — so this passthrough is purely defensive.
	return c.markDrained(open, "")
}

func (c *localClient) ListPromptTemplates(ctx context.Context) ([]*store.PromptTemplate, error) {
	return c.store.ListPromptTemplates()
}

func (c *localClient) GetPromptTemplate(ctx context.Context, slug string) (*store.PromptTemplate, error) {
	return c.store.GetPromptTemplateBySlug(slug)
}

func (c *localClient) AddPromptTemplate(ctx context.Context, in inputs.SettingsTemplateAddInput, dryRun bool) (*store.PromptTemplate, error) {
	addIn := store.AddPromptTemplateIn{
		Slug:          in.Slug,
		Name:          in.Name,
		Body:          in.Body,
		AllowedStates: stringsToStates(in.States),
		// IsBuiltin is never set by an agent-facing add — only the
		// migration's seed step and RestoreBuiltinPromptTemplates flip
		// it on.
		ConcurrencyLimit: in.ConcurrencyLimit,
	}
	if dryRun {
		return c.store.ValidateAddPromptTemplate(addIn)
	}
	t, err := c.store.AddPromptTemplate(addIn)
	if err != nil {
		return nil, err
	}
	id := t.ID
	c.recordOp(model.HistoryEntry{
		Op: "template.create", Kind: "app_setting",
		TargetID: &id, TargetLabel: "prompt_template:" + t.Slug,
		Details: fmt.Sprintf("slug=%s, name=%s", t.Slug, t.Name),
	})
	return t, nil
}

func (c *localClient) RenamePromptTemplate(ctx context.Context, in inputs.SettingsTemplateRenameInput, dryRun bool) (*store.PromptTemplate, error) {
	// A rename with empty NewSlug means "keep slug, change name"; copy
	// the existing slug in so the validator + store don't need to
	// special-case it.
	existing, err := c.store.GetPromptTemplateBySlug(in.Slug)
	if err != nil {
		return nil, err
	}
	target := store.RenamePromptTemplateIn{
		OldSlug: in.Slug,
		NewSlug: in.NewSlug,
		NewName: in.NewName,
	}
	if target.NewSlug == "" {
		target.NewSlug = in.Slug
	}
	if dryRun {
		// Project the would-be row without writing. Validate both slug
		// shapes; surface the existing row's other fields untouched.
		if _, err := store.ValidatePromptTemplateSlug(target.OldSlug); err != nil {
			return nil, fmt.Errorf("old slug: %w", err)
		}
		if _, err := store.ValidatePromptTemplateSlug(target.NewSlug); err != nil {
			return nil, fmt.Errorf("new slug: %w", err)
		}
		projected := *existing
		projected.Slug = target.NewSlug
		if target.NewName != "" {
			name, err := store.ValidatePromptTemplateName(target.NewName)
			if err != nil {
				return nil, err
			}
			projected.Name = name
		}
		return &projected, nil
	}
	renamed, err := c.store.RenamePromptTemplate(target)
	if err != nil {
		return nil, err
	}
	id := renamed.ID
	details := fmt.Sprintf("from=%s, to=%s, name=%s", in.Slug, renamed.Slug, renamed.Name)
	c.recordOp(model.HistoryEntry{
		Op: "template.rename", Kind: "app_setting",
		TargetID: &id, TargetLabel: "prompt_template:" + renamed.Slug,
		Details: details,
	})
	return renamed, nil
}

func (c *localClient) DeletePromptTemplate(ctx context.Context, in inputs.SettingsTemplateRmInput, dryRun bool) (*store.PromptTemplate, error) {
	existing, err := c.store.GetPromptTemplateBySlug(in.Slug)
	if err != nil {
		return nil, err
	}
	if dryRun {
		return existing, nil
	}
	removed, err := c.store.DeletePromptTemplate(in.Slug)
	if err != nil {
		return nil, err
	}
	id := removed.ID
	c.recordOp(model.HistoryEntry{
		Op: "template.delete", Kind: "app_setting",
		TargetID: &id, TargetLabel: "prompt_template:" + removed.Slug,
		Details: "slug=" + removed.Slug,
	})
	return removed, nil
}

func (c *localClient) RestoreBuiltinPromptTemplates(ctx context.Context, dryRun bool) ([]string, error) {
	if dryRun {
		// Compute the would-be list without touching the table.
		existing, err := c.store.ListPromptTemplates()
		if err != nil {
			return nil, err
		}
		present := make(map[string]bool, len(existing))
		for _, t := range existing {
			present[t.Slug] = true
		}
		var would []string
		for _, slug := range model.BuiltinTemplateSlugs() {
			if !present[slug] {
				would = append(would, slug)
			}
		}
		return would, nil
	}
	created, err := c.store.RestoreBuiltinPromptTemplates()
	if err != nil {
		return nil, err
	}
	if len(created) > 0 {
		c.recordOp(model.HistoryEntry{
			Op: "template.restore_defaults", Kind: "app_setting",
			TargetLabel: "prompt_template",
			Details:     "slugs=" + strings.Join(created, ","),
		})
	}
	return created, nil
}

func (c *localClient) SetPromptTemplateActionLabel(ctx context.Context, in inputs.SettingsTemplateSetActionLabelInput, dryRun bool) (*store.PromptTemplate, error) {
	existing, err := c.store.GetPromptTemplateBySlug(in.Slug)
	if err != nil {
		return nil, err
	}
	cleaned, err := store.ValidatePromptTemplateActionLabel(in.ActionLabel)
	if err != nil {
		return nil, err
	}
	if dryRun {
		// Project the would-be row without writing — mirrors the
		// dry-run shape every other template mutator uses.
		proj := *existing
		proj.ActionLabel = cleaned
		return &proj, nil
	}
	updated, err := c.store.SetPromptTemplateActionLabel(in.Slug, cleaned)
	if err != nil {
		return nil, err
	}
	id := updated.ID
	c.recordOp(model.HistoryEntry{
		Op: "template.set_action_label", Kind: "app_setting",
		TargetID: &id, TargetLabel: "prompt_template:" + updated.Slug,
		Details: fmt.Sprintf("slug=%s, action_label=%q", updated.Slug, updated.ActionLabel),
	})
	return updated, nil
}

func (c *localClient) SetPromptTemplateConcurrencyLimit(ctx context.Context, in inputs.SettingsTemplateSetConcurrencyInput, dryRun bool) (*store.PromptTemplate, error) {
	existing, err := c.store.GetPromptTemplateBySlug(in.Slug)
	if err != nil {
		return nil, err
	}
	cleaned, err := store.ValidateConcurrencyLimit(in.ConcurrencyLimit)
	if err != nil {
		return nil, err
	}
	if dryRun {
		// Project the would-be row without writing — mirrors the
		// dry-run shape every other template mutator uses.
		proj := *existing
		proj.ConcurrencyLimit = cleaned
		return &proj, nil
	}
	updated, err := c.store.SetPromptTemplateConcurrencyLimit(in.Slug, cleaned)
	if err != nil {
		return nil, err
	}
	id := updated.ID
	c.recordOp(model.HistoryEntry{
		Op: "template.set_concurrency", Kind: "app_setting",
		TargetID: &id, TargetLabel: "prompt_template:" + updated.Slug,
		Details: fmt.Sprintf("slug=%s, concurrency_limit=%d", updated.Slug, updated.ConcurrencyLimit),
	})
	return updated, nil
}

func (c *localClient) GetPromptTemplates(ctx context.Context) (map[string]string, error) {
	all, err := c.store.AllPromptTemplates()
	if err != nil {
		return nil, err
	}
	out := make(map[string]string, len(all))
	for m, t := range all {
		out[string(m)] = t
	}
	return out, nil
}

func (c *localClient) SetPromptTemplate(ctx context.Context, mode, body string, dryRun bool) error {
	m, err := model.ParseDispatchMode(mode)
	if err != nil {
		return err
	}
	if m == "" {
		return fmt.Errorf("prompt template requires a slug")
	}
	if dryRun {
		// Validate the body at the store boundary, then stop before the
		// write — same shape as every other --dry-run mutation.
		_, err := c.store.ValidatePromptTemplate(m, body)
		return err
	}
	if err := c.store.SetPromptTemplate(m, body); err != nil {
		return err
	}
	// Prompt templates are global, not repo-scoped — the audit row
	// carries no RepoID. recordOp never fails the user-visible action.
	op := "prompt_template.update"
	if strings.TrimSpace(body) == "" {
		op = "prompt_template.reset"
	}
	c.recordOp(model.HistoryEntry{
		Op: op, Kind: "app_setting",
		TargetLabel: "prompt_template:" + string(m),
		Details:     "slug=" + string(m),
	})
	return nil
}

func (c *localClient) GetPromptStates(ctx context.Context) (map[string][]string, error) {
	all, err := c.store.AllPromptStates()
	if err != nil {
		return nil, err
	}
	out := make(map[string][]string, len(all))
	for m, states := range all {
		ss := make([]string, len(states))
		for i, st := range states {
			ss[i] = string(st)
		}
		out[string(m)] = ss
	}
	return out, nil
}

func (c *localClient) SetPromptStates(ctx context.Context, mode string, states []string, dryRun bool) error {
	m, err := model.ParseDispatchMode(mode)
	if err != nil {
		return err
	}
	if m == "" {
		return fmt.Errorf("prompt state-gate requires a slug")
	}
	parsed := stringsToStates(states)
	if dryRun {
		// Validate the state set at the store boundary, then stop before
		// the write — same shape as every other --dry-run mutation.
		_, err := c.store.ValidatePromptStates(m, parsed)
		return err
	}
	if err := c.store.SetPromptStates(m, parsed); err != nil {
		return err
	}
	// Prompt state-gates are global, not repo-scoped — the audit row
	// carries no RepoID. recordOp never fails the user-visible action.
	op := "prompt_states.update"
	if len(states) == 0 {
		op = "prompt_states.reset"
	}
	c.recordOp(model.HistoryEntry{
		Op: op, Kind: "app_setting",
		TargetLabel: "prompt_states:" + string(m),
		Details:     "slug=" + string(m),
	})
	return nil
}

// stringsToStates is the wire-to-model helper for state-gate inputs.
// Each element is a model.State string cast directly; the validator on
// the store boundary rejects unknown values.
func stringsToStates(states []string) []model.State {
	out := make([]model.State, len(states))
	for i, s := range states {
		out[i] = model.State(s)
	}
	return out
}

// dispatchTargetLabel picks the most specific label for audit rows:
// the agent identity slug if there is one, else the session id.
func dispatchTargetLabel(d *model.AgentDispatch) string {
	if d.TargetAgentName != "" {
		return d.TargetAgentName
	}
	return d.TargetSessionID
}

// SetupDispatchCreator marks dispatches that the bacio channel itself
// enqueued to ask the agent to call the `register` tool — distinct from
// any human or supervisor creator. The channel filters on this value to
// keep EnsureSetupDispatch idempotent across restarts. Aliases
// model.SetupDispatchCreator (kept here for back-compat with existing
// callers; new code should reference the model constant so the store
// layer can use it without importing client).
const SetupDispatchCreator = model.SetupDispatchCreator

// buildSetupDispatchPayload renders the channel-emitted setup
// dispatch with the real session_id pre-filled. The agent sees this
// as a regular dispatch (so it lands via the proven push path, not a
// synthetic notification) and acks it via the normal reply tool.
//
// The session_id is substituted server-side rather than left as a
// literal placeholder (BACI-46): pre-filling makes the copy-paste path
// correct by construction, and the ValidateSessionID rule that refuses
// placeholder strings is the belt-and-braces guard against any future
// briefing change reintroducing the bug.
func buildSetupDispatchPayload(sessionID string) string {
	return "Call the bacio MCP `register` tool now with " +
		`{"session_id": "` + sessionID + `", ` +
		`"model": "<your model id>"} ` +
		"(session_id is already filled in for you; " +
		"model is optional but worth passing — " +
		"the model identifier looks like \"claude-opus-4-7\" or \"claude-sonnet-4-6\"). " +
		"This completes the registration; ack this dispatch via `reply` once you've called register."
}

func (c *localClient) EnsureSetupDispatch(ctx context.Context, repo *model.Repo, sessionID string) (*model.AgentDispatch, error) {
	if repo == nil || sessionID == "" {
		return nil, nil // channel runs idle until a session for its (host, claude_pid) exists
	}
	existing, err := c.store.ListDispatches(store.DispatchFilter{
		RepoID:          &repo.ID,
		TargetSessionID: sessionID,
		Statuses:        []model.DispatchStatus{model.DispatchPending, model.DispatchDelivered},
		CreatedBy:       SetupDispatchCreator,
	})
	if err != nil {
		return nil, err
	}
	if len(existing) > 0 {
		return existing[0], nil // idempotent — drain will re-push it next tick
	}
	d, err := c.store.AddDispatch(store.AddDispatchIn{
		RepoID:          repo.ID,
		TargetSessionID: sessionID,
		Payload:         buildSetupDispatchPayload(sessionID),
		CreatedBy:       SetupDispatchCreator,
	})
	if err != nil {
		return nil, err
	}
	c.recordOp(model.HistoryEntry{
		RepoID: &repo.ID, RepoPrefix: repo.Prefix,
		Op: "agent.dispatch", Kind: "agent", Actor: SetupDispatchCreator,
		TargetID: &d.ID, TargetLabel: dispatchTargetLabel(d),
		Details: dispatchDetails(d),
	})
	return d, nil
}

// buildPingDispatchPayload renders the body the bacio idle-pinger
// pushes to a long-idle session as a "are you still alive?" probe
// (BACI-57). Short and action-oriented like the setup-dispatch payload:
// the agent only needs to ack via the channel reply tool to refresh its
// own liveness; no business logic, no parameters.
func buildPingDispatchPayload() string {
	return "bacio idle-check: your session hasn't seen activity in over 1 hour. " +
		"Reply (ack) within 2 minutes to confirm you're still running, or bacio " +
		"will end your session as presumed-dead."
}

// EnsurePingDispatch is the idle-pinger's "are you still alive?" probe
// (BACI-57). Idempotent per session: skip if any pending|delivered
// ping already exists for this session (matches the
// SetupDispatchCreator pattern in EnsureSetupDispatch). Writes an
// agent.dispatch audit row on enqueue with Actor=IdlePingDispatchCreator
// — the forensic trail for "when did agent X get poked, and did they
// answer?" — and returns the existing in-flight ping (no insert) when
// one is already queued. A nil session is a no-op.
func (c *localClient) EnsurePingDispatch(ctx context.Context, sess *model.AgentSession) (*model.AgentDispatch, error) {
	if sess == nil || sess.SessionID == "" {
		return nil, nil
	}
	existing, err := c.store.ListDispatches(store.DispatchFilter{
		RepoID:          &sess.RepoID,
		TargetSessionID: sess.SessionID,
		Statuses:        []model.DispatchStatus{model.DispatchPending, model.DispatchDelivered},
		CreatedBy:       model.IdlePingDispatchCreator,
	})
	if err != nil {
		return nil, err
	}
	if len(existing) > 0 {
		return existing[0], nil // idempotent — drain will re-push it next tick
	}
	d, err := c.store.AddDispatch(store.AddDispatchIn{
		RepoID:          sess.RepoID,
		TargetSessionID: sess.SessionID,
		Payload:         buildPingDispatchPayload(),
		CreatedBy:       model.IdlePingDispatchCreator,
	})
	if err != nil {
		return nil, err
	}
	c.recordOp(model.HistoryEntry{
		RepoID: &sess.RepoID, RepoPrefix: sess.RepoPrefix,
		Op: "agent.dispatch", Kind: "agent", Actor: model.IdlePingDispatchCreator,
		TargetID: &d.ID, TargetLabel: dispatchTargetLabel(d),
		Details: dispatchDetails(d),
	})
	return d, nil
}

// CreateRescueDispatch (BACI-190) enqueues a `from="bacio-rescue"`
// channel event asking an idle supervisor to handle a dead worker's
// stranded worktree INLINE — no fresh Task spawn. Structural carve-
// out mirrors EnsureSetupDispatch / EnsurePingDispatch: bypass
// ComposeDispatchPayload (the per-mode brief preamble would tell the
// supervisor to spawn a subagent, exactly the wrong thing here) and
// write the whole rescue instruction inline.
//
// Eligibility (enforced here so the REST/Wails layers don't repeat
// the check):
//   - the original dispatch is pending or delivered (never acked /
//     cancelled / queued)
//   - its CreatedBy is a real per-mode creator (not bacio-channel /
//     bacio-channel-ping / bacio-rescue)
//   - its TargetSessionID is non-empty
//   - that target session is ended (EndedAt != nil)
//
// Target picking: a live, channel-connected, non-busy, registered
// session in the same repo, NOT the dead one. Freshest-last-seen
// first. Returns an error when nothing eligible exists.
//
// agent_id / worktree resolution is best-effort: parsed from the
// newest transcript document linked to the dispatch's issue. When no
// transcript is attached the rescue payload falls back to instructing
// the supervisor to `git worktree list` for candidates.
//
// Writes one `agent.rescue` audit row attributed to the calling
// actor with TargetID = the new rescue dispatch's id, and Details
// naming the original dispatch + agent + worktree.
func (c *localClient) CreateRescueDispatch(ctx context.Context, dispatchID int64) (*model.AgentDispatch, error) {
	orig, err := c.store.GetDispatch(dispatchID)
	if err != nil {
		return nil, err
	}
	if orig.Status != model.DispatchPending && orig.Status != model.DispatchDelivered {
		return nil, fmt.Errorf("dispatch #%d is %s; only pending/delivered dispatches are rescuable", orig.ID, orig.Status)
	}
	if isRescueTrivialCreator(orig.CreatedBy) {
		return nil, fmt.Errorf("dispatch #%d was created by %s and is not rescuable (only typed per-mode dispatches can be rescued)", orig.ID, orig.CreatedBy)
	}
	if orig.TargetSessionID == "" {
		return nil, fmt.Errorf("dispatch #%d has no target session; nothing to rescue", orig.ID)
	}
	deadSess, err := c.store.GetAgentSession(orig.TargetSessionID)
	if err != nil {
		return nil, fmt.Errorf("rescue: load dead session %s: %w", orig.TargetSessionID, err)
	}
	if deadSess.EndedAt == nil {
		return nil, fmt.Errorf("rescue: target session %s is still alive; nothing to rescue", deadSess.SessionID)
	}

	repo, err := c.store.GetRepoByID(orig.RepoID)
	if err != nil {
		return nil, fmt.Errorf("rescue: load repo %d: %w", orig.RepoID, err)
	}

	// Best-effort agent id resolution from a linked transcript doc.
	// The dead worker's transcript was likely never attached by the
	// supervisor (the worker died before its summary returned) — but
	// the bacio-transcript-review skill often attaches them post-hoc,
	// and either way the agent id resolves cleanly when present.
	var agentID, transcriptName string
	if orig.IssueID != nil {
		if links, ferr := c.store.ListDocumentsLinkedToIssue(*orig.IssueID); ferr == nil {
			agentID, transcriptName = newestTranscriptAgentID(links)
		}
	}

	target, err := c.pickIdleRescueSupervisor(repo.ID, deadSess.SessionID)
	if err != nil {
		return nil, err
	}
	if target == nil {
		return nil, fmt.Errorf("rescue: no idle supervisor available (need a live, channel-connected, non-busy session in %s; you can also start a fresh `claude` in this repo to receive the rescue)", repo.Prefix)
	}

	worktreePath := ""
	if agentID != "" {
		worktreePath = filepath.Join(repo.Path, ".claude", "worktrees", "agent-"+agentID)
	}

	payload := buildRescueDispatchPayload(orig, agentID, worktreePath, transcriptName, repo.Path)

	d, err := c.store.AddDispatch(store.AddDispatchIn{
		RepoID:          repo.ID,
		TargetAgentID:   target.AgentID,
		TargetSessionID: target.SessionID,
		Payload:         payload,
		CreatedBy:       model.RescueDispatchCreator,
	})
	if err != nil {
		return nil, err
	}
	details := fmt.Sprintf("original_dispatch=%d,target_session=%s,agent=%s,worktree=%s",
		orig.ID, target.SessionID, agentID, worktreePath)
	c.recordOp(model.HistoryEntry{
		RepoID: &repo.ID, RepoPrefix: repo.Prefix,
		Op: "agent.rescue", Kind: "agent",
		TargetID: &d.ID, TargetLabel: dispatchTargetLabel(d),
		Details: details,
	})
	return d, nil
}

// isRescueTrivialCreator reports whether the CreatedBy value names
// one of the structural carve-out creators (setup / ping / rescue).
// Rescue dispatches themselves are excluded so a stale UI click can't
// chain-rescue an in-flight rescue.
func isRescueTrivialCreator(c string) bool {
	switch c {
	case model.SetupDispatchCreator, model.IdlePingDispatchCreator, model.RescueDispatchCreator:
		return true
	}
	return false
}

// newestTranscriptAgentID returns (agentID, filename) parsed from
// the newest bacio transcript document among links — by linkage
// CreatedAt, since that's when the transcript was attached to the
// issue. Returns ("", "") when no link points at a transcript.
func newestTranscriptAgentID(links []*model.DocumentLink) (string, string) {
	var newest *model.DocumentLink
	for _, l := range links {
		if l == nil {
			continue
		}
		if l.DocumentType != model.DocTypeTranscript && !model.IsBacioTranscriptFilename(l.DocumentFilename) {
			continue
		}
		if newest == nil || l.CreatedAt.After(newest.CreatedAt) {
			newest = l
		}
	}
	if newest == nil {
		return "", ""
	}
	return parseAgentIDFromTranscriptFilename(newest.DocumentFilename), newest.DocumentFilename
}

// ParseAgentIDFromTranscriptFilenameForTest exposes the private
// parser to external tests (package client_test). Production code
// MUST NOT depend on this — the canonical caller is
// newestTranscriptAgentID inside this package.
func ParseAgentIDFromTranscriptFilenameForTest(name string) string {
	return parseAgentIDFromTranscriptFilename(name)
}

// parseAgentIDFromTranscriptFilename extracts <id> from the
// attach_transcript naming convention
// `bacio-transcript-<KEY>-agent-<id>.jsonl`. Returns "" when the
// filename doesn't match.
func parseAgentIDFromTranscriptFilename(name string) string {
	name = strings.TrimSuffix(name, ".jsonl")
	i := strings.Index(name, "-agent-")
	if i < 0 {
		return ""
	}
	rest := name[i+len("-agent-"):]
	// Defensive: stop at a path separator if the filename was passed in
	// with a directory prefix.
	if j := strings.IndexAny(rest, "/\\"); j >= 0 {
		rest = rest[:j]
	}
	return rest
}

// pickIdleRescueSupervisor returns the freshest live, channel-
// connected, non-busy, registered session in the repo that is NOT
// the dead session. Returns (nil, nil) when nothing eligible exists.
func (c *localClient) pickIdleRescueSupervisor(repoID int64, excludeSessionID string) (*model.AgentSession, error) {
	sessions, err := c.store.ListAgentSessions(store.AgentSessionFilter{
		RepoID:         &repoID,
		OnlyAlive:      true,
		RegisteredOnly: true,
	})
	if err != nil {
		return nil, err
	}
	openClaims, err := c.store.OpenClaimsBySession(repoID)
	if err != nil {
		return nil, err
	}
	for _, s := range sessions {
		if s == nil || s.SessionID == excludeSessionID {
			continue
		}
		if s.ChannelSeenAt == nil {
			continue
		}
		busy, _ := model.SessionBusy(openClaims[s.ID])
		if busy {
			continue
		}
		return s, nil
	}
	return nil, nil
}

// buildRescueDispatchPayload renders the inline rescue brief the
// supervisor reads from the `<channel from="bacio-rescue">` push.
// Static, freeform text (no template tokens) — the supervisor's
// per-mode brief is NOT involved. The payload tells the supervisor
// to:
//   - handle inline (NOT spawn a Task subagent)
//   - cd into the worktree
//   - read the transcript tail + git diff
//   - classify as finalize or bail (resume deferred in v1)
//   - run close-out via the bare `bacio` on PATH
//   - reply against the rescue dispatch id (read from the <channel>
//     tag's dispatch_id attribute)
//
// agentID and worktreePath may be empty when no transcript was
// attached; the payload then instructs the supervisor to discover
// the worktree via `git worktree list`.
func buildRescueDispatchPayload(orig *model.AgentDispatch, agentID, worktreePath, transcriptName, repoPath string) string {
	var b strings.Builder
	b.WriteString("bacio rescue: a previously dispatched ")
	if orig.Mode != "" {
		b.WriteString(string(orig.Mode))
		b.WriteString(" ")
	}
	b.WriteString("worker died mid-job, leaving its worktree edits unsalvaged. ")
	b.WriteString("Handle this dispatch INLINE — do NOT spawn a per-mode subagent via Task; the work is already partly done and a fresh worker would discard it.\n\n")

	b.WriteString("Context:\n")
	fmt.Fprintf(&b, "  Original dispatch: #%d\n", orig.ID)
	if orig.IssueKey != "" {
		fmt.Fprintf(&b, "  Ticket: %s\n", orig.IssueKey)
	}
	if orig.Mode != "" {
		fmt.Fprintf(&b, "  Mode: %s\n", orig.Mode)
	}
	if agentID != "" {
		fmt.Fprintf(&b, "  Dead agent id: %s\n", agentID)
	} else {
		b.WriteString("  Dead agent id: unknown (no transcript attached) — discover the worktree via `git worktree list` below\n")
	}
	if worktreePath != "" {
		fmt.Fprintf(&b, "  Worktree: %s\n", worktreePath)
	}
	if transcriptName != "" {
		fmt.Fprintf(&b, "  Transcript document: %s (linked to %s)\n", transcriptName, orig.IssueKey)
	}
	fmt.Fprintf(&b, "  Repo: %s\n", repoPath)
	b.WriteString("\n")

	b.WriteString("Steps:\n\n")
	if worktreePath != "" {
		fmt.Fprintf(&b, "1. cd into the worktree:\n   cd %s\n\n", worktreePath)
	} else {
		fmt.Fprintf(&b, "1. Discover the dead worker's worktree, then cd into it:\n"+
			"   git -C %s worktree list   # pick the locked one matching the work\n"+
			"   cd <path>\n\n", repoPath)
	}

	b.WriteString("2. Inspect the worktree:\n")
	b.WriteString("   git status --short\n")
	b.WriteString("   git diff --stat HEAD\n")
	b.WriteString("   git log HEAD~3..HEAD --oneline\n")
	b.WriteString("   git branch --show-current\n\n")

	if agentID != "" {
		b.WriteString("3. Read the last ~80 lines of the dead worker's transcript to understand what it was doing when it died. The raw .jsonl is under\n")
		fmt.Fprintf(&b, "   ~/.claude/projects/*/<parent-session>/subagents/agent-%s.jsonl\n", agentID)
		b.WriteString("   (or `bacio doc show ")
		if transcriptName != "" {
			b.WriteString(transcriptName)
		} else {
			b.WriteString("<transcript-filename>")
		}
		b.WriteString("` for the attached copy).\n\n")
	} else {
		b.WriteString("3. Read the dead worker's transcript if you can locate one (no transcript was attached to this issue, so you may need to skip this step).\n\n")
	}

	b.WriteString("4. Classify the diff:\n\n")
	b.WriteString("   FINALIZE (most common): edits look complete and on-task. Drive the close-out:\n")
	b.WriteString("     - git add -A && git commit -m \"<concise message>\"\n")
	b.WriteString("     - ./build.sh  (rebuild; surface real errors)\n")
	b.WriteString("     - smoke test where applicable (UI changes: bacio web --no-open + playwright-cli)\n")
	b.WriteString("     - gh pr create with a sensible title + body\n")
	if orig.IssueKey != "" {
		fmt.Fprintf(&b, "     - bacio pr attach %s <pr-url>\n", orig.IssueKey)
		switch orig.Mode {
		case "implement":
			fmt.Fprintf(&b, "     - bacio tag add %s implemented\n", orig.IssueKey)
		case "fix_review", "fix-review":
			fmt.Fprintf(&b, "     - bacio tag add %s fix-review\n", orig.IssueKey)
		}
		fmt.Fprintf(&b, "     - bacio issue state %s in_review   (skip if the state is already in_review)\n", orig.IssueKey)
	}
	b.WriteString("\n")

	b.WriteString("   BAIL: edits look incoherent / partial / dangerous, OR you would otherwise want to resume into the existing worktree (resume is not supported in v1):\n")
	b.WriteString("     - mcp__bacio__ask_user_question with issue_id=" + orig.IssueKey + " describing what you saw and asking whether to discard the worktree or pick it up by hand.\n")
	b.WriteString("     - Stop after answering. Do NOT commit or push speculative work.\n\n")

	b.WriteString("5. Reply to THIS rescue dispatch:\n")
	b.WriteString("   mcp__bacio__reply with dispatch_id from the <channel> tag attribute and a short one-line note ('finalised; PR #N' or 'bailed; <reason>').\n\n")

	b.WriteString("Tripwires:\n")
	b.WriteString("  - Use the bare `bacio` on PATH for every close-out call (NOT `.bin/bacio-agent-*`; that workspace binary belongs to its own in-progress implementation and may mismatch the live store schema).\n")
	b.WriteString("  - Don't run `bacio worktree init` here — you're salvaging an existing worktree, not setting up a fresh isolated env.\n")
	b.WriteString("  - Don't claim the ticket — the dead worker's claim was already released. Just commit, PR, tag, reply.\n")
	return b.String()
}

// dispatchDetails builds the audit-log Details string for a dispatch op.
func dispatchDetails(d *model.AgentDispatch) string {
	var parts []string
	if d.IssueKey != "" {
		parts = append(parts, "issue="+d.IssueKey)
	}
	if d.TargetSessionID != "" {
		parts = append(parts, "session="+d.TargetSessionID)
	}
	parts = append(parts, "status="+string(d.Status))
	return joinCSV(parts)
}
