// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * StatusDTO is the wire shape both the desktop ("leaderStatus" Wails
 * event + LeaderService.GetLeaderStatus) and the api (GET /leader)
 * expose. Single source of truth for the JSON tags; the two host-side
 * files re-export this as a type alias so their Wails / JSON bindings
 * stay stable.
 */
export class StatusDTO {
    /**
     * AmLeader is true when the local process holds the UI leader lease.
     */
    "amLeader": boolean;

    /**
     * HolderLabel is the human-readable label of the process that currently
     * holds the lease — useful for "Standby — {HolderLabel} has control".
     * Empty when AmLeader is true or the lease has never been acquired.
     */
    "holderLabel": string;

    /** Creates a new StatusDTO instance. */
    constructor($$source: Partial<StatusDTO> = {}) {
        if (!("amLeader" in $$source)) {
            this["amLeader"] = false;
        }
        if (!("holderLabel" in $$source)) {
            this["holderLabel"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatusDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): StatusDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StatusDTO($$parsedSource as Partial<StatusDTO>);
    }
}
