// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BoardService is the Wails-bound API the kanban frontend talks to. It
 * wraps a local bacio client.Client and reshapes its results into the
 * DTOs the imported UI kit expects. Mostly read-only; the mutations are
 * DispatchIssue (queuing a dispatch for an agent), UpdateIssueDescription,
 * and AddComment (both driven from the issue-drawer Edit modal).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agentcards$0 from "../internal/agentcards/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as boardcards$0 from "../internal/boardcards/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../internal/model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddComment appends a comment to an issue and returns the refreshed
 * issue-drawer payload. An empty author falls back to the OS username,
 * the same default the CLI uses for human actors. repoPrefix may be empty
 * or "all" — the prefix is then derived from the canonical issue key.
 * 
 * `eval` (BACI-131) flags the row as a quality-review note posted from
 * the kanban quick-eval composer — the server pins the in-flight
 * (agent_session_id, dispatch_id, mode) snapshot onto the comment at
 * write time. `transcriptEventRef` (BACI-141) is the optional per-event
 * anchor set by the transcript viewer's per-event composer
 * (`tool_use_id:<id>` or `line_index:<n>`); empty leaves the comment
 * unanchored, rendered pinned to the dispatch prompt card at the top of
 * the transcript view.
 */
export function AddComment(repoPrefix: string, key: string, author: string, body: string, isEval: boolean, transcriptEventRef: string): $CancellablePromise<$models.IssueDetail> {
    return $Call.ByID(1143577105, repoPrefix, key, author, body, isEval, transcriptEventRef).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AddIssue creates a new issue in the named repo and returns the
 * freshly-shaped BoardCard so the React composer can prepend it to the
 * kanban + open IssueWorkspace on the new key. Mirrors DispatchIssue's
 * shape line-for-line: required repo prefix in hand (the "all"
 * cross-repo pseudo-board has no concept of "which repo do I create
 * in", so the caller must pass a real prefix), one client.CreateIssue
 * call, then a single-row Assemble round-trip so the new card carries
 * the same feature-emoji / waiting / blocker shape as the rest of the
 * kanban. Validation (empty title, control chars, etc.) lives at the
 * store boundary inside client.CreateIssue.
 * featureSlug (Phase 4) optionally associates the new issue with a
 * feature at creation time. Empty defers to the repo default feature
 * (store.ResolveCreateIssueFeatureID) — features are mandatory, so the
 * composer always supplies one, but an empty string stays valid.
 * autoRun (BACI-374) arms the new card to run the full
 * Scope → Plan → Implement → Ship chain under the engine; the composer
 * switch defaults it on, and the returned card comes back in the
 * Pipeline column rather than Backlog.
 */
export function AddIssue(repoPrefix: string, title: string, description: string, featureSlug: string, autoRun: boolean): $CancellablePromise<$models.BoardCard> {
    return $Call.ByID(2590773623, repoPrefix, title, description, featureSlug, autoRun).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * AddRepository opens a native folder picker and registers the chosen git
 * working tree as a bacio repo, returning it as a Board. A Board with an empty
 * Prefix means the user cancelled the dialog. The picked folder may sit
 * anywhere inside the repo — git.Detect walks up to the working-tree root.
 */
export function AddRepository(): $CancellablePromise<$models.Board> {
    return $Call.ByID(2129265032).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * AnswerSessionQuestion submits the user's answer. answers is keyed
 * by question text; values are either string (single-select) or
 * []string (multi-select). The store re-validates against the
 * stored payload at the boundary.
 */
export function AnswerSessionQuestion(id: number, answers: { [_ in string]?: any }): $CancellablePromise<model$0.SessionQuestion | null> {
    return $Call.ByID(3587423249, id, answers).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ArchiveIssue (BACI-68) is the per-card "archive" Wails binding —
 * stamps archived_at, returns the updated row. The desktop card menu
 * calls this when the user selects Archive. The kanban refreshes via
 * the regular ListCards path; archived cards stay visible only when
 * display.show_archived is on (and then render visibly-muted).
 */
export function ArchiveIssue(repoPrefix: string, issueKey: string): $CancellablePromise<model$0.Issue | null> {
    return $Call.ByID(543071120, repoPrefix, issueKey).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * AttachPullRequest attaches a pull-request URL to an issue and returns
 * the resolved PRDTO. Validation (http/https + host) lives in the
 * store layer; an invalid URL surfaces as the original error message
 * for the IssueWorkspace's PR-attach form to display.
 */
export function AttachPullRequest(repoPrefix: string, key: string, url: string): $CancellablePromise<$models.PRDTO> {
    return $Call.ByID(1860090468, repoPrefix, key, url).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * CancelSessionQuestion dismisses an open question — the agent
 * receives a tool error on the next channel poll tick.
 */
export function CancelSessionQuestion(id: number): $CancellablePromise<model$0.SessionQuestion | null> {
    return $Call.ByID(1557142517, id).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * CancelWaitingDispatch (BACI-51) is the spinner-as-cancel-button
 * binding. Resolves the active (queued / pending / delivered) dispatch
 * for an issue and cancels it in a single Wails call so card DTOs
 * don't have to carry the dispatch id. A no-active-dispatch issue is
 * not an error — the spinner may have cleared between the click and
 * the call landing — the cancel is a no-op and returns nil.
 * 
 * BACI-130: cancel-after-delivery is now rejected at the store
 * boundary. The desktop card hides the cancel affordance via the
 * new BoardCard.WaitingDispatchDelivered field, but a stale render
 * can still send the click in — swallow the recognisable error
 * fragment the same way the 404 race-clear path returns nil.
 */
export function CancelWaitingDispatch(repoPrefix: string, issueKey: string): $CancellablePromise<void> {
    return $Call.ByID(2200863224, repoPrefix, issueKey);
}

/**
 * ClearDefaultFeature (BACI-235) clears the per-repo default_feature
 * setting. Returns a zero-valued DTO so the caller can re-render
 * without a separate read.
 */
export function ClearDefaultFeature(repoPrefix: string): $CancellablePromise<$models.DefaultFeatureDTO> {
    return $Call.ByID(3288349059, repoPrefix).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * CountShipped (BACI-221) returns the total number of shipped issues
 * under the active Today / Last Week / Forever scope — for one repo, or
 * across every repo when repoPrefix is empty or "all" (BACI-371).
 * Polled on the same 10s cadence as the other live read endpoints so
 * the Shipped pill reflects the current scope even
 * when the popover isn't open. sinceDays==0 means "Forever" (no lower
 * bound on terminal_at); sinceTs (BACI-312) is the absolute
 * local-midnight "Today" cutoff and wins over sinceDays when non-empty.
 */
export function CountShipped(repoPrefix: string, sinceDays: number, sinceTs: string): $CancellablePromise<number> {
    return $Call.ByID(1177825803, repoPrefix, sinceDays, sinceTs);
}

/**
 * CountUnreadNotifications (BACI-287) returns the cross-repo unread badge
 * count the bell polls.
 */
export function CountUnreadNotifications(): $CancellablePromise<number> {
    return $Call.ByID(438446293);
}

/**
 * CreateRelation wires a `blocks` edge so `blocked` ends up blocked by
 * `blocker` — the Pipeline drag-to-block gesture (BACI-342). A `blocks`
 * edge is stored from = blocker, to = blocked, so the drop target (the
 * blocker) is `blocker` and the dragged card (which becomes blocked) is
 * `blocked`. type is hard-coded to "blocks"; the gesture only creates
 * blocks/blocked-by. The store's INSERT OR IGNORE makes a duplicate edge
 * a silent no-op, and the React caller guards a self-drop, so neither
 * reaches this method as an error in normal use. The repo is resolved
 * from the blocker key (both cards share the active board's repo).
 */
export function CreateRelation(repoPrefix: string, blocker: string, blocked: string): $CancellablePromise<void> {
    return $Call.ByID(2970530249, repoPrefix, blocker, blocked);
}

/**
 * DeleteComment removes a comment from an issue and returns the
 * refreshed issue-drawer payload. The comment is addressed by its
 * immutable uuid. repoPrefix may be empty or "all" — the prefix is then
 * derived from the canonical issue key.
 */
export function DeleteComment(repoPrefix: string, key: string, commentUUID: string): $CancellablePromise<$models.IssueDetail> {
    return $Call.ByID(475927367, repoPrefix, key, commentUUID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DispatchIssue queues a dispatch against an issue for a given job stage
 * (mode). The state-gate check and the free-agent auto-pick both live
 * on client.Client.AutoDispatchIssue (BACI-40), so the per-card button,
 * the REST route, and the CLI's target-less `bacio agent dispatch`
 * share the same picker + gate. repoPrefix may be empty or "all" — the
 * prefix is then derived from the canonical issue key.
 */
export function DispatchIssue(repoPrefix: string, issueKey: string, mode: string): $CancellablePromise<$models.DispatchDTO> {
    return $Call.ByID(715303058, repoPrefix, issueKey, mode).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * EditCardProcessTail edits the pending tail of an in_pipeline card's job
 * chain (BACI-294): the completed / running / cancelled jobs stay as a
 * locked prefix; stages is the re-ordered pending tail that replaces the
 * card's pending jobs, re-sequenced after the prefix.
 */
export function EditCardProcessTail(repoPrefix: string, key: string, stages: string[]): $CancellablePromise<(model$0.PipelineJob | null)[]> {
    return $Call.ByID(3819875786, repoPrefix, key, stages).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * GetAutoShip reads the per-repo Shipping-column auto-ship toggle so the
 * Pipeline's Shipping switch seeds from the DB (the value the
 * controller's auto-ship ticker acts on), not a local cache.
 */
export function GetAutoShip(repoPrefix: string): $CancellablePromise<boolean> {
    return $Call.ByID(2288322126, repoPrefix);
}

/**
 * GetBacklogCollapsed (BACI-288) reads the per-repo Pipeline
 * Backlog-column collapse preference so the Pipeline page seeds its rail
 * state from the persisted KV, not a local cache.
 */
export function GetBacklogCollapsed(repoPrefix: string): $CancellablePromise<boolean> {
    return $Call.ByID(396104259, repoPrefix);
}

/**
 * GetBoardHiddenStates (BACI-248) returns the per-repo set of
 * kanban-column states hidden on this machine. Threaded through the
 * client so the Wails binding and the HTTP API stay in lockstep on
 * the audit ledger and the canonical state-name validation.
 */
export function GetBoardHiddenStates(repoPrefix: string): $CancellablePromise<$models.BoardHiddenStatesDTO> {
    return $Call.ByID(3854215019, repoPrefix).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * GetDefaultFeature (BACI-235) returns the per-repo default_feature
 * setting for repoPrefix. Empty Slug = unset (the legacy default).
 */
export function GetDefaultFeature(repoPrefix: string): $CancellablePromise<$models.DefaultFeatureDTO> {
    return $Call.ByID(3752670238, repoPrefix).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetImpactPrimary (BACI-349) reads the per-repo Pipeline impact-primary
 * display preference so the Pipeline page seeds its toggle state from the
 * persisted KV, not a local cache.
 */
export function GetImpactPrimary(repoPrefix: string): $CancellablePromise<boolean> {
    return $Call.ByID(3781828001, repoPrefix);
}

/**
 * GetIssue returns the full issue-drawer payload for one issue. repoPrefix
 * may be empty or "all" — canonical issue keys (PREFIX-N) resolve without a
 * repo context.
 */
export function GetIssue(repoPrefix: string, key: string): $CancellablePromise<$models.IssueDetail> {
    return $Call.ByID(624409110, repoPrefix, key).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetIssueBrief returns the workspace-shaped bulk payload for one
 * issue — issue meta + feature reference + relations (both directions)
 * + linked documents with body content (deduped between issue-link
 * and feature-link sources) + pull requests + comments + claimants +
 * derived taken / waitingForClaim flags. Backs the IssueWorkspace
 * top-level view; replaces the drawer's GetIssue payload for that
 * surface but doesn't retire GetIssue (the older payload still backs
 * callers like the IssueDrawer until BACI-54's deletion step). The
 * repo prefix may be empty or "all" — canonical issue keys (PREFIX-N)
 * resolve without one.
 */
export function GetIssueBrief(repoPrefix: string, key: string): $CancellablePromise<$models.IssueBriefDTO> {
    return $Call.ByID(836296342, repoPrefix, key).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * GetNotification (BACI-287) fetches one notification by id.
 */
export function GetNotification(id: number): $CancellablePromise<model$0.Notification | null> {
    return $Call.ByID(2425668760, id).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * GetSessionQuestion fetches one BACI-53 ask_user_question row by id.
 * Backs the desktop Agents-view modal — the AgentCard composite ships
 * only the badge metadata, so the modal does one extra round trip
 * when the user opens it to fetch the full payload + any existing
 * answer.
 */
export function GetSessionQuestion(id: number): $CancellablePromise<model$0.SessionQuestion | null> {
    return $Call.ByID(445804441, id).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * LaunchRepo returns the prefix of the repo the app was launched from,
 * or "" when there wasn't one. The React tree uses it as the
 * highest-priority default when the URL carries no repo prefix
 * (BACI-368) — the desktop half of the web's GET /launch-repo.
 * 
 * The error return is vestigial (there is nothing to fail) but keeps
 * the generated binding a rejectable promise like its siblings.
 */
export function LaunchRepo(): $CancellablePromise<string> {
    return $Call.ByID(868537162);
}

/**
 * ListAgents returns the agent sessions for one repo (or every repo when
 * repoPrefix is empty or "all"), each carrying its status, open claims,
 * and the dispatches aimed at it. SessionStart stubs that never
 * completed register are hidden — they're noise in the supervision UI.
 * 
 * The assembly logic lives in internal/agentcards (BACI-50) so the
 * bacio api can serve the same payload to a browser. This wrapper just
 * resolves the repo and delegates.
 */
export function ListAgents(repoPrefix: string): $CancellablePromise<$models.AgentCard[]> {
    return $Call.ByID(3979848123, repoPrefix).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * ListBoards returns every bacio repo as a sidebar board, with its issue count
 * and its BACI-89 background-sync status.
 */
export function ListBoards(): $CancellablePromise<$models.Board[]> {
    return $Call.ByID(3235630628).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * ListCards returns issues as kanban cards — for one repo, or across every
 * repo when repoPrefix is empty or "all". Delegates to boardcards.Assemble
 * so the desktop and REST surface share one assembler.
 * 
 * Archived cards (BACI-68) follow the display.show_archived global
 * setting — when on, archived rows surface as visibly-muted cards;
 * when off (the default) they're hidden from the board entirely. The
 * desktop has no per-call --include-archived knob — toggle the setting
 * from the Settings panel.
 */
export function ListCards(repoPrefix: string): $CancellablePromise<$models.BoardCard[]> {
    return $Call.ByID(4181487648, repoPrefix).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * ListColumns returns the kanban columns — the legacy state-board
 * columns, excluding the Pipeline states (those cards live on the
 * Pipeline page).
 */
export function ListColumns(): $CancellablePromise<$models.BoardColumn[]> {
    return $Call.ByID(2117984856).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * ListNotifications (BACI-287) returns the global (cross-repo) agent→user
 * notification list, newest-first — the notification bell's dropdown.
 * unreadOnly drops read rows (the bell's default); pass false for the
 * "show all" filter. limit <= 0 falls back to the store default cap.
 */
export function ListNotifications(unreadOnly: boolean, limit: number): $CancellablePromise<(model$0.Notification | null)[]> {
    return $Call.ByID(648588779, unreadOnly, limit).then(($result: any) => {
        return $$createType23($result);
    });
}

/**
 * ListRepoActivity returns the per-repo activity summary the topbar's
 * repository picker ranks itself by (BACI-369). One row per repo,
 * including repos with nothing happening — the picker needs every repo
 * in its ordering input.
 */
export function ListRepoActivity(): $CancellablePromise<$models.RepoActivity[]> {
    return $Call.ByID(2158820232).then(($result: any) => {
        return $$createType25($result);
    });
}

/**
 * ListShipped (BACI-187, reshaped for BACI-221) returns the
 * recently-shipped issues (newest-first) wrapped with the
 * total count under the same scope. sinceDays clamps the relative window
 * (0 = no lower bound — "Forever"); sinceTs (BACI-312) is the absolute
 * local-midnight "Today" cutoff and wins over sinceDays when non-empty;
 * limit caps the row count (0 = the popover's default 20, max 100).
 * Sibling of ListCards in shape, repo resolution included — one repo, or
 * every repo when repoPrefix is empty or "all" (BACI-371, the popover's
 * default scope).
 */
export function ListShipped(repoPrefix: string, sinceDays: number, sinceTs: string, limit: number): $CancellablePromise<$models.ShippedListDTO> {
    return $Call.ByID(3138957880, repoPrefix, sinceDays, sinceTs, limit).then(($result: any) => {
        return $$createType26($result);
    });
}

/**
 * MarkAllNotificationsRead (BACI-287) marks every unread row read,
 * cross-repo — the bell's "mark all read" footer. Returns the count flipped.
 */
export function MarkAllNotificationsRead(): $CancellablePromise<number> {
    return $Call.ByID(916348189);
}

/**
 * MarkCardDone is the in_pipeline → done hand-off (BACI-352): close a card
 * out as done directly, bypassing the Shipping column and the ship agent.
 * The direct-done counterpart to ShipCard.
 */
export function MarkCardDone(repoPrefix: string, key: string): $CancellablePromise<$models.BoardCard> {
    return $Call.ByID(3684593014, repoPrefix, key).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * MarkNotificationRead (BACI-287) stamps read_at on one notification —
 * the bell's per-row "mark read". Idempotent.
 */
export function MarkNotificationRead(id: number): $CancellablePromise<model$0.Notification | null> {
    return $Call.ByID(3369062611, id).then(($result: any) => {
        return $$createType16($result);
    });
}

export function ReorderCard(repoPrefix: string, key: string, position: number): $CancellablePromise<$models.BoardCard> {
    return $Call.ByID(4119956470, repoPrefix, key, position).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * RerunCardJob re-runs an aborted (cancelled) job at the given 1-based
 * sequence — the BACI-291 per-job Re-run control. Returns the refreshed
 * chain.
 */
export function RerunCardJob(repoPrefix: string, key: string, seq: number): $CancellablePromise<(model$0.PipelineJob | null)[]> {
    return $Call.ByID(1469568566, repoPrefix, key, seq).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * RescueDispatch (BACI-190) posts a `from="bacio-rescue"` channel
 * event to an idle supervisor session, asking it to handle a dead
 * worker's stranded worktree INLINE. Eligibility (status pending /
 * delivered, real per-mode creator, target session ended, idle
 * supervisor available) is enforced by client.CreateRescueDispatch
 * — the binding just shapes the response. Returns an error string
 * the frontend can surface in a toast when the rescue can't be
 * queued (e.g. no idle supervisor in the repo).
 */
export function RescueDispatch(dispatchID: number): $CancellablePromise<$models.DispatchDTO> {
    return $Call.ByID(233478750, dispatchID).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * ResetCardProcess wipes an in_pipeline card's ENTIRE job chain (BACI-314)
 * so it drops back to the from-scratch "Pick a process" picker. The UI
 * never dry-runs, so dryRun is always false. Refused by the engine while a
 * job is running (the UI hides Reset in that state; the client surfaces the
 * error otherwise). Returns the refreshed (empty) chain.
 */
export function ResetCardProcess(repoPrefix: string, key: string): $CancellablePromise<(model$0.PipelineJob | null)[]> {
    return $Call.ByID(2278414531, repoPrefix, key).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * SendSessionMessage (BACI-286) enqueues a user→agent steer message at a
 * busy session — the Pipeline running-job card / Agents-page session
 * card "message" button. The channel serving that session pushes it as a
 * `<channel kind="message">` tag at the worker's next turn boundary.
 * NOT a dispatch — no matcher, no ack lifecycle. An unknown session id
 * or empty/over-cap body surfaces as an error the frontend toasts.
 */
export function SendSessionMessage(sessionID: string, body: string): $CancellablePromise<model$0.UserMessage | null> {
    return $Call.ByID(23283136, sessionID, body).then(($result: any) => {
        return $$createType28($result);
    });
}

export function SetAutoShip(repoPrefix: string, enabled: boolean): $CancellablePromise<boolean> {
    return $Call.ByID(1219303746, repoPrefix, enabled);
}

/**
 * SetBacklogCollapsed (BACI-288) persists the per-repo Pipeline
 * Backlog-column collapse preference and returns the resulting value.
 */
export function SetBacklogCollapsed(repoPrefix: string, collapsed: boolean): $CancellablePromise<boolean> {
    return $Call.ByID(1820060943, repoPrefix, collapsed);
}

/**
 * SetBoardHiddenStates (BACI-248) replaces the per-repo
 * board-hidden-states set with `states`. Replace-not-merge: the array
 * is the full new set. Unknown state names are silently dropped at the
 * store boundary so a future state rename doesn't break old saved
 * settings. Records a `repo_setting.update` audit row when the set
 * actually changes (idempotent no-op writes skip the audit).
 */
export function SetBoardHiddenStates(repoPrefix: string, states: string[]): $CancellablePromise<$models.BoardHiddenStatesDTO> {
    return $Call.ByID(1989240775, repoPrefix, states).then(($result: any) => {
        return $$createType13($result);
    });
}

export function SetCardEngineMode(repoPrefix: string, key: string, mode: string): $CancellablePromise<$models.BoardCard> {
    return $Call.ByID(3389668292, repoPrefix, key, mode).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SetCardProcess materialises a card's job chain from either a preset
 * slug (process) or an explicit ordered stage list (stages) — mutually
 * exclusive. The cumulative-stepper picker sends stages; the kept
 * skip-Plan preset buttons send a slug.
 */
export function SetCardProcess(repoPrefix: string, key: string, process: string, stages: string[]): $CancellablePromise<(model$0.PipelineJob | null)[]> {
    return $Call.ByID(3410649082, repoPrefix, key, process, stages).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * SetDefaultFeature (BACI-235) writes the per-repo default_feature
 * setting. slug must reference an existing feature in the same repo;
 * the client records the audit row.
 */
export function SetDefaultFeature(repoPrefix: string, slug: string): $CancellablePromise<$models.DefaultFeatureDTO> {
    return $Call.ByID(2719883970, repoPrefix, slug).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * SetImpactPrimary (BACI-349) persists the per-repo Pipeline
 * impact-primary display preference and returns the resulting value.
 */
export function SetImpactPrimary(repoPrefix: string, impactPrimary: boolean): $CancellablePromise<boolean> {
    return $Call.ByID(479770125, repoPrefix, impactPrimary);
}

/**
 * SetIssueState changes an issue's state and returns the refreshed card.
 * It backs the board's drag-to-move: dropping a card in a new column
 * persists the state change so it survives the next auto-refresh poll.
 * repoPrefix may be empty or "all" — the prefix is then derived from the
 * canonical issue key.
 */
export function SetIssueState(repoPrefix: string, key: string, state: string): $CancellablePromise<$models.BoardCard> {
    return $Call.ByID(2874048639, repoPrefix, key, state).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ShipCard(repoPrefix: string, key: string): $CancellablePromise<$models.BoardCard> {
    return $Call.ByID(3461643849, repoPrefix, key).then(($result: any) => {
        return $$createType1($result);
    });
}

export function StartCardJob(repoPrefix: string, key: string): $CancellablePromise<(model$0.PipelineJob | null)[]> {
    return $Call.ByID(2998495872, repoPrefix, key).then(($result: any) => {
        return $$createType12($result);
    });
}

export function StopCardJob(repoPrefix: string, key: string): $CancellablePromise<(model$0.PipelineJob | null)[]> {
    return $Call.ByID(39478934, repoPrefix, key).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * UnarchiveIssue (BACI-68) clears archived_at.
 */
export function UnarchiveIssue(repoPrefix: string, issueKey: string): $CancellablePromise<model$0.Issue | null> {
    return $Call.ByID(3350533803, repoPrefix, issueKey).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * UpdateIssueCustomerImpact (BACI-349) replaces an issue's one-line
 * customer impact and returns the refreshed issue-drawer payload. Unlike
 * the title, an empty value is legitimate — it clears the field back to
 * the "no impact" state — so the value is always sent as a non-nil
 * pointer (empty = clear). repoPrefix may be empty or "all" — the prefix
 * is then derived from the canonical issue key.
 */
export function UpdateIssueCustomerImpact(repoPrefix: string, key: string, customerImpact: string): $CancellablePromise<$models.IssueDetail> {
    return $Call.ByID(2666824201, repoPrefix, key, customerImpact).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * UpdateIssueDescription replaces an issue's description and returns the
 * refreshed issue-drawer payload. repoPrefix may be empty or "all" — the
 * prefix is then derived from the canonical issue key.
 */
export function UpdateIssueDescription(repoPrefix: string, key: string, description: string): $CancellablePromise<$models.IssueDetail> {
    return $Call.ByID(2921112347, repoPrefix, key, description).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * UpdateIssueTitle replaces an issue's title and returns the refreshed
 * issue-drawer payload. Mirrors UpdateIssueDescription — the store rejects
 * an empty title (invalid_input) so callers gate the value first.
 * repoPrefix may be empty or "all" — the prefix is then derived from the
 * canonical issue key.
 */
export function UpdateIssueTitle(repoPrefix: string, key: string, title: string): $CancellablePromise<$models.IssueDetail> {
    return $Call.ByID(3596251263, repoPrefix, key, title).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.IssueDetail.createFrom;
const $$createType1 = boardcards$0.BoardCard.createFrom;
const $$createType2 = $models.Board.createFrom;
const $$createType3 = model$0.SessionQuestion.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = model$0.Issue.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $models.PRDTO.createFrom;
const $$createType8 = $models.DefaultFeatureDTO.createFrom;
const $$createType9 = agentcards$0.DispatchDTO.createFrom;
const $$createType10 = model$0.PipelineJob.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $models.BoardHiddenStatesDTO.createFrom;
const $$createType14 = $models.IssueBriefDTO.createFrom;
const $$createType15 = model$0.Notification.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
const $$createType17 = agentcards$0.AgentCard.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = $Create.Array($$createType2);
const $$createType20 = $Create.Array($$createType1);
const $$createType21 = $models.BoardColumn.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = $Create.Array($$createType16);
const $$createType24 = $models.RepoActivity.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = $models.ShippedListDTO.createFrom;
const $$createType27 = model$0.UserMessage.createFrom;
const $$createType28 = $Create.Nullable($$createType27);
