// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BoardService is the Wails-bound read API the kanban frontend talks to. It
 * wraps a local bacio client.Client and reshapes its results into the DTOs
 * the imported UI kit expects. Read-only for now — mutations are a follow-up.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetIssue returns the full issue-drawer payload for one issue. repoPrefix
 * may be empty or "all" — canonical issue keys (PREFIX-N) resolve without a
 * repo context.
 */
export function GetIssue(repoPrefix: string, key: string): $CancellablePromise<$models.IssueDetail> {
    return $Call.ByID(624409110, repoPrefix, key).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListBoards returns every bacio repo as a sidebar board, with its issue count.
 */
export function ListBoards(): $CancellablePromise<$models.Board[]> {
    return $Call.ByID(3235630628).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ListCards returns issues as kanban cards — for one repo, or across every
 * repo when repoPrefix is empty or "all".
 */
export function ListCards(repoPrefix: string): $CancellablePromise<$models.BoardCard[]> {
    return $Call.ByID(4181487648, repoPrefix).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ListColumns returns the kanban columns — bacio's issue states, in order.
 */
export function ListColumns(): $CancellablePromise<$models.BoardColumn[]> {
    return $Call.ByID(2117984856).then(($result: any) => {
        return $$createType6($result);
    });
}

// Private type creation functions
const $$createType0 = $models.IssueDetail.createFrom;
const $$createType1 = $models.Board.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.BoardCard.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.BoardColumn.createFrom;
const $$createType6 = $Create.Array($$createType5);
