// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BoardService is the Wails-bound API the kanban frontend talks to. It
 * wraps a local bacio client.Client and reshapes its results into the
 * DTOs the imported UI kit expects. Mostly read-only; the mutations are
 * DispatchIssue (queuing a dispatch for an agent), UpdateIssueDescription,
 * and AddComment (both driven from the issue-drawer Edit modal).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agentcards$0 from "../internal/agentcards/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as boardcards$0 from "../internal/boardcards/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../internal/model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddComment appends a comment to an issue and returns the refreshed
 * issue-drawer payload. An empty author falls back to the OS username,
 * the same default the CLI uses for human actors. repoPrefix may be empty
 * or "all" — the prefix is then derived from the canonical issue key.
 * 
 * `eval` (BACI-131) flags the row as a quality-review note posted from
 * the kanban quick-eval composer — the server pins the in-flight
 * (agent_session_id, dispatch_id, mode) snapshot onto the comment at
 * write time. `transcriptEventRef` (BACI-141) is the optional per-event
 * anchor set by the transcript viewer's per-event composer
 * (`tool_use_id:<id>` or `line_index:<n>`); empty leaves the comment
 * unanchored, rendered pinned to the dispatch prompt card at the top of
 * the transcript view.
 */
export function AddComment(repoPrefix: string, key: string, author: string, body: string, isEval: boolean, transcriptEventRef: string): $CancellablePromise<$models.IssueDetail> {
    return $Call.ByID(1143577105, repoPrefix, key, author, body, isEval, transcriptEventRef).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AddIssue creates a new issue in the named repo and returns the
 * freshly-shaped BoardCard so the React composer can prepend it to the
 * kanban + open IssueWorkspace on the new key. Mirrors DispatchIssue's
 * shape line-for-line: required repo prefix in hand (the "all"
 * cross-repo pseudo-board has no concept of "which repo do I create
 * in", so the caller must pass a real prefix), one client.CreateIssue
 * call, then a single-row Assemble round-trip so the new card carries
 * the same feature-emoji / waiting / blocker shape as the rest of the
 * kanban. Validation (empty title, control chars, etc.) lives at the
 * store boundary inside client.CreateIssue.
 */
export function AddIssue(repoPrefix: string, title: string, description: string): $CancellablePromise<$models.BoardCard> {
    return $Call.ByID(2590773623, repoPrefix, title, description).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * AddRepository opens a native folder picker and registers the chosen git
 * working tree as a bacio repo, returning it as a Board. A Board with an empty
 * Prefix means the user cancelled the dialog. The picked folder may sit
 * anywhere inside the repo — git.Detect walks up to the working-tree root.
 */
export function AddRepository(): $CancellablePromise<$models.Board> {
    return $Call.ByID(2129265032).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * AnswerSessionQuestion submits the user's answer. answers is keyed
 * by question text; values are either string (single-select) or
 * []string (multi-select). The store re-validates against the
 * stored payload at the boundary.
 */
export function AnswerSessionQuestion(id: number, answers: { [_ in string]?: any }): $CancellablePromise<model$0.SessionQuestion | null> {
    return $Call.ByID(3587423249, id, answers).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ArchiveIssue (BACI-68) is the per-card "archive" Wails binding —
 * stamps archived_at, returns the updated row. The desktop card menu
 * calls this when the user selects Archive. The kanban refreshes via
 * the regular ListCards path; archived cards stay visible only when
 * display.show_archived is on (and then render visibly-muted).
 */
export function ArchiveIssue(repoPrefix: string, issueKey: string): $CancellablePromise<model$0.Issue | null> {
    return $Call.ByID(543071120, repoPrefix, issueKey).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * AttachPullRequest attaches a pull-request URL to an issue and returns
 * the resolved PRDTO. Validation (http/https + host) lives in the
 * store layer; an invalid URL surfaces as the original error message
 * for the IssueWorkspace's PR-attach form to display.
 */
export function AttachPullRequest(repoPrefix: string, key: string, url: string): $CancellablePromise<$models.PRDTO> {
    return $Call.ByID(1860090468, repoPrefix, key, url).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * CancelFollowOnDispatch (BACI-180) is the chip-remove handler: cancel
 * the dormant follow-on attached to an issue. Idempotent — a no-op on
 * an issue with no dormant follow-on (returns the zero DispatchDTO and
 * nil error) so a stale UI click doesn't surface as an error.
 */
export function CancelFollowOnDispatch(repoPrefix: string, issueKey: string): $CancellablePromise<$models.DispatchDTO> {
    return $Call.ByID(1725053965, repoPrefix, issueKey).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * CancelSessionQuestion dismisses an open question — the agent
 * receives a tool error on the next channel poll tick.
 */
export function CancelSessionQuestion(id: number): $CancellablePromise<model$0.SessionQuestion | null> {
    return $Call.ByID(1557142517, id).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * CancelWaitingDispatch (BACI-51) is the spinner-as-cancel-button
 * binding. Resolves the active (queued / pending / delivered) dispatch
 * for an issue and cancels it in a single Wails call so card DTOs
 * don't have to carry the dispatch id. A no-active-dispatch issue is
 * not an error — the spinner may have cleared between the click and
 * the call landing — the cancel is a no-op and returns nil.
 * 
 * BACI-130: cancel-after-delivery is now rejected at the store
 * boundary. The desktop card hides the cancel affordance via the
 * new BoardCard.WaitingDispatchDelivered field, but a stale render
 * can still send the click in — swallow the recognisable error
 * fragment the same way the 404 race-clear path returns nil.
 */
export function CancelWaitingDispatch(repoPrefix: string, issueKey: string): $CancellablePromise<void> {
    return $Call.ByID(2200863224, repoPrefix, issueKey);
}

/**
 * ClearDefaultFeature (BACI-235) clears the per-repo default_feature
 * setting. Returns a zero-valued DTO so the caller can re-render
 * without a separate read.
 */
export function ClearDefaultFeature(repoPrefix: string): $CancellablePromise<$models.DefaultFeatureDTO> {
    return $Call.ByID(3288349059, repoPrefix).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * CountShipped (BACI-221) returns the total number of shipped issues
 * for one repo under the active Today / Last Week / Forever scope.
 * Polled on the same 10s cadence as the other live read endpoints so
 * the topbar pill reflects the current scope even when the popover
 * isn't open. sinceDays==0 means "Forever" (no lower bound on
 * terminal_at).
 */
export function CountShipped(repoPrefix: string, sinceDays: number): $CancellablePromise<number> {
    return $Call.ByID(1177825803, repoPrefix, sinceDays);
}

/**
 * DeleteComment removes a comment from an issue and returns the
 * refreshed issue-drawer payload. The comment is addressed by its
 * immutable uuid. repoPrefix may be empty or "all" — the prefix is then
 * derived from the canonical issue key.
 */
export function DeleteComment(repoPrefix: string, key: string, commentUUID: string): $CancellablePromise<$models.IssueDetail> {
    return $Call.ByID(475927367, repoPrefix, key, commentUUID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DispatchIssue queues a dispatch against an issue for a given job stage
 * (mode). The state-gate check and the free-agent auto-pick both live
 * on client.Client.AutoDispatchIssue (BACI-40), so the per-card button,
 * the REST route, and the CLI's target-less `bacio agent dispatch`
 * share the same picker + gate. repoPrefix may be empty or "all" — the
 * prefix is then derived from the canonical issue key.
 */
export function DispatchIssue(repoPrefix: string, issueKey: string, mode: string): $CancellablePromise<$models.DispatchDTO> {
    return $Call.ByID(715303058, repoPrefix, issueKey, mode).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * DispatchIssueChain (BACI-209) queues a state-gated primary dispatch
 * PLUS a dormant follow-on against the brand-new parent in one
 * transaction. Backs the kanban's "Plan, then Implement" compound
 * picker on todo cards. Mirrors DispatchIssue's shape (returns the
 * parent DispatchDTO; the follow-on rides on the next BoardCard
 * refresh via card.followOn).
 * 
 * All three surfaces — Wails, REST, CLI — funnel through
 * client.AutoDispatchIssueWithFollowOn so the gate + payload + two
 * audit rows live in one place.
 */
export function DispatchIssueChain(repoPrefix: string, issueKey: string, mode: string, followOnMode: string): $CancellablePromise<$models.DispatchDTO> {
    return $Call.ByID(168125999, repoPrefix, issueKey, mode, followOnMode).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetDefaultFeature (BACI-235) returns the per-repo default_feature
 * setting for repoPrefix. Empty Slug = unset (the legacy default).
 */
export function GetDefaultFeature(repoPrefix: string): $CancellablePromise<$models.DefaultFeatureDTO> {
    return $Call.ByID(3752670238, repoPrefix).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GetIssue returns the full issue-drawer payload for one issue. repoPrefix
 * may be empty or "all" — canonical issue keys (PREFIX-N) resolve without a
 * repo context.
 */
export function GetIssue(repoPrefix: string, key: string): $CancellablePromise<$models.IssueDetail> {
    return $Call.ByID(624409110, repoPrefix, key).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetIssueBrief returns the workspace-shaped bulk payload for one
 * issue — issue meta + feature reference + relations (both directions)
 * + linked documents with body content (deduped between issue-link
 * and feature-link sources) + pull requests + comments + claimants +
 * derived taken / waitingForClaim flags. Backs the IssueWorkspace
 * top-level view; replaces the drawer's GetIssue payload for that
 * surface but doesn't retire GetIssue (the older payload still backs
 * callers like the IssueDrawer until BACI-54's deletion step). The
 * repo prefix may be empty or "all" — canonical issue keys (PREFIX-N)
 * resolve without one.
 */
export function GetIssueBrief(repoPrefix: string, key: string): $CancellablePromise<$models.IssueBriefDTO> {
    return $Call.ByID(836296342, repoPrefix, key).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * GetSessionQuestion fetches one BACI-53 ask_user_question row by id.
 * Backs the desktop Agents-view modal — the AgentCard composite ships
 * only the badge metadata, so the modal does one extra round trip
 * when the user opens it to fetch the full payload + any existing
 * answer.
 */
export function GetSessionQuestion(id: number): $CancellablePromise<model$0.SessionQuestion | null> {
    return $Call.ByID(445804441, id).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ListAgents returns the agent sessions for one repo (or every repo when
 * repoPrefix is empty or "all"), each carrying its status, open claims,
 * and the dispatches aimed at it. SessionStart stubs that never
 * completed register are hidden — they're noise in the supervision UI.
 * 
 * The assembly logic lives in internal/agentcards (BACI-50) so the
 * bacio api can serve the same payload to a browser. This wrapper just
 * resolves the repo and delegates.
 */
export function ListAgents(repoPrefix: string): $CancellablePromise<$models.AgentCard[]> {
    return $Call.ByID(3979848123, repoPrefix).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * ListBoards returns every bacio repo as a sidebar board, with its issue count
 * and its BACI-89 background-sync status.
 */
export function ListBoards(): $CancellablePromise<$models.Board[]> {
    return $Call.ByID(3235630628).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * ListCards returns issues as kanban cards — for one repo, or across every
 * repo when repoPrefix is empty or "all". Delegates to boardcards.Assemble
 * so the desktop and REST surface share one assembler.
 * 
 * Archived cards (BACI-68) follow the display.show_archived global
 * setting — when on, archived rows surface as visibly-muted cards;
 * when off (the default) they're hidden from the board entirely. The
 * desktop has no per-call --include-archived knob — toggle the setting
 * from the Settings panel.
 */
export function ListCards(repoPrefix: string): $CancellablePromise<$models.BoardCard[]> {
    return $Call.ByID(4181487648, repoPrefix).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * ListColumns returns the kanban columns — bacio's issue states, in order.
 */
export function ListColumns(): $CancellablePromise<$models.BoardColumn[]> {
    return $Call.ByID(2117984856).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * ListShipped (BACI-187, reshaped for BACI-221) returns the
 * recently-shipped issues for one repo (newest-first) wrapped with the
 * total count under the same scope. sinceDays clamps the window
 * (0 = no lower bound — "Forever"); limit caps the row count
 * (0 = the popover's default 20, max 100). Sibling of ListCards in
 * shape — one repo, one trip, lean rows the popover renders without
 * follow-up fetches.
 */
export function ListShipped(repoPrefix: string, sinceDays: number, limit: number): $CancellablePromise<$models.ShippedListDTO> {
    return $Call.ByID(3138957880, repoPrefix, sinceDays, limit).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * ListStateGraph returns the BACI-241 canonical state-transition graph —
 * the categorised edge table that surfaces (the kanban follow-on popup
 * today, board-card menus and the dispatch composer later) read to
 * promote / demote / tuck-away modes whose allowedStates overlap with
 * the card's primary / secondary / unusual next-states. The graph is a
 * Go constant; this call is a thin marshaller mirroring the REST
 * /settings/state-graph endpoint.
 */
export function ListStateGraph(): $CancellablePromise<$models.StateGraphDTO> {
    return $Call.ByID(2937613722).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * QueueFollowOnDispatch (BACI-180) attaches a dormant follow-on
 * dispatch to the issue's in-flight (parent) dispatch. Mirrors
 * DispatchIssue's shape — same DTO out, repo prefix derivable from
 * the issue key — but routes through client.QueueFollowOnDispatch so
 * the gate + parent-resolution path stays in one place. Errors when
 * there is no open dispatch on the issue, when the state-gate
 * rejects, or when a dormant follow-on already exists (single-slot
 * per issue).
 */
export function QueueFollowOnDispatch(repoPrefix: string, issueKey: string, mode: string): $CancellablePromise<$models.DispatchDTO> {
    return $Call.ByID(1591721554, repoPrefix, issueKey, mode).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * RescueDispatch (BACI-190) posts a `from="bacio-rescue"` channel
 * event to an idle supervisor session, asking it to handle a dead
 * worker's stranded worktree INLINE. Eligibility (status pending /
 * delivered, real per-mode creator, target session ended, idle
 * supervisor available) is enforced by client.CreateRescueDispatch
 * — the binding just shapes the response. Returns an error string
 * the frontend can surface in a toast when the rescue can't be
 * queued (e.g. no idle supervisor in the repo).
 */
export function RescueDispatch(dispatchID: number): $CancellablePromise<$models.DispatchDTO> {
    return $Call.ByID(233478750, dispatchID).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * SetDefaultFeature (BACI-235) writes the per-repo default_feature
 * setting. slug must reference an existing feature in the same repo;
 * the client records the audit row.
 */
export function SetDefaultFeature(repoPrefix: string, slug: string): $CancellablePromise<$models.DefaultFeatureDTO> {
    return $Call.ByID(2719883970, repoPrefix, slug).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * SetIssueState changes an issue's state and returns the refreshed card.
 * It backs the board's drag-to-move: dropping a card in a new column
 * persists the state change so it survives the next auto-refresh poll.
 * repoPrefix may be empty or "all" — the prefix is then derived from the
 * canonical issue key.
 */
export function SetIssueState(repoPrefix: string, key: string, state: string): $CancellablePromise<$models.BoardCard> {
    return $Call.ByID(2874048639, repoPrefix, key, state).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UnarchiveIssue (BACI-68) clears archived_at.
 */
export function UnarchiveIssue(repoPrefix: string, issueKey: string): $CancellablePromise<model$0.Issue | null> {
    return $Call.ByID(3350533803, repoPrefix, issueKey).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * UpdateIssueDescription replaces an issue's description and returns the
 * refreshed issue-drawer payload. repoPrefix may be empty or "all" — the
 * prefix is then derived from the canonical issue key.
 */
export function UpdateIssueDescription(repoPrefix: string, key: string, description: string): $CancellablePromise<$models.IssueDetail> {
    return $Call.ByID(2921112347, repoPrefix, key, description).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.IssueDetail.createFrom;
const $$createType1 = boardcards$0.BoardCard.createFrom;
const $$createType2 = $models.Board.createFrom;
const $$createType3 = model$0.SessionQuestion.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = model$0.Issue.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $models.PRDTO.createFrom;
const $$createType8 = agentcards$0.DispatchDTO.createFrom;
const $$createType9 = $models.DefaultFeatureDTO.createFrom;
const $$createType10 = $models.IssueBriefDTO.createFrom;
const $$createType11 = agentcards$0.AgentCard.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $Create.Array($$createType2);
const $$createType14 = $Create.Array($$createType1);
const $$createType15 = $models.BoardColumn.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = $models.ShippedListDTO.createFrom;
const $$createType18 = $models.StateGraphDTO.createFrom;
