// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DocService is the Wails-bound document API the desktop frontend talks to.
 * It wraps a local bacio client.Client and reshapes its results into the DTOs
 * the editor UI expects. Documents are per-repo: every method needs a
 * concrete repo prefix (the "all repositories" pseudo-board has no document
 * scope).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetDoc returns one document with its markdown content for editing.
 */
export function GetDoc(repoPrefix: string, filename: string): $CancellablePromise<$models.DocContent> {
    return $Call.ByID(245181325, repoPrefix, filename).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListDocs returns every document in one repo as a summary row. typeFilter is
 * a document-type string ("architecture", "designs", …) or "" for all types.
 */
export function ListDocs(repoPrefix: string, typeFilter: string): $CancellablePromise<$models.DocSummary[]> {
    return $Call.ByID(2525044932, repoPrefix, typeFilter).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SaveDoc persists new markdown content for an existing document and returns
 * the refreshed document. The underlying client records an audit entry.
 */
export function SaveDoc(repoPrefix: string, filename: string, content: string): $CancellablePromise<$models.DocContent> {
    return $Call.ByID(2796954592, repoPrefix, filename, content).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.DocContent.createFrom;
const $$createType1 = $models.DocSummary.createFrom;
const $$createType2 = $Create.Array($$createType1);
