// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FeatureService is the Wails-bound feature API the desktop frontend talks to.
 * It wraps a local bacio client.Client and reshapes its results into the DTOs
 * the Features view expects. Read-only: features are created and edited via
 * the CLI. Features are per-repo, so every method needs a concrete repo
 * prefix (the "all repositories" pseudo-board has no feature scope).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddFeatureComment posts a chronological handoff comment to a feature
 * (BACI-124) and returns the refreshed detail.
 */
export function AddFeatureComment(repoPrefix: string, slug: string, author: string, body: string): $CancellablePromise<$models.FeatureDetail> {
    return $Call.ByID(517388757, repoPrefix, slug, author, body).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DeleteFeatureComment removes a feature comment by uuid (BACI-124) and
 * returns the refreshed detail.
 */
export function DeleteFeatureComment(repoPrefix: string, slug: string, commentUUID: string): $CancellablePromise<$models.FeatureDetail> {
    return $Call.ByID(1504383339, repoPrefix, slug, commentUUID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetFeature returns one feature with its description and the issues grouped
 * under it, for the detail pane.
 */
export function GetFeature(repoPrefix: string, slug: string): $CancellablePromise<$models.FeatureDetail> {
    return $Call.ByID(3103647661, repoPrefix, slug).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetFeaturePlan (BACI-236) returns the dependency-graph payload for
 * the FeaturesView. includeClosed=false matches the historical open-
 * only `bacio feature plan` shape; true widens to every issue in the
 * feature plus every `blocks` edge whose endpoints are both in the
 * feature, with Closed=true on terminal entries.
 */
export function GetFeaturePlan(repoPrefix: string, slug: string, includeClosed: boolean): $CancellablePromise<$models.FeaturePlan> {
    return $Call.ByID(461398074, repoPrefix, slug, includeClosed).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListFeatures returns every feature in one repo as a summary row.
 * Archived features (BACI-68) follow display.show_archived.
 */
export function ListFeatures(repoPrefix: string): $CancellablePromise<$models.FeatureSummary[]> {
    return $Call.ByID(640296380, repoPrefix).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * SetFeatureAutoClose (BACI-250) flips the per-feature auto-close
 * toggle — the sticky-bit `state_manual` column that gates the
 * BACI-199 archive-sweep's auto-completion pass — and returns the
 * refreshed FeatureDetail. enabled=true clears the bit (the sweep may
 * promote this feature once every child is terminal); enabled=false
 * sets the bit (long-lived catch-alls stay `active` indefinitely).
 * Idempotent — flipping to the same state is a no-op write. Mirrors
 * SetHiddenOnBoard's shape.
 */
export function SetFeatureAutoClose(repoPrefix: string, slug: string, enabled: boolean): $CancellablePromise<$models.FeatureDetail> {
    return $Call.ByID(4056697990, repoPrefix, slug, enabled).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetFeatureBranchName (BACI-231) updates the per-feature integration
 * branch and returns the refreshed FeatureDetail. Empty string clears
 * the branch (the feature ships straight to main again). Validates at
 * the store boundary via ValidateBranchName so invalid refnames
 * (whitespace, leading `-`, embedded `..`, etc.) surface as an error
 * from the client. Parallel to SetFeatureEmoji.
 */
export function SetFeatureBranchName(repoPrefix: string, slug: string, branch: string): $CancellablePromise<$models.FeatureDetail> {
    return $Call.ByID(521024498, repoPrefix, slug, branch).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetFeatureCollectHandoffs (BACI-333) flips the per-feature
 * collect-handoffs toggle and returns the refreshed FeatureDetail.
 * enabled=true collects worker close-out handoff comments; enabled=false
 * silences a standing bucket. Idempotent — flipping to the same state is
 * a no-op write. Mirrors SetFeatureAutoClose's shape.
 */
export function SetFeatureCollectHandoffs(repoPrefix: string, slug: string, enabled: boolean): $CancellablePromise<$models.FeatureDetail> {
    return $Call.ByID(277787338, repoPrefix, slug, enabled).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetFeatureEmoji (BACI-172) updates the per-feature emoji glyph and
 * returns the refreshed FeatureDetail. Empty string clears the
 * emoji. Validates at the store boundary so multi-cluster input
 * (e.g. "FEATURE") surfaces as an error from the client.
 */
export function SetFeatureEmoji(repoPrefix: string, slug: string, emoji: string): $CancellablePromise<$models.FeatureDetail> {
    return $Call.ByID(1872203865, repoPrefix, slug, emoji).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetFeatureState (BACI-199) flips the feature's three-state column
 * and returns the refreshed FeatureDetail. Parses the state string at
 * the boundary so a typo surfaces as a clear error from the client.
 * 
 * BACI-250 decoupled this from the auto-close pin: this method no
 * longer touches state_manual. Use SetFeatureAutoClose to flip the
 * per-feature pin against the BACI-199 auto-completion sweep.
 */
export function SetFeatureState(repoPrefix: string, slug: string, state: string): $CancellablePromise<$models.FeatureDetail> {
    return $Call.ByID(2810734914, repoPrefix, slug, state).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetHiddenOnBoard (BACI-177) flips the per-feature "Show on board"
 * toggle and returns the refreshed FeatureDetail. true hides every
 * kanban card belonging to this feature on this machine; false makes
 * them visible again. Idempotent — flipping to the same state is a
 * no-op write. The flag lives in the per-repo board-hide KV
 * (tui_settings), shared with the TUI's feature picker; flipping it
 * here is visible on the TUI's next reload.
 */
export function SetHiddenOnBoard(repoPrefix: string, slug: string, hidden: boolean): $CancellablePromise<$models.FeatureDetail> {
    return $Call.ByID(1990222744, repoPrefix, slug, hidden).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.FeatureDetail.createFrom;
const $$createType1 = $models.FeaturePlan.createFrom;
const $$createType2 = $models.FeatureSummary.createFrom;
const $$createType3 = $Create.Array($$createType2);
