// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FeatureService is the Wails-bound feature API the desktop frontend talks to.
 * It wraps a local bacio client.Client and reshapes its results into the DTOs
 * the Features view expects. Read-only: features are created and edited via
 * the CLI. Features are per-repo, so every method needs a concrete repo
 * prefix (the "all repositories" pseudo-board has no feature scope).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddFeatureComment posts a chronological handoff comment to a feature
 * (BACI-124) and returns the refreshed detail.
 */
export function AddFeatureComment(repoPrefix: string, slug: string, author: string, body: string): $CancellablePromise<$models.FeatureDetail> {
    return $Call.ByID(517388757, repoPrefix, slug, author, body).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DeleteFeatureComment removes a feature comment by uuid (BACI-124) and
 * returns the refreshed detail.
 */
export function DeleteFeatureComment(repoPrefix: string, slug: string, commentUUID: string): $CancellablePromise<$models.FeatureDetail> {
    return $Call.ByID(1504383339, repoPrefix, slug, commentUUID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetFeature returns one feature with its description and the issues grouped
 * under it, for the detail pane.
 */
export function GetFeature(repoPrefix: string, slug: string): $CancellablePromise<$models.FeatureDetail> {
    return $Call.ByID(3103647661, repoPrefix, slug).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListFeatures returns every feature in one repo as a summary row.
 * Archived features (BACI-68) follow display.show_archived.
 */
export function ListFeatures(repoPrefix: string): $CancellablePromise<$models.FeatureSummary[]> {
    return $Call.ByID(640296380, repoPrefix).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $models.FeatureDetail.createFrom;
const $$createType1 = $models.FeatureSummary.createFrom;
const $$createType2 = $Create.Array($$createType1);
