// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HistoryService is the Wails-bound audit-log API the desktop frontend talks
 * to. It wraps a local bacio client.Client and serves the history newest-first
 * in fixed-size pages. Read-only. History is per-repo, so every call needs a
 * concrete repo prefix (the "all repositories" pseudo-board has no scope).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ListHistory returns one page of the repo's audit log, newest first. page is
 * 0-based; pageSize is clamped to a sane range. It over-fetches by one row so
 * HasMore can be reported without a separate count query.
 */
export function ListHistory(repoPrefix: string, page: number, pageSize: number): $CancellablePromise<$models.HistoryPage> {
    return $Call.ByID(1990576659, repoPrefix, page, pageSize).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.HistoryPage.createFrom;
