// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LeaderService runs the UI leader election for the desktop app. It
 * satisfies the Wails v3 service lifecycle — ServiceStartup opens a
 * dedicated *store.Store handle and starts the shared
 * leaderservice.Service; ServiceShutdown stops it, releases the lease,
 * then closes the store.
 * 
 * It opens its own *store.Store (a second handle on the same WAL-mode
 * file) rather than routing through client.Client, keeping it simple and
 * consistent with how the CLI opens fresh store handles on every
 * invocation.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as leaderservice$0 from "../internal/leaderservice/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetLeaderStatus returns the current election state synchronously —
 * used by the frontend on mount to seed its UI before the first event
 * arrives.
 */
export function GetLeaderStatus(): $CancellablePromise<$models.LeaderStatusDTO> {
    return $Call.ByID(2365494043).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = leaderservice$0.StatusDTO.createFrom;
