// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../time/models.js";

/**
 * Board is one bacio repo, offered in the top-nav repository selector.
 */
export class Board {
    "prefix": string;
    "name": string;
    "issueCount": number;

    /** Creates a new Board instance. */
    constructor($$source: Partial<Board> = {}) {
        if (!("prefix" in $$source)) {
            this["prefix"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("issueCount" in $$source)) {
            this["issueCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Board instance from a string or object.
     */
    static createFrom($$source: any = {}): Board {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Board($$parsedSource as Partial<Board>);
    }
}

/**
 * BoardCard is a kanban card — one bacio issue, shaped for the imported UI kit.
 */
export class BoardCard {
    "key": string;
    "column": string;
    "columnLabel": string;
    "title": string;
    "tags": string[];
    "assignees": string[];
    "claude": boolean;

    /** Creates a new BoardCard instance. */
    constructor($$source: Partial<BoardCard> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("column" in $$source)) {
            this["column"] = "";
        }
        if (!("columnLabel" in $$source)) {
            this["columnLabel"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("assignees" in $$source)) {
            this["assignees"] = [];
        }
        if (!("claude" in $$source)) {
            this["claude"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BoardCard instance from a string or object.
     */
    static createFrom($$source: any = {}): BoardCard {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        if ("assignees" in $$parsedSource) {
            $$parsedSource["assignees"] = $$createField5_0($$parsedSource["assignees"]);
        }
        return new BoardCard($$parsedSource as Partial<BoardCard>);
    }
}

/**
 * BoardColumn is one kanban column — one bacio issue state.
 */
export class BoardColumn {
    "state": string;
    "label": string;

    /** Creates a new BoardColumn instance. */
    constructor($$source: Partial<BoardColumn> = {}) {
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BoardColumn instance from a string or object.
     */
    static createFrom($$source: any = {}): BoardColumn {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BoardColumn($$parsedSource as Partial<BoardColumn>);
    }
}

/**
 * CommentDTO is one issue comment.
 */
export class CommentDTO {
    "author": string;
    "body": string;
    "createdAt": time$0.Time;

    /** Creates a new CommentDTO instance. */
    constructor($$source: Partial<CommentDTO> = {}) {
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommentDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): CommentDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommentDTO($$parsedSource as Partial<CommentDTO>);
    }
}

/**
 * IssueDetail is the issue-drawer payload for a single issue.
 */
export class IssueDetail {
    "key": string;
    "column": string;
    "columnLabel": string;
    "title": string;
    "description": string;
    "tags": string[];
    "assignees": string[];
    "claude": boolean;
    "comments": CommentDTO[];
    "pullRequests": PRDTO[];

    /** Creates a new IssueDetail instance. */
    constructor($$source: Partial<IssueDetail> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("column" in $$source)) {
            this["column"] = "";
        }
        if (!("columnLabel" in $$source)) {
            this["columnLabel"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("assignees" in $$source)) {
            this["assignees"] = [];
        }
        if (!("claude" in $$source)) {
            this["claude"] = false;
        }
        if (!("comments" in $$source)) {
            this["comments"] = [];
        }
        if (!("pullRequests" in $$source)) {
            this["pullRequests"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IssueDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): IssueDetail {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        const $$createField8_0 = $$createType2;
        const $$createField9_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField5_0($$parsedSource["tags"]);
        }
        if ("assignees" in $$parsedSource) {
            $$parsedSource["assignees"] = $$createField6_0($$parsedSource["assignees"]);
        }
        if ("comments" in $$parsedSource) {
            $$parsedSource["comments"] = $$createField8_0($$parsedSource["comments"]);
        }
        if ("pullRequests" in $$parsedSource) {
            $$parsedSource["pullRequests"] = $$createField9_0($$parsedSource["pullRequests"]);
        }
        return new IssueDetail($$parsedSource as Partial<IssueDetail>);
    }
}

/**
 * PRDTO is one attached pull request.
 */
export class PRDTO {
    "url": string;

    /** Creates a new PRDTO instance. */
    constructor($$source: Partial<PRDTO> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PRDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): PRDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PRDTO($$parsedSource as Partial<PRDTO>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = CommentDTO.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = PRDTO.createFrom;
const $$createType4 = $Create.Array($$createType3);
