// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agentcards$0 from "../internal/agentcards/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as boardcards$0 from "../internal/boardcards/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as leaderservice$0 from "../internal/leaderservice/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../time/models.js";

/**
 * ClaimantDTO, ClaimDTO, SessionTodoDTO, DispatchDTO, and AgentCard
 * live in internal/agentcards so the bacio api can serve the same wire
 * format (BACI-50) and the per-issue claimant mapper has one home
 * (BACI-55). Aliases keep the Wails-bound surface unchanged — the
 * generated TS bindings point at the same struct names from the
 * desktop's perspective, so the existing api.ts and components don't
 * need to update their imports.
 */
export const AgentCard = agentcards$0.AgentCard;

/**
 * ClaimantDTO, ClaimDTO, SessionTodoDTO, DispatchDTO, and AgentCard
 * live in internal/agentcards so the bacio api can serve the same wire
 * format (BACI-50) and the per-issue claimant mapper has one home
 * (BACI-55). Aliases keep the Wails-bound surface unchanged — the
 * generated TS bindings point at the same struct names from the
 * desktop's perspective, so the existing api.ts and components don't
 * need to update their imports.
 */
export type AgentCard = agentcards$0.AgentCard;

/**
 * ArchivePreferencesDTO is the BACI-162 auto-archive pair shaped for
 * the desktop Settings panel. AutoEnabled gates the hourly issue
 * auto-archive pass; RetentionDays is the number of days a
 * terminal-state issue's terminal_at must sit before the next sweep
 * archives it (1..3650; default 7).
 */
export class ArchivePreferencesDTO {
    "autoEnabled": boolean;
    "retentionDays": number;

    /** Creates a new ArchivePreferencesDTO instance. */
    constructor($$source: Partial<ArchivePreferencesDTO> = {}) {
        if (!("autoEnabled" in $$source)) {
            this["autoEnabled"] = false;
        }
        if (!("retentionDays" in $$source)) {
            this["retentionDays"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArchivePreferencesDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ArchivePreferencesDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ArchivePreferencesDTO($$parsedSource as Partial<ArchivePreferencesDTO>);
    }
}

/**
 * Board is one bacio repo, offered in the top-nav repository selector.
 * 
 * The SyncEnabled / SyncInProgress / SyncLastAt / SyncLastError fields
 * (BACI-89) drive the topbar's live sync-status badge: SyncEnabled is
 * "this repo has git sync configured"; the other three reflect the
 * background sync runner's last / current state.
 */
export class Board {
    "prefix": string;
    "name": string;
    "issueCount": number;
    "syncEnabled": boolean;
    "syncInProgress": boolean;
    "syncLastAt"?: time$0.Time | null;
    "syncLastError"?: string;

    /** Creates a new Board instance. */
    constructor($$source: Partial<Board> = {}) {
        if (!("prefix" in $$source)) {
            this["prefix"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("issueCount" in $$source)) {
            this["issueCount"] = 0;
        }
        if (!("syncEnabled" in $$source)) {
            this["syncEnabled"] = false;
        }
        if (!("syncInProgress" in $$source)) {
            this["syncInProgress"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Board instance from a string or object.
     */
    static createFrom($$source: any = {}): Board {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Board($$parsedSource as Partial<Board>);
    }
}

/**
 * BoardCard is the kanban-card wire shape, hoisted into
 * internal/boardcards so the bacio api can serve the same payload
 * over REST (mirrors the BACI-50 agentcards extraction). The alias
 * keeps the Wails-bound surface unchanged — the generated TS
 * bindings still point at the same struct name from the desktop's
 * perspective, so api.ts and components don't need to update their
 * imports.
 */
export const BoardCard = boardcards$0.BoardCard;

/**
 * BoardCard is the kanban-card wire shape, hoisted into
 * internal/boardcards so the bacio api can serve the same payload
 * over REST (mirrors the BACI-50 agentcards extraction). The alias
 * keeps the Wails-bound surface unchanged — the generated TS
 * bindings still point at the same struct name from the desktop's
 * perspective, so api.ts and components don't need to update their
 * imports.
 */
export type BoardCard = boardcards$0.BoardCard;

/**
 * BoardColumn is one kanban column — one bacio issue state.
 */
export class BoardColumn {
    "state": string;
    "label": string;

    /** Creates a new BoardColumn instance. */
    constructor($$source: Partial<BoardColumn> = {}) {
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BoardColumn instance from a string or object.
     */
    static createFrom($$source: any = {}): BoardColumn {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BoardColumn($$parsedSource as Partial<BoardColumn>);
    }
}

/**
 * ClaimantDTO, ClaimDTO, SessionTodoDTO, DispatchDTO, and AgentCard
 * live in internal/agentcards so the bacio api can serve the same wire
 * format (BACI-50) and the per-issue claimant mapper has one home
 * (BACI-55). Aliases keep the Wails-bound surface unchanged — the
 * generated TS bindings point at the same struct names from the
 * desktop's perspective, so the existing api.ts and components don't
 * need to update their imports.
 */
export const ClaimantDTO = agentcards$0.ClaimantDTO;

/**
 * ClaimantDTO, ClaimDTO, SessionTodoDTO, DispatchDTO, and AgentCard
 * live in internal/agentcards so the bacio api can serve the same wire
 * format (BACI-50) and the per-issue claimant mapper has one home
 * (BACI-55). Aliases keep the Wails-bound surface unchanged — the
 * generated TS bindings point at the same struct names from the
 * desktop's perspective, so the existing api.ts and components don't
 * need to update their imports.
 */
export type ClaimantDTO = agentcards$0.ClaimantDTO;

/**
 * CollisionPreviewDTO is the projected renumber / rename churn a clone
 * or attach would produce when local rows collide with imported ones.
 * Mirrors sync.CollisionPreview; the JS side iterates these to render
 * the step-2 banner.
 */
export class CollisionPreviewDTO {
    "renumbered"?: RenumberEntryDTO[];
    "renamed"?: RenameEntryDTO[];

    /** Creates a new CollisionPreviewDTO instance. */
    constructor($$source: Partial<CollisionPreviewDTO> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CollisionPreviewDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): CollisionPreviewDTO {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("renumbered" in $$parsedSource) {
            $$parsedSource["renumbered"] = $$createField0_0($$parsedSource["renumbered"]);
        }
        if ("renamed" in $$parsedSource) {
            $$parsedSource["renamed"] = $$createField1_0($$parsedSource["renamed"]);
        }
        return new CollisionPreviewDTO($$parsedSource as Partial<CollisionPreviewDTO>);
    }
}

/**
 * CommentDTO is one issue comment. UUID is the immutable identity the
 * React layer addresses a delete with.
 * 
 * BACI-131 added the four eval-context fields the kanban quick-eval
 * composer pins onto a comment at write time. They're zero values on
 * a normal comment; AgentName is the persistent agent-identity slug
 * resolved server-side via the agent_sessions → agents JOIN at read
 * time (never persisted on the row).
 */
export class CommentDTO {
    "uuid": string;
    "author": string;
    "body": string;
    "createdAt": time$0.Time;
    "eval": boolean;
    "agentSessionId"?: string;
    "dispatchId"?: number | null;
    "mode"?: string;
    "agentName"?: string;

    /**
     * TranscriptEventRef (BACI-141) pins this comment to a specific
     * event inside a `.jsonl` transcript when set, so the transcript
     * viewer can render it as an inline annotation next to the matching
     * event card. Empty = unanchored, rendered pinned to the dispatch
     * prompt card at the top of the transcript view.
     */
    "transcriptEventRef"?: string;

    /** Creates a new CommentDTO instance. */
    constructor($$source: Partial<CommentDTO> = {}) {
        if (!("uuid" in $$source)) {
            this["uuid"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("eval" in $$source)) {
            this["eval"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommentDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): CommentDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommentDTO($$parsedSource as Partial<CommentDTO>);
    }
}

/**
 * DefaultFeatureDTO (BACI-235) is the per-repo default_feature setting
 * shaped for the desktop / web Settings panel. Slug is empty when the
 * setting is unset; Title / Emoji are inflated when the setting is set
 * so the dropdown can render the same glyph + label as the rest of the
 * feature affordances. Mirrors FeatureSummary's slim shape.
 */
export class DefaultFeatureDTO {
    "slug": string;
    "title"?: string;
    "emoji"?: string;

    /** Creates a new DefaultFeatureDTO instance. */
    constructor($$source: Partial<DefaultFeatureDTO> = {}) {
        if (!("slug" in $$source)) {
            this["slug"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DefaultFeatureDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): DefaultFeatureDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DefaultFeatureDTO($$parsedSource as Partial<DefaultFeatureDTO>);
    }
}

/**
 * ClaimantDTO, ClaimDTO, SessionTodoDTO, DispatchDTO, and AgentCard
 * live in internal/agentcards so the bacio api can serve the same wire
 * format (BACI-50) and the per-issue claimant mapper has one home
 * (BACI-55). Aliases keep the Wails-bound surface unchanged — the
 * generated TS bindings point at the same struct names from the
 * desktop's perspective, so the existing api.ts and components don't
 * need to update their imports.
 */
export const DispatchDTO = agentcards$0.DispatchDTO;

/**
 * ClaimantDTO, ClaimDTO, SessionTodoDTO, DispatchDTO, and AgentCard
 * live in internal/agentcards so the bacio api can serve the same wire
 * format (BACI-50) and the per-issue claimant mapper has one home
 * (BACI-55). Aliases keep the Wails-bound surface unchanged — the
 * generated TS bindings point at the same struct names from the
 * desktop's perspective, so the existing api.ts and components don't
 * need to update their imports.
 */
export type DispatchDTO = agentcards$0.DispatchDTO;

/**
 * DisplayPreferencesDTO is the BACI-68 display.show_archived global
 * toggle, shaped for the desktop Settings panel.
 */
export class DisplayPreferencesDTO {
    "showArchived": boolean;

    /** Creates a new DisplayPreferencesDTO instance. */
    constructor($$source: Partial<DisplayPreferencesDTO> = {}) {
        if (!("showArchived" in $$source)) {
            this["showArchived"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DisplayPreferencesDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): DisplayPreferencesDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DisplayPreferencesDTO($$parsedSource as Partial<DisplayPreferencesDTO>);
    }
}

/**
 * DocContent is one document with its markdown body, for the editor pane.
 */
export class DocContent {
    "filename": string;
    "type": string;
    "content": string;
    "updatedAt": time$0.Time;

    /** Creates a new DocContent instance. */
    constructor($$source: Partial<DocContent> = {}) {
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocContent instance from a string or object.
     */
    static createFrom($$source: any = {}): DocContent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DocContent($$parsedSource as Partial<DocContent>);
    }
}

/**
 * DocLinkDTO is one document linked to an issue, shaped for the drawer's
 * attachments section.
 */
export class DocLinkDTO {
    "filename": string;
    "type": string;

    /**
     * the link's --why reason
     */
    "description": string;

    /** Creates a new DocLinkDTO instance. */
    constructor($$source: Partial<DocLinkDTO> = {}) {
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocLinkDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): DocLinkDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DocLinkDTO($$parsedSource as Partial<DocLinkDTO>);
    }
}

/**
 * DocSummary is one document, shaped for the desktop document list.
 * 
 * BACI-204 adds Links + Snippet + ArchivedAt + CreatedAt so the
 * redesigned Documents page can render the linked-issue / linked-feature
 * chips, a per-row snippet under each title, sort by created date,
 * and mute archived rows — all without a second round trip per row.
 * Existing fields stay first so the wire shape is purely additive.
 */
export class DocSummary {
    "filename": string;
    "type": string;
    "sizeBytes": number;
    "updatedAt": time$0.Time;
    "createdAt": time$0.Time;
    "archivedAt"?: time$0.Time | null;
    "snippet"?: string;
    "links"?: DocSummaryLinkDTO[];

    /** Creates a new DocSummary instance. */
    constructor($$source: Partial<DocSummary> = {}) {
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("sizeBytes" in $$source)) {
            this["sizeBytes"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): DocSummary {
        const $$createField7_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("links" in $$parsedSource) {
            $$parsedSource["links"] = $$createField7_0($$parsedSource["links"]);
        }
        return new DocSummary($$parsedSource as Partial<DocSummary>);
    }
}

/**
 * DocSummaryLinkDTO is one link row on a DocSummary — issue or feature plus
 * the per-link description. Same fields as the brief endpoint's
 * LinkedDocDTO so the React rendering stays consistent across the
 * document-detail and document-list surfaces.
 */
export class DocSummaryLinkDTO {
    "issueKey"?: string;
    "featureSlug"?: string;
    "description"?: string;

    /** Creates a new DocSummaryLinkDTO instance. */
    constructor($$source: Partial<DocSummaryLinkDTO> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocSummaryLinkDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): DocSummaryLinkDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DocSummaryLinkDTO($$parsedSource as Partial<DocSummaryLinkDTO>);
    }
}

/**
 * FeatureComment mirrors model.FeatureComment, shaped for the desktop
 * feature detail pane (BACI-124).
 */
export class FeatureComment {
    "uuid": string;
    "author": string;
    "body": string;
    "createdAt": time$0.Time;

    /** Creates a new FeatureComment instance. */
    constructor($$source: Partial<FeatureComment> = {}) {
        if (!("uuid" in $$source)) {
            this["uuid"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FeatureComment instance from a string or object.
     */
    static createFrom($$source: any = {}): FeatureComment {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FeatureComment($$parsedSource as Partial<FeatureComment>);
    }
}

/**
 * FeatureDetail is one feature with its description and linked issues — the
 * payload for the desktop feature detail pane.
 */
export class FeatureDetail {
    "slug": string;
    "title": string;
    "description": string;

    /**
     * Emoji (BACI-172) is the per-feature glyph rendered in the
     * top-left of every kanban card belonging to this feature.
     * Empty when none has been set — the FeaturesView surfaces a
     * "set emoji" affordance in that case.
     */
    "emoji": string;

    /**
     * State + StateManual (BACI-199) round-trip the per-feature state
     * column and its sticky bit. The drawer's segmented control reads
     * State to highlight the active button, and StateManual to render
     * a "pinned" indicator next to it so the user knows the
     * auto-completion sweep won't move it.
     */
    "state": string;
    "stateManual": boolean;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;
    "issues": FeatureLinkedIssue[];

    /**
     * Comments is the BACI-124 chronological-handoff timeline, oldest
     * first. Drives the feature drawer's comment panel.
     */
    "comments": FeatureComment[];

    /**
     * Documents (BACI-214) is the list of documents linked to this
     * feature via `bacio doc link <file> <feature-slug>`. Drives the
     * "Documents" section on the FeaturesView detail pane — each row
     * links to the canonical /documents/<filename> viewer.
     */
    "documents": FeatureLinkedDoc[];

    /**
     * HiddenOnBoard (BACI-177) mirrors the per-feature "Show on board"
     * toggle. When true, every kanban card belonging to this feature
     * is hidden from the board on this machine.
     */
    "hiddenOnBoard": boolean;

    /** Creates a new FeatureDetail instance. */
    constructor($$source: Partial<FeatureDetail> = {}) {
        if (!("slug" in $$source)) {
            this["slug"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("emoji" in $$source)) {
            this["emoji"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("stateManual" in $$source)) {
            this["stateManual"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }
        if (!("issues" in $$source)) {
            this["issues"] = [];
        }
        if (!("comments" in $$source)) {
            this["comments"] = [];
        }
        if (!("documents" in $$source)) {
            this["documents"] = [];
        }
        if (!("hiddenOnBoard" in $$source)) {
            this["hiddenOnBoard"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FeatureDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): FeatureDetail {
        const $$createField8_0 = $$createType7;
        const $$createField9_0 = $$createType9;
        const $$createField10_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("issues" in $$parsedSource) {
            $$parsedSource["issues"] = $$createField8_0($$parsedSource["issues"]);
        }
        if ("comments" in $$parsedSource) {
            $$parsedSource["comments"] = $$createField9_0($$parsedSource["comments"]);
        }
        if ("documents" in $$parsedSource) {
            $$parsedSource["documents"] = $$createField10_0($$parsedSource["documents"]);
        }
        return new FeatureDetail($$parsedSource as Partial<FeatureDetail>);
    }
}

/**
 * FeatureLinkedDoc is one document linked to this feature via
 * `bacio doc link <file> <feature-slug>`, shaped for the desktop /
 * web feature detail pane (BACI-214). Filename + Type drive the
 * per-row chrome; Description carries the link-time `--why` (which is
 * model.DocumentLink.Description, not the doc's own description).
 * SourcePath is reserved for parity with the issue-workspace
 * LinkedDocPanel shape but stays empty here — `view.Documents` is a
 * link slice, not a doc slice, so resolving the source path would
 * cost an extra round-trip per doc and isn't surfaced on the feature
 * pane today. Deliberately narrower than the issue brief's LinkedDoc
 * (no `linkedVia` / no `sizeBytes`): the feature pane is single-source
 * of truth for "linked to this feature" so the disambiguating chips
 * the issue panel renders don't apply.
 */
export class FeatureLinkedDoc {
    "filename": string;
    "type": string;
    "description": string;
    "sourcePath": string;

    /** Creates a new FeatureLinkedDoc instance. */
    constructor($$source: Partial<FeatureLinkedDoc> = {}) {
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("sourcePath" in $$source)) {
            this["sourcePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FeatureLinkedDoc instance from a string or object.
     */
    static createFrom($$source: any = {}): FeatureLinkedDoc {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FeatureLinkedDoc($$parsedSource as Partial<FeatureLinkedDoc>);
    }
}

/**
 * FeatureLinkedIssue is one issue grouped under a feature, for the detail pane.
 */
export class FeatureLinkedIssue {
    "key": string;
    "title": string;
    "state": string;
    "stateLabel": string;

    /** Creates a new FeatureLinkedIssue instance. */
    constructor($$source: Partial<FeatureLinkedIssue> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("stateLabel" in $$source)) {
            this["stateLabel"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FeatureLinkedIssue instance from a string or object.
     */
    static createFrom($$source: any = {}): FeatureLinkedIssue {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FeatureLinkedIssue($$parsedSource as Partial<FeatureLinkedIssue>);
    }
}

/**
 * FeaturePlan is the dependency-graph payload for one feature
 * (BACI-236). Slug echoes the requested feature; Order is the
 * topo-sorted issue list driving the graph view's nodes + edges.
 */
export class FeaturePlan {
    "slug": string;
    "order": FeaturePlanEntry[];

    /** Creates a new FeaturePlan instance. */
    constructor($$source: Partial<FeaturePlan> = {}) {
        if (!("slug" in $$source)) {
            this["slug"] = "";
        }
        if (!("order" in $$source)) {
            this["order"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FeaturePlan instance from a string or object.
     */
    static createFrom($$source: any = {}): FeaturePlan {
        const $$createField1_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("order" in $$parsedSource) {
            $$parsedSource["order"] = $$createField1_0($$parsedSource["order"]);
        }
        return new FeaturePlan($$parsedSource as Partial<FeaturePlan>);
    }
}

/**
 * FeaturePlanEntry mirrors api.PlanEntry, reshaped to the camelCase
 * JSON tags the desktop / web bundle expects (BACI-236). One row per
 * issue in the feature; BlockedBy carries the keys of in-feature
 * blockers the dependency-graph view turns into directed edges.
 * Closed is true for done / cancelled issues so the renderer can mute
 * them while still drawing their connections to live work.
 */
export class FeaturePlanEntry {
    "key": string;
    "title": string;
    "state": string;
    "assignee": string;
    "blockedBy": string[];
    "closed": boolean;

    /** Creates a new FeaturePlanEntry instance. */
    constructor($$source: Partial<FeaturePlanEntry> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("assignee" in $$source)) {
            this["assignee"] = "";
        }
        if (!("blockedBy" in $$source)) {
            this["blockedBy"] = [];
        }
        if (!("closed" in $$source)) {
            this["closed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FeaturePlanEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): FeaturePlanEntry {
        const $$createField4_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("blockedBy" in $$parsedSource) {
            $$parsedSource["blockedBy"] = $$createField4_0($$parsedSource["blockedBy"]);
        }
        return new FeaturePlanEntry($$parsedSource as Partial<FeaturePlanEntry>);
    }
}

/**
 * FeatureRefDTO is the lightweight feature reference attached to an
 * issue brief — slug + title. Just enough to render the feature pill
 * in the workspace rail without leaking the full FeatureDetail.
 */
export class FeatureRefDTO {
    "slug": string;
    "title": string;

    /** Creates a new FeatureRefDTO instance. */
    constructor($$source: Partial<FeatureRefDTO> = {}) {
        if (!("slug" in $$source)) {
            this["slug"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FeatureRefDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): FeatureRefDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FeatureRefDTO($$parsedSource as Partial<FeatureRefDTO>);
    }
}

/**
 * FeatureSummary is one feature, shaped for the desktop feature list.
 * 
 * Emoji (BACI-184) carries the per-feature glyph so the Features panel
 * list can render it alongside the title — same glyph BACI-172 paints
 * on every kanban card. Empty when no emoji has been set.
 * 
 * HiddenOnBoard (BACI-177) mirrors the per-feature "Show on board"
 * toggle on the Features screen — when true, every kanban card
 * belonging to this feature is hidden from the board on this machine.
 * Lives in the per-repo board-hide KV (tui_settings), not on the
 * features row.
 */
export class FeatureSummary {
    "slug": string;
    "title": string;
    "emoji": string;

    /**
     * State (BACI-199) is the three-state column on the feature row
     * — `active` (default — work in flight), `done` (delivered) or
     * `cancelled` (abandoned). The Features panel renders a state
     * pill so a glance distinguishes work in flight from delivered /
     * abandoned work.
     */
    "state": string;
    "updatedAt": time$0.Time;
    "hiddenOnBoard": boolean;

    /** Creates a new FeatureSummary instance. */
    constructor($$source: Partial<FeatureSummary> = {}) {
        if (!("slug" in $$source)) {
            this["slug"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("emoji" in $$source)) {
            this["emoji"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }
        if (!("hiddenOnBoard" in $$source)) {
            this["hiddenOnBoard"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FeatureSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): FeatureSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FeatureSummary($$parsedSource as Partial<FeatureSummary>);
    }
}

/**
 * HistoryEntryDTO is one audit-log row, shaped for the desktop history table.
 */
export class HistoryEntryDTO {
    "id": number;
    "actor": string;
    "op": string;
    "kind": string;
    "targetLabel": string;
    "details": string;
    "createdAt": time$0.Time;

    /** Creates a new HistoryEntryDTO instance. */
    constructor($$source: Partial<HistoryEntryDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("actor" in $$source)) {
            this["actor"] = "";
        }
        if (!("op" in $$source)) {
            this["op"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("targetLabel" in $$source)) {
            this["targetLabel"] = "";
        }
        if (!("details" in $$source)) {
            this["details"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryEntryDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryEntryDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryEntryDTO($$parsedSource as Partial<HistoryEntryDTO>);
    }
}

/**
 * HistoryPage is one page of the audit log. Page is 0-based; HasMore reports
 * whether a further page exists, so the frontend can drive Prev/Next without a
 * separate total-count query.
 */
export class HistoryPage {
    "entries": HistoryEntryDTO[];
    "page": number;
    "pageSize": number;
    "hasMore": boolean;

    /** Creates a new HistoryPage instance. */
    constructor($$source: Partial<HistoryPage> = {}) {
        if (!("entries" in $$source)) {
            this["entries"] = [];
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            this["pageSize"] = 0;
        }
        if (!("hasMore" in $$source)) {
            this["hasMore"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryPage instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryPage {
        const $$createField0_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField0_0($$parsedSource["entries"]);
        }
        return new HistoryPage($$parsedSource as Partial<HistoryPage>);
    }
}

/**
 * IssueBriefDTO is the workspace-shaped payload — BoardService.GetIssueBrief's
 * return value, mirroring internal/client/views.go::IssueBrief with desktop
 * camelCase JSON tags. New fields over IssueDetail: feature, relations,
 * waitingForClaim, warnings, and doc content (via LinkedDocDTO).
 * 
 * BACI-145: WaitingState is the structured "why is this card waiting?"
 * projection used by the IssueLockBanner — same shape and same wording
 * as the kanban-card label. Nil when the issue isn't waiting; the
 * banner falls back to its "taken" branch when an agent has the claim.
 */
export class IssueBriefDTO {
    "issue": IssueMetaDTO;
    "feature"?: FeatureRefDTO | null;
    "relations": RelationsDTO;
    "pullRequests": PRDTO[];
    "documents": LinkedDocDTO[];
    "comments": CommentDTO[];
    "claimants": ClaimantDTO[];
    "taken": boolean;
    "waitingForClaim": boolean;
    "waitingState"?: boardcards$0.WaitingState | null;

    /**
     * LatestPlan (BACI-216) — duplicated alongside Issue.LatestPlan
     * so consumers that read the brief envelope (REST/HTTP clients)
     * can pick it up without descending into the meta block. The two
     * are always in lockstep.
     */
    "latestPlan"?: LatestPlanDTO | null;
    "warnings": string[];

    /** Creates a new IssueBriefDTO instance. */
    constructor($$source: Partial<IssueBriefDTO> = {}) {
        if (!("issue" in $$source)) {
            this["issue"] = (new IssueMetaDTO());
        }
        if (!("relations" in $$source)) {
            this["relations"] = (new RelationsDTO());
        }
        if (!("pullRequests" in $$source)) {
            this["pullRequests"] = [];
        }
        if (!("documents" in $$source)) {
            this["documents"] = [];
        }
        if (!("comments" in $$source)) {
            this["comments"] = [];
        }
        if (!("claimants" in $$source)) {
            this["claimants"] = [];
        }
        if (!("taken" in $$source)) {
            this["taken"] = false;
        }
        if (!("waitingForClaim" in $$source)) {
            this["waitingForClaim"] = false;
        }
        if (!("warnings" in $$source)) {
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IssueBriefDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): IssueBriefDTO {
        const $$createField0_0 = $$createType17;
        const $$createField1_0 = $$createType19;
        const $$createField2_0 = $$createType20;
        const $$createField3_0 = $$createType22;
        const $$createField4_0 = $$createType24;
        const $$createField5_0 = $$createType26;
        const $$createField6_0 = $$createType28;
        const $$createField9_0 = $$createType30;
        const $$createField10_0 = $$createType32;
        const $$createField11_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("issue" in $$parsedSource) {
            $$parsedSource["issue"] = $$createField0_0($$parsedSource["issue"]);
        }
        if ("feature" in $$parsedSource) {
            $$parsedSource["feature"] = $$createField1_0($$parsedSource["feature"]);
        }
        if ("relations" in $$parsedSource) {
            $$parsedSource["relations"] = $$createField2_0($$parsedSource["relations"]);
        }
        if ("pullRequests" in $$parsedSource) {
            $$parsedSource["pullRequests"] = $$createField3_0($$parsedSource["pullRequests"]);
        }
        if ("documents" in $$parsedSource) {
            $$parsedSource["documents"] = $$createField4_0($$parsedSource["documents"]);
        }
        if ("comments" in $$parsedSource) {
            $$parsedSource["comments"] = $$createField5_0($$parsedSource["comments"]);
        }
        if ("claimants" in $$parsedSource) {
            $$parsedSource["claimants"] = $$createField6_0($$parsedSource["claimants"]);
        }
        if ("waitingState" in $$parsedSource) {
            $$parsedSource["waitingState"] = $$createField9_0($$parsedSource["waitingState"]);
        }
        if ("latestPlan" in $$parsedSource) {
            $$parsedSource["latestPlan"] = $$createField10_0($$parsedSource["latestPlan"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField11_0($$parsedSource["warnings"]);
        }
        return new IssueBriefDTO($$parsedSource as Partial<IssueBriefDTO>);
    }
}

/**
 * IssueDetail is the issue-drawer payload for a single issue.
 */
export class IssueDetail {
    "key": string;
    "column": string;
    "columnLabel": string;
    "title": string;
    "description": string;
    "tags": string[];
    "assignees": string[];
    "claude": boolean;
    "comments": CommentDTO[];
    "pullRequests": PRDTO[];
    "documents": DocLinkDTO[];
    "claimants": ClaimantDTO[];

    /**
     * Taken is the derived "an agent is actively holding this" signal —
     * true iff Claimants has an open (unreleased) claim.
     */
    "taken": boolean;

    /**
     * LatestPlan (BACI-216) — see IssueMetaDTO.LatestPlan.
     */
    "latestPlan"?: LatestPlanDTO | null;

    /** Creates a new IssueDetail instance. */
    constructor($$source: Partial<IssueDetail> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("column" in $$source)) {
            this["column"] = "";
        }
        if (!("columnLabel" in $$source)) {
            this["columnLabel"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("assignees" in $$source)) {
            this["assignees"] = [];
        }
        if (!("claude" in $$source)) {
            this["claude"] = false;
        }
        if (!("comments" in $$source)) {
            this["comments"] = [];
        }
        if (!("pullRequests" in $$source)) {
            this["pullRequests"] = [];
        }
        if (!("documents" in $$source)) {
            this["documents"] = [];
        }
        if (!("claimants" in $$source)) {
            this["claimants"] = [];
        }
        if (!("taken" in $$source)) {
            this["taken"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IssueDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): IssueDetail {
        const $$createField5_0 = $$createType14;
        const $$createField6_0 = $$createType14;
        const $$createField8_0 = $$createType26;
        const $$createField9_0 = $$createType22;
        const $$createField10_0 = $$createType34;
        const $$createField11_0 = $$createType28;
        const $$createField13_0 = $$createType32;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField5_0($$parsedSource["tags"]);
        }
        if ("assignees" in $$parsedSource) {
            $$parsedSource["assignees"] = $$createField6_0($$parsedSource["assignees"]);
        }
        if ("comments" in $$parsedSource) {
            $$parsedSource["comments"] = $$createField8_0($$parsedSource["comments"]);
        }
        if ("pullRequests" in $$parsedSource) {
            $$parsedSource["pullRequests"] = $$createField9_0($$parsedSource["pullRequests"]);
        }
        if ("documents" in $$parsedSource) {
            $$parsedSource["documents"] = $$createField10_0($$parsedSource["documents"]);
        }
        if ("claimants" in $$parsedSource) {
            $$parsedSource["claimants"] = $$createField11_0($$parsedSource["claimants"]);
        }
        if ("latestPlan" in $$parsedSource) {
            $$parsedSource["latestPlan"] = $$createField13_0($$parsedSource["latestPlan"]);
        }
        return new IssueDetail($$parsedSource as Partial<IssueDetail>);
    }
}

/**
 * IssueMetaDTO is the workspace's issue-header payload: the bits the
 * rail and primary column read repeatedly without going through the
 * rest of the brief. Mirrors the BoardCard shape (column + label +
 * title + tags + assignees), plus the description and the derived
 * taken / waitingForClaim flags so the IssueWorkspace doesn't have to
 * hop between brief.issue.{...} and brief.{taken,waitingForClaim}.
 */
export class IssueMetaDTO {
    "key": string;
    "column": string;
    "columnLabel": string;
    "title": string;
    "description": string;
    "tags": string[];
    "assignees": string[];
    "claude": boolean;
    "taken": boolean;
    "waitingForClaim": boolean;

    /**
     * LatestPlan (BACI-216) — the newest `plan`-typed doc linked
     * directly to this issue, or nil when none. Drives the prominent
     * "Open plan" link in IssueWorkspace's header. Mirrors the
     * BoardCard.LatestPlan / IssueDetail.LatestPlan fields so every
     * surface reads the same plan affordance.
     */
    "latestPlan"?: LatestPlanDTO | null;

    /** Creates a new IssueMetaDTO instance. */
    constructor($$source: Partial<IssueMetaDTO> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("column" in $$source)) {
            this["column"] = "";
        }
        if (!("columnLabel" in $$source)) {
            this["columnLabel"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("assignees" in $$source)) {
            this["assignees"] = [];
        }
        if (!("claude" in $$source)) {
            this["claude"] = false;
        }
        if (!("taken" in $$source)) {
            this["taken"] = false;
        }
        if (!("waitingForClaim" in $$source)) {
            this["waitingForClaim"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IssueMetaDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): IssueMetaDTO {
        const $$createField5_0 = $$createType14;
        const $$createField6_0 = $$createType14;
        const $$createField10_0 = $$createType32;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField5_0($$parsedSource["tags"]);
        }
        if ("assignees" in $$parsedSource) {
            $$parsedSource["assignees"] = $$createField6_0($$parsedSource["assignees"]);
        }
        if ("latestPlan" in $$parsedSource) {
            $$parsedSource["latestPlan"] = $$createField10_0($$parsedSource["latestPlan"]);
        }
        return new IssueMetaDTO($$parsedSource as Partial<IssueMetaDTO>);
    }
}

/**
 * LatestPlanDTO (BACI-216) is the Wails-side mirror of
 * model.LatestPlan — the newest `plan`-typed doc linked directly to
 * an issue. Carries enough metadata (filename, uuid, updated_at) for
 * the React surfaces to render the "Open plan" link without a
 * follow-up fetch; the doc body itself is loaded on-demand via the
 * existing /documents/<filename> route.
 */
export class LatestPlanDTO {
    "documentId": number;
    "uuid": string;
    "filename": string;
    "updatedAt": time$0.Time;

    /** Creates a new LatestPlanDTO instance. */
    constructor($$source: Partial<LatestPlanDTO> = {}) {
        if (!("documentId" in $$source)) {
            this["documentId"] = 0;
        }
        if (!("uuid" in $$source)) {
            this["uuid"] = "";
        }
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LatestPlanDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): LatestPlanDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LatestPlanDTO($$parsedSource as Partial<LatestPlanDTO>);
    }
}

/**
 * LeaderStatusDTO is the state the desktop frontend receives on every
 * election tick via the "leaderStatus" Wails event and via
 * GetLeaderStatus on mount. It's a type alias of
 * leaderservice.StatusDTO so the bacio api and desktop share one wire
 * shape; the alias keeps the Wails binding generator emitting a type
 * rooted at main.LeaderStatusDTO so the generated TS stays stable.
 */
export const LeaderStatusDTO = leaderservice$0.StatusDTO;

/**
 * LeaderStatusDTO is the state the desktop frontend receives on every
 * election tick via the "leaderStatus" Wails event and via
 * GetLeaderStatus on mount. It's a type alias of
 * leaderservice.StatusDTO so the bacio api and desktop share one wire
 * shape; the alias keeps the Wails binding generator emitting a type
 * rooted at main.LeaderStatusDTO so the generated TS stays stable.
 */
export type LeaderStatusDTO = leaderservice$0.StatusDTO;

/**
 * LinkedDocDTO is the per-doc shape used by the IssueWorkspace — the
 * drawer-shaped DocLinkDTO plus the body content + source path +
 * linked-via origin (so a doc reachable from both the issue and its
 * feature renders one panel with "(issue + feature)"). Kept separate
 * from DocLinkDTO so the existing drawer / Kanban card payloads don't
 * get fattened.
 */
export class LinkedDocDTO {
    "filename": string;
    "type": string;
    "description": string;
    "sourcePath"?: string;
    "linkedVia": string[];

    /**
     * SizeBytes is the doc's on-disk size in bytes. Always populated, even
     * when Content is omitted from the brief (BACI-115 keeps transcript
     * bodies out of the inlined payload but carries the size so the
     * LinkedDocPanel can render "body not inlined — N KB" instead of the
     * misleading "Document body is empty.").
     */
    "sizeBytes": number;
    "content": string;

    /** Creates a new LinkedDocDTO instance. */
    constructor($$source: Partial<LinkedDocDTO> = {}) {
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("linkedVia" in $$source)) {
            this["linkedVia"] = [];
        }
        if (!("sizeBytes" in $$source)) {
            this["sizeBytes"] = 0;
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LinkedDocDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): LinkedDocDTO {
        const $$createField4_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("linkedVia" in $$parsedSource) {
            $$parsedSource["linkedVia"] = $$createField4_0($$parsedSource["linkedVia"]);
        }
        return new LinkedDocDTO($$parsedSource as Partial<LinkedDocDTO>);
    }
}

/**
 * MemberProjectDTO mirrors client.MemberProject.
 */
export class MemberProjectDTO {
    "prefix": string;
    "name": string;
    "uuid"?: string;
    "status": string;

    /** Creates a new MemberProjectDTO instance. */
    constructor($$source: Partial<MemberProjectDTO> = {}) {
        if (!("prefix" in $$source)) {
            this["prefix"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MemberProjectDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): MemberProjectDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MemberProjectDTO($$parsedSource as Partial<MemberProjectDTO>);
    }
}

/**
 * PRDTO is one attached pull request.
 */
export class PRDTO {
    "url": string;

    /** Creates a new PRDTO instance. */
    constructor($$source: Partial<PRDTO> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PRDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): PRDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PRDTO($$parsedSource as Partial<PRDTO>);
    }
}

/**
 * PromptTemplateDTO is one editable dispatch prompt template, shaped
 * for the desktop Settings panel. Slug is the storage / CLI identifier;
 * Mode is kept as an alias of Slug for backward-compat with frontend
 * code that still keys by `mode`. Body is the persisted body. Default
 * is the built-in embedded default for the slug (empty for user-created
 * templates); IsDefault reports whether Body still matches it.
 * AllowedStates is the state-gate; DefaultStates is the built-in
 * default for the slug (empty for user-created); StatesAreDefault
 * reports whether the gate still matches.
 */
export class PromptTemplateDTO {
    "slug": string;
    "mode": string;
    "label": string;
    "body": string;
    "default": string;
    "isBuiltin": boolean;
    "isDefault": boolean;
    "allowedStates": string[];
    "defaultStates": string[];
    "statesAreDefault": boolean;
    "concurrencyLimit": number;
    "defaultConcurrencyLimit": number;
    "concurrencyIsDefault": boolean;

    /**
     * BACI-67: imperative override rendered on the dispatch action
     * menus. ActionLabel is the persisted value (empty = derive from
     * Name via the gerund→imperative rule); DefaultActionLabel is the
     * built-in imperative seed for the slug (empty for user-created
     * templates); ActionLabelIsDefault reports whether the persisted
     * override still matches the built-in default — drives the
     * Settings panel's "reset" affordance.
     */
    "actionLabel": string;
    "defaultActionLabel": string;
    "actionLabelIsDefault": boolean;

    /** Creates a new PromptTemplateDTO instance. */
    constructor($$source: Partial<PromptTemplateDTO> = {}) {
        if (!("slug" in $$source)) {
            this["slug"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("default" in $$source)) {
            this["default"] = "";
        }
        if (!("isBuiltin" in $$source)) {
            this["isBuiltin"] = false;
        }
        if (!("isDefault" in $$source)) {
            this["isDefault"] = false;
        }
        if (!("allowedStates" in $$source)) {
            this["allowedStates"] = [];
        }
        if (!("defaultStates" in $$source)) {
            this["defaultStates"] = [];
        }
        if (!("statesAreDefault" in $$source)) {
            this["statesAreDefault"] = false;
        }
        if (!("concurrencyLimit" in $$source)) {
            this["concurrencyLimit"] = 0;
        }
        if (!("defaultConcurrencyLimit" in $$source)) {
            this["defaultConcurrencyLimit"] = 0;
        }
        if (!("concurrencyIsDefault" in $$source)) {
            this["concurrencyIsDefault"] = false;
        }
        if (!("actionLabel" in $$source)) {
            this["actionLabel"] = "";
        }
        if (!("defaultActionLabel" in $$source)) {
            this["defaultActionLabel"] = "";
        }
        if (!("actionLabelIsDefault" in $$source)) {
            this["actionLabelIsDefault"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PromptTemplateDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): PromptTemplateDTO {
        const $$createField7_0 = $$createType14;
        const $$createField8_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("allowedStates" in $$parsedSource) {
            $$parsedSource["allowedStates"] = $$createField7_0($$parsedSource["allowedStates"]);
        }
        if ("defaultStates" in $$parsedSource) {
            $$parsedSource["defaultStates"] = $$createField8_0($$parsedSource["defaultStates"]);
        }
        return new PromptTemplateDTO($$parsedSource as Partial<PromptTemplateDTO>);
    }
}

/**
 * RelationDTO is one outgoing/incoming relation, resolved to the other
 * end's issue key.
 */
export class RelationDTO {
    /**
     * blocks | relates_to | duplicate_of
     */
    "type": string;

    /**
     * the *other* end of the edge
     */
    "otherKey": string;

    /** Creates a new RelationDTO instance. */
    constructor($$source: Partial<RelationDTO> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("otherKey" in $$source)) {
            this["otherKey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RelationDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): RelationDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RelationDTO($$parsedSource as Partial<RelationDTO>);
    }
}

/**
 * RelationsDTO splits an issue's relations into the outgoing edges
 * (this issue → other) and incoming edges (other → this issue), each
 * with the other end resolved to a key.
 */
export class RelationsDTO {
    "outgoing": RelationDTO[];
    "incoming": RelationDTO[];

    /** Creates a new RelationsDTO instance. */
    constructor($$source: Partial<RelationsDTO> = {}) {
        if (!("outgoing" in $$source)) {
            this["outgoing"] = [];
        }
        if (!("incoming" in $$source)) {
            this["incoming"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RelationsDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): RelationsDTO {
        const $$createField0_0 = $$createType36;
        const $$createField1_0 = $$createType36;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("outgoing" in $$parsedSource) {
            $$parsedSource["outgoing"] = $$createField0_0($$parsedSource["outgoing"]);
        }
        if ("incoming" in $$parsedSource) {
            $$parsedSource["incoming"] = $$createField1_0($$parsedSource["incoming"]);
        }
        return new RelationsDTO($$parsedSource as Partial<RelationsDTO>);
    }
}

/**
 * RenameEntryDTO is one projected slug/filename rename.
 */
export class RenameEntryDTO {
    "kind": string;
    "old": string;
    "new": string;
    "uuid": string;

    /** Creates a new RenameEntryDTO instance. */
    constructor($$source: Partial<RenameEntryDTO> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("old" in $$source)) {
            this["old"] = "";
        }
        if (!("new" in $$source)) {
            this["new"] = "";
        }
        if (!("uuid" in $$source)) {
            this["uuid"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RenameEntryDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): RenameEntryDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RenameEntryDTO($$parsedSource as Partial<RenameEntryDTO>);
    }
}

/**
 * RenumberEntryDTO is one projected issue renumber.
 */
export class RenumberEntryDTO {
    "prefix": string;
    "oldNumber": number;
    "newNumber": number;
    "uuid": string;

    /** Creates a new RenumberEntryDTO instance. */
    constructor($$source: Partial<RenumberEntryDTO> = {}) {
        if (!("prefix" in $$source)) {
            this["prefix"] = "";
        }
        if (!("oldNumber" in $$source)) {
            this["oldNumber"] = 0;
        }
        if (!("newNumber" in $$source)) {
            this["newNumber"] = 0;
        }
        if (!("uuid" in $$source)) {
            this["uuid"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RenumberEntryDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): RenumberEntryDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RenumberEntryDTO($$parsedSource as Partial<RenumberEntryDTO>);
    }
}

/**
 * RepoLinkResultDTO is the camelCase Wails-side outcome of
 * LinkPhantomRepo (BACI-112). Mirrors client.RepoLinkResult — the
 * upgraded repo row plus the URL of the sync repo whose
 * repos/<prefix>/ folder owns the phantom, plus AlreadyLinked which
 * is true on an idempotent re-link.
 */
export class RepoLinkResultDTO {
    "prefix": string;
    "path": string;
    "syncRemoteUrl": string;
    "alreadyLinked": boolean;

    /** Creates a new RepoLinkResultDTO instance. */
    constructor($$source: Partial<RepoLinkResultDTO> = {}) {
        if (!("prefix" in $$source)) {
            this["prefix"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("syncRemoteUrl" in $$source)) {
            this["syncRemoteUrl"] = "";
        }
        if (!("alreadyLinked" in $$source)) {
            this["alreadyLinked"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RepoLinkResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): RepoLinkResultDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RepoLinkResultDTO($$parsedSource as Partial<RepoLinkResultDTO>);
    }
}

/**
 * SetupSyncIn is the camelCase Wails-side input for SetupSync — the
 * React tree builds it in SyncSetupModal. Mirrors the snake-case
 * inputs.SyncSetupInput the HTTP layer accepts; the field set is the
 * same. AllowRenumber gates the renumber-collision preview the engine
 * produces on a clone / attach that would renumber local rows.
 */
export class SetupSyncIn {
    "mode": string;
    "remote"?: string;
    "localPath"?: string;
    "allowRenumber"?: boolean;

    /** Creates a new SetupSyncIn instance. */
    constructor($$source: Partial<SetupSyncIn> = {}) {
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SetupSyncIn instance from a string or object.
     */
    static createFrom($$source: any = {}): SetupSyncIn {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SetupSyncIn($$parsedSource as Partial<SetupSyncIn>);
    }
}

/**
 * ShippedIssueDTO is one row in the BACI-187 shipping-log popover.
 * Lean by design — the popover renders key + title + a relative date
 * chip + tags + an optional PR chip. The DTO shape mirrors the HTTP
 * /repos/{prefix}/shipped response so the React side imports the
 * same type from either api.ts (Wails) or api.http.ts (HTTP) without
 * reshape.
 */
export class ShippedIssueDTO {
    "key": string;
    "title": string;
    "terminalAt": time$0.Time;
    "tags": string[];
    "featureSlug"?: string;
    "featureEmoji"?: string;
    "prUrl"?: string;

    /** Creates a new ShippedIssueDTO instance. */
    constructor($$source: Partial<ShippedIssueDTO> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("terminalAt" in $$source)) {
            this["terminalAt"] = null;
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShippedIssueDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ShippedIssueDTO {
        const $$createField3_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField3_0($$parsedSource["tags"]);
        }
        return new ShippedIssueDTO($$parsedSource as Partial<ShippedIssueDTO>);
    }
}

/**
 * ShippedListDTO (BACI-221) wraps the popover's per-fetch rows with
 * the total count under the same scope so the popover header can
 * render "showing N of TOTAL" without a second round trip. Mirrors
 * api.ShippedListResponse on the HTTP side; both transports decode to
 * the same shape on the React seam.
 */
export class ShippedListDTO {
    "rows": ShippedIssueDTO[];
    "total": number;

    /** Creates a new ShippedListDTO instance. */
    constructor($$source: Partial<ShippedListDTO> = {}) {
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShippedListDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ShippedListDTO {
        const $$createField0_0 = $$createType38;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField0_0($$parsedSource["rows"]);
        }
        return new ShippedListDTO($$parsedSource as Partial<ShippedListDTO>);
    }
}

/**
 * SyncPreferencesDTO is the BACI-89 background-sync toggle shaped for
 * the desktop Sync view. Mirrors DisplayPreferencesDTO — same single-
 * boolean shape.
 */
export class SyncPreferencesDTO {
    "backgroundEnabled": boolean;

    /** Creates a new SyncPreferencesDTO instance. */
    constructor($$source: Partial<SyncPreferencesDTO> = {}) {
        if (!("backgroundEnabled" in $$source)) {
            this["backgroundEnabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncPreferencesDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncPreferencesDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncPreferencesDTO($$parsedSource as Partial<SyncPreferencesDTO>);
    }
}

/**
 * SyncRegistryDTO is the BACI-108 standalone Sync view payload —
 * camelCase mirror of client.SyncRegistry. Re-shaped here (rather
 * than carried verbatim) so the Wails seam follows the convention
 * every other DTO in this file uses (camelCase JSON tags for the
 * generated TS bindings).
 */
export class SyncRegistryDTO {
    "syncRepos": SyncRepoDTO[];
    "unsyncedProjects": UnsyncedProjectDTO[];

    /** Creates a new SyncRegistryDTO instance. */
    constructor($$source: Partial<SyncRegistryDTO> = {}) {
        if (!("syncRepos" in $$source)) {
            this["syncRepos"] = [];
        }
        if (!("unsyncedProjects" in $$source)) {
            this["unsyncedProjects"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncRegistryDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncRegistryDTO {
        const $$createField0_0 = $$createType40;
        const $$createField1_0 = $$createType42;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("syncRepos" in $$parsedSource) {
            $$parsedSource["syncRepos"] = $$createField0_0($$parsedSource["syncRepos"]);
        }
        if ("unsyncedProjects" in $$parsedSource) {
            $$parsedSource["unsyncedProjects"] = $$createField1_0($$parsedSource["unsyncedProjects"]);
        }
        return new SyncRegistryDTO($$parsedSource as Partial<SyncRegistryDTO>);
    }
}

/**
 * SyncRepoDTO is one entry in the registry.
 */
export class SyncRepoDTO {
    "remoteUrl": string;
    "label": string;
    "localPath": string;
    "clonedAt": string;
    "lastSyncAt"?: string;
    "lastError"?: string;
    "inProgress": boolean;
    "projects": MemberProjectDTO[];

    /** Creates a new SyncRepoDTO instance. */
    constructor($$source: Partial<SyncRepoDTO> = {}) {
        if (!("remoteUrl" in $$source)) {
            this["remoteUrl"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("localPath" in $$source)) {
            this["localPath"] = "";
        }
        if (!("clonedAt" in $$source)) {
            this["clonedAt"] = "";
        }
        if (!("inProgress" in $$source)) {
            this["inProgress"] = false;
        }
        if (!("projects" in $$source)) {
            this["projects"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncRepoDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncRepoDTO {
        const $$createField7_0 = $$createType44;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("projects" in $$parsedSource) {
            $$parsedSource["projects"] = $$createField7_0($$parsedSource["projects"]);
        }
        return new SyncRepoDTO($$parsedSource as Partial<SyncRepoDTO>);
    }
}

/**
 * SyncSetupDTO is the camelCase Wails-side outcome of SetupSync. Two
 * shapes share the struct:
 * 
 *   - Success: `previewCollisions` is nil and the per-mode result
 *     fields (`commitSHA`, `pushed`, `attached` for init / `localPath`,
 *     `remote` for clone / attach) reflect the engine's structured
 *     return. The caller closes the modal and re-fetches the registry.
 *   - Renumber-collision refusal: `previewCollisions` is populated
 *     with the projected renumbers / renames, and the per-mode result
 *     fields stay empty (the engine wrote nothing). The caller switches
 *     to the modal's step-2 confirm and re-submits with
 *     `allowRenumber: true`.
 * 
 * Using a single struct with a nil-vs-populated collision field (rather
 * than an error returned from SetupSync) keeps the typed payload intact
 * across the Wails boundary — Wails marshals errors as strings and
 * drops the DTO when an error is non-nil, so the typed collision shape
 * would round-trip as a plain string. The JS-side seam in api.ts maps
 * a populated `previewCollisions` into the typed SyncSetupCollisionError
 * the modal expects.
 */
export class SyncSetupDTO {
    "mode": string;
    "localPath"?: string;
    "remote"?: string;

    /**
     * Init-only fields.
     */
    "commitSHA"?: string;
    "pushed"?: boolean;
    "attached"?: boolean;

    /**
     * PreviewCollisions is non-nil only on a renumber-collision refusal.
     */
    "previewCollisions"?: CollisionPreviewDTO | null;

    /** Creates a new SyncSetupDTO instance. */
    constructor($$source: Partial<SyncSetupDTO> = {}) {
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncSetupDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncSetupDTO {
        const $$createField6_0 = $$createType46;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("previewCollisions" in $$parsedSource) {
            $$parsedSource["previewCollisions"] = $$createField6_0($$parsedSource["previewCollisions"]);
        }
        return new SyncSetupDTO($$parsedSource as Partial<SyncSetupDTO>);
    }
}

/**
 * UnsyncedProjectDTO mirrors client.UnsyncedProject.
 */
export class UnsyncedProjectDTO {
    "prefix": string;
    "name": string;
    "uuid": string;
    "path": string;

    /** Creates a new UnsyncedProjectDTO instance. */
    constructor($$source: Partial<UnsyncedProjectDTO> = {}) {
        if (!("prefix" in $$source)) {
            this["prefix"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("uuid" in $$source)) {
            this["uuid"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UnsyncedProjectDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): UnsyncedProjectDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UnsyncedProjectDTO($$parsedSource as Partial<UnsyncedProjectDTO>);
    }
}

// Private type creation functions
const $$createType0 = RenumberEntryDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = RenameEntryDTO.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = DocSummaryLinkDTO.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = FeatureLinkedIssue.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = FeatureComment.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = FeatureLinkedDoc.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = FeaturePlanEntry.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $Create.Array($Create.Any);
const $$createType15 = HistoryEntryDTO.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = IssueMetaDTO.createFrom;
const $$createType18 = FeatureRefDTO.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = RelationsDTO.createFrom;
const $$createType21 = PRDTO.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = LinkedDocDTO.createFrom;
const $$createType24 = $Create.Array($$createType23);
const $$createType25 = CommentDTO.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = agentcards$0.ClaimantDTO.createFrom;
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = boardcards$0.WaitingState.createFrom;
const $$createType30 = $Create.Nullable($$createType29);
const $$createType31 = LatestPlanDTO.createFrom;
const $$createType32 = $Create.Nullable($$createType31);
const $$createType33 = DocLinkDTO.createFrom;
const $$createType34 = $Create.Array($$createType33);
const $$createType35 = RelationDTO.createFrom;
const $$createType36 = $Create.Array($$createType35);
const $$createType37 = ShippedIssueDTO.createFrom;
const $$createType38 = $Create.Array($$createType37);
const $$createType39 = SyncRepoDTO.createFrom;
const $$createType40 = $Create.Array($$createType39);
const $$createType41 = UnsyncedProjectDTO.createFrom;
const $$createType42 = $Create.Array($$createType41);
const $$createType43 = MemberProjectDTO.createFrom;
const $$createType44 = $Create.Array($$createType43);
const $$createType45 = CollisionPreviewDTO.createFrom;
const $$createType46 = $Create.Nullable($$createType45);
