// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../time/models.js";

/**
 * AgentCard is one agent session shaped for the desktop Agents screen,
 * carrying its open claims and the dispatches aimed at it so the
 * frontend can render the drill-down without a second round trip.
 */
export class AgentCard {
    "sessionId": string;

    /**
     * identity slug; "" if none
     */
    "agentName": string;
    "actor": string;
    "model": string;
    "branch": string;
    "repoPrefix": string;

    /**
     * active | idle | ended
     */
    "status": string;

    /**
     * Busy is true while the session holds an open claim — orthogonal to
     * Status (a session can be active+busy or idle+busy). BusyIssue is
     * the issue key it's working, for a "busy (BACI-12)" label. A busy
     * session is not a valid dispatch target.
     */
    "busy": boolean;
    "busyIssue": string;
    "lastSeenAt": time$0.Time;
    "claims": ClaimDTO[];
    "dispatches": DispatchDTO[];

    /** Creates a new AgentCard instance. */
    constructor($$source: Partial<AgentCard> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("agentName" in $$source)) {
            this["agentName"] = "";
        }
        if (!("actor" in $$source)) {
            this["actor"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("repoPrefix" in $$source)) {
            this["repoPrefix"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("busy" in $$source)) {
            this["busy"] = false;
        }
        if (!("busyIssue" in $$source)) {
            this["busyIssue"] = "";
        }
        if (!("lastSeenAt" in $$source)) {
            this["lastSeenAt"] = null;
        }
        if (!("claims" in $$source)) {
            this["claims"] = [];
        }
        if (!("dispatches" in $$source)) {
            this["dispatches"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentCard instance from a string or object.
     */
    static createFrom($$source: any = {}): AgentCard {
        const $$createField10_0 = $$createType1;
        const $$createField11_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("claims" in $$parsedSource) {
            $$parsedSource["claims"] = $$createField10_0($$parsedSource["claims"]);
        }
        if ("dispatches" in $$parsedSource) {
            $$parsedSource["dispatches"] = $$createField11_0($$parsedSource["dispatches"]);
        }
        return new AgentCard($$parsedSource as Partial<AgentCard>);
    }
}

/**
 * Board is one bacio repo, offered in the top-nav repository selector.
 */
export class Board {
    "prefix": string;
    "name": string;
    "issueCount": number;
    "syncEnabled": boolean;

    /** Creates a new Board instance. */
    constructor($$source: Partial<Board> = {}) {
        if (!("prefix" in $$source)) {
            this["prefix"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("issueCount" in $$source)) {
            this["issueCount"] = 0;
        }
        if (!("syncEnabled" in $$source)) {
            this["syncEnabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Board instance from a string or object.
     */
    static createFrom($$source: any = {}): Board {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Board($$parsedSource as Partial<Board>);
    }
}

/**
 * BoardCard is a kanban card — one bacio issue, shaped for the imported UI kit.
 */
export class BoardCard {
    "key": string;
    "column": string;
    "columnLabel": string;
    "title": string;
    "tags": string[];
    "assignees": string[];
    "claude": boolean;

    /** Creates a new BoardCard instance. */
    constructor($$source: Partial<BoardCard> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("column" in $$source)) {
            this["column"] = "";
        }
        if (!("columnLabel" in $$source)) {
            this["columnLabel"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("assignees" in $$source)) {
            this["assignees"] = [];
        }
        if (!("claude" in $$source)) {
            this["claude"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BoardCard instance from a string or object.
     */
    static createFrom($$source: any = {}): BoardCard {
        const $$createField4_0 = $$createType4;
        const $$createField5_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        if ("assignees" in $$parsedSource) {
            $$parsedSource["assignees"] = $$createField5_0($$parsedSource["assignees"]);
        }
        return new BoardCard($$parsedSource as Partial<BoardCard>);
    }
}

/**
 * BoardColumn is one kanban column — one bacio issue state.
 */
export class BoardColumn {
    "state": string;
    "label": string;

    /** Creates a new BoardColumn instance. */
    constructor($$source: Partial<BoardColumn> = {}) {
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BoardColumn instance from a string or object.
     */
    static createFrom($$source: any = {}): BoardColumn {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BoardColumn($$parsedSource as Partial<BoardColumn>);
    }
}

/**
 * ClaimDTO is one open agent claim, shaped for the Agents screen.
 */
export class ClaimDTO {
    "issueKey": string;
    "prompt": string;
    "claimedAt": time$0.Time;

    /** Creates a new ClaimDTO instance. */
    constructor($$source: Partial<ClaimDTO> = {}) {
        if (!("issueKey" in $$source)) {
            this["issueKey"] = "";
        }
        if (!("prompt" in $$source)) {
            this["prompt"] = "";
        }
        if (!("claimedAt" in $$source)) {
            this["claimedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClaimDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ClaimDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClaimDTO($$parsedSource as Partial<ClaimDTO>);
    }
}

/**
 * ClaimantDTO is one entry in an issue's claim history — a session that
 * has claimed the issue, with the prompt it ran and whether the claim
 * is still open.
 */
export class ClaimantDTO {
    "sessionId": string;
    "agentName": string;
    "prompt": string;
    "claimedAt": time$0.Time;
    "releasedAt": time$0.Time | null;
    "open": boolean;

    /** Creates a new ClaimantDTO instance. */
    constructor($$source: Partial<ClaimantDTO> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("agentName" in $$source)) {
            this["agentName"] = "";
        }
        if (!("prompt" in $$source)) {
            this["prompt"] = "";
        }
        if (!("claimedAt" in $$source)) {
            this["claimedAt"] = null;
        }
        if (!("releasedAt" in $$source)) {
            this["releasedAt"] = null;
        }
        if (!("open" in $$source)) {
            this["open"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClaimantDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ClaimantDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClaimantDTO($$parsedSource as Partial<ClaimantDTO>);
    }
}

/**
 * CommentDTO is one issue comment.
 */
export class CommentDTO {
    "author": string;
    "body": string;
    "createdAt": time$0.Time;

    /** Creates a new CommentDTO instance. */
    constructor($$source: Partial<CommentDTO> = {}) {
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommentDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): CommentDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommentDTO($$parsedSource as Partial<CommentDTO>);
    }
}

/**
 * DispatchDTO is one queued dispatch — returned both inside an AgentCard
 * (the agent's drill-down) and from DispatchIssue (the new write).
 */
export class DispatchDTO {
    "id": number;
    "issueKey": string;
    "targetAgent": string;
    "mode": string;
    "status": string;
    "payload": string;
    "createdBy": string;
    "createdAt": time$0.Time;

    /** Creates a new DispatchDTO instance. */
    constructor($$source: Partial<DispatchDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("issueKey" in $$source)) {
            this["issueKey"] = "";
        }
        if (!("targetAgent" in $$source)) {
            this["targetAgent"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("payload" in $$source)) {
            this["payload"] = "";
        }
        if (!("createdBy" in $$source)) {
            this["createdBy"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DispatchDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): DispatchDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DispatchDTO($$parsedSource as Partial<DispatchDTO>);
    }
}

/**
 * DocContent is one document with its markdown body, for the editor pane.
 */
export class DocContent {
    "filename": string;
    "type": string;
    "content": string;
    "updatedAt": time$0.Time;

    /** Creates a new DocContent instance. */
    constructor($$source: Partial<DocContent> = {}) {
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocContent instance from a string or object.
     */
    static createFrom($$source: any = {}): DocContent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DocContent($$parsedSource as Partial<DocContent>);
    }
}

/**
 * DocLinkDTO is one document linked to an issue, shaped for the drawer's
 * attachments section.
 */
export class DocLinkDTO {
    "filename": string;
    "type": string;

    /**
     * the link's --why reason
     */
    "description": string;

    /** Creates a new DocLinkDTO instance. */
    constructor($$source: Partial<DocLinkDTO> = {}) {
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocLinkDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): DocLinkDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DocLinkDTO($$parsedSource as Partial<DocLinkDTO>);
    }
}

/**
 * DocSummary is one document, shaped for the desktop document list.
 */
export class DocSummary {
    "filename": string;
    "type": string;
    "sizeBytes": number;
    "updatedAt": time$0.Time;

    /** Creates a new DocSummary instance. */
    constructor($$source: Partial<DocSummary> = {}) {
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("sizeBytes" in $$source)) {
            this["sizeBytes"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): DocSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DocSummary($$parsedSource as Partial<DocSummary>);
    }
}

/**
 * FeatureDetail is one feature with its description and linked issues — the
 * payload for the desktop feature detail pane.
 */
export class FeatureDetail {
    "slug": string;
    "title": string;
    "description": string;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;
    "issues": FeatureLinkedIssue[];

    /** Creates a new FeatureDetail instance. */
    constructor($$source: Partial<FeatureDetail> = {}) {
        if (!("slug" in $$source)) {
            this["slug"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }
        if (!("issues" in $$source)) {
            this["issues"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FeatureDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): FeatureDetail {
        const $$createField5_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("issues" in $$parsedSource) {
            $$parsedSource["issues"] = $$createField5_0($$parsedSource["issues"]);
        }
        return new FeatureDetail($$parsedSource as Partial<FeatureDetail>);
    }
}

/**
 * FeatureLinkedIssue is one issue grouped under a feature, for the detail pane.
 */
export class FeatureLinkedIssue {
    "key": string;
    "title": string;
    "state": string;
    "stateLabel": string;

    /** Creates a new FeatureLinkedIssue instance. */
    constructor($$source: Partial<FeatureLinkedIssue> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("stateLabel" in $$source)) {
            this["stateLabel"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FeatureLinkedIssue instance from a string or object.
     */
    static createFrom($$source: any = {}): FeatureLinkedIssue {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FeatureLinkedIssue($$parsedSource as Partial<FeatureLinkedIssue>);
    }
}

/**
 * FeatureSummary is one feature, shaped for the desktop feature list.
 */
export class FeatureSummary {
    "slug": string;
    "title": string;
    "updatedAt": time$0.Time;

    /** Creates a new FeatureSummary instance. */
    constructor($$source: Partial<FeatureSummary> = {}) {
        if (!("slug" in $$source)) {
            this["slug"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FeatureSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): FeatureSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FeatureSummary($$parsedSource as Partial<FeatureSummary>);
    }
}

/**
 * HistoryEntryDTO is one audit-log row, shaped for the desktop history table.
 */
export class HistoryEntryDTO {
    "id": number;
    "actor": string;
    "op": string;
    "kind": string;
    "targetLabel": string;
    "details": string;
    "createdAt": time$0.Time;

    /** Creates a new HistoryEntryDTO instance. */
    constructor($$source: Partial<HistoryEntryDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("actor" in $$source)) {
            this["actor"] = "";
        }
        if (!("op" in $$source)) {
            this["op"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("targetLabel" in $$source)) {
            this["targetLabel"] = "";
        }
        if (!("details" in $$source)) {
            this["details"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryEntryDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryEntryDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryEntryDTO($$parsedSource as Partial<HistoryEntryDTO>);
    }
}

/**
 * HistoryPage is one page of the audit log. Page is 0-based; HasMore reports
 * whether a further page exists, so the frontend can drive Prev/Next without a
 * separate total-count query.
 */
export class HistoryPage {
    "entries": HistoryEntryDTO[];
    "page": number;
    "pageSize": number;
    "hasMore": boolean;

    /** Creates a new HistoryPage instance. */
    constructor($$source: Partial<HistoryPage> = {}) {
        if (!("entries" in $$source)) {
            this["entries"] = [];
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            this["pageSize"] = 0;
        }
        if (!("hasMore" in $$source)) {
            this["hasMore"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryPage instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryPage {
        const $$createField0_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField0_0($$parsedSource["entries"]);
        }
        return new HistoryPage($$parsedSource as Partial<HistoryPage>);
    }
}

/**
 * IssueDetail is the issue-drawer payload for a single issue.
 */
export class IssueDetail {
    "key": string;
    "column": string;
    "columnLabel": string;
    "title": string;
    "description": string;
    "tags": string[];
    "assignees": string[];
    "claude": boolean;
    "comments": CommentDTO[];
    "pullRequests": PRDTO[];
    "documents": DocLinkDTO[];
    "claimants": ClaimantDTO[];

    /**
     * Taken is the derived "an agent is actively holding this" signal —
     * true iff Claimants has an open (unreleased) claim.
     */
    "taken": boolean;

    /** Creates a new IssueDetail instance. */
    constructor($$source: Partial<IssueDetail> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("column" in $$source)) {
            this["column"] = "";
        }
        if (!("columnLabel" in $$source)) {
            this["columnLabel"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("assignees" in $$source)) {
            this["assignees"] = [];
        }
        if (!("claude" in $$source)) {
            this["claude"] = false;
        }
        if (!("comments" in $$source)) {
            this["comments"] = [];
        }
        if (!("pullRequests" in $$source)) {
            this["pullRequests"] = [];
        }
        if (!("documents" in $$source)) {
            this["documents"] = [];
        }
        if (!("claimants" in $$source)) {
            this["claimants"] = [];
        }
        if (!("taken" in $$source)) {
            this["taken"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IssueDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): IssueDetail {
        const $$createField5_0 = $$createType4;
        const $$createField6_0 = $$createType4;
        const $$createField8_0 = $$createType10;
        const $$createField9_0 = $$createType12;
        const $$createField10_0 = $$createType14;
        const $$createField11_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField5_0($$parsedSource["tags"]);
        }
        if ("assignees" in $$parsedSource) {
            $$parsedSource["assignees"] = $$createField6_0($$parsedSource["assignees"]);
        }
        if ("comments" in $$parsedSource) {
            $$parsedSource["comments"] = $$createField8_0($$parsedSource["comments"]);
        }
        if ("pullRequests" in $$parsedSource) {
            $$parsedSource["pullRequests"] = $$createField9_0($$parsedSource["pullRequests"]);
        }
        if ("documents" in $$parsedSource) {
            $$parsedSource["documents"] = $$createField10_0($$parsedSource["documents"]);
        }
        if ("claimants" in $$parsedSource) {
            $$parsedSource["claimants"] = $$createField11_0($$parsedSource["claimants"]);
        }
        return new IssueDetail($$parsedSource as Partial<IssueDetail>);
    }
}

/**
 * PRDTO is one attached pull request.
 */
export class PRDTO {
    "url": string;

    /** Creates a new PRDTO instance. */
    constructor($$source: Partial<PRDTO> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PRDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): PRDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PRDTO($$parsedSource as Partial<PRDTO>);
    }
}

/**
 * PromptTemplateDTO is one editable dispatch prompt template, shaped for
 * the desktop Settings panel. Body is the effective template (the user's
 * custom override, or Default when none is set); IsDefault reports
 * whether Body still matches the built-in default. AllowedStates is the
 * effective state-gate — the issue states this stage's prompt is valid
 * to run from — with DefaultStates the built-in set and StatesAreDefault
 * whether AllowedStates still matches it.
 */
export class PromptTemplateDTO {
    "mode": string;
    "label": string;
    "body": string;
    "default": string;
    "isDefault": boolean;
    "allowedStates": string[];
    "defaultStates": string[];
    "statesAreDefault": boolean;

    /** Creates a new PromptTemplateDTO instance. */
    constructor($$source: Partial<PromptTemplateDTO> = {}) {
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("default" in $$source)) {
            this["default"] = "";
        }
        if (!("isDefault" in $$source)) {
            this["isDefault"] = false;
        }
        if (!("allowedStates" in $$source)) {
            this["allowedStates"] = [];
        }
        if (!("defaultStates" in $$source)) {
            this["defaultStates"] = [];
        }
        if (!("statesAreDefault" in $$source)) {
            this["statesAreDefault"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PromptTemplateDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): PromptTemplateDTO {
        const $$createField5_0 = $$createType4;
        const $$createField6_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("allowedStates" in $$parsedSource) {
            $$parsedSource["allowedStates"] = $$createField5_0($$parsedSource["allowedStates"]);
        }
        if ("defaultStates" in $$parsedSource) {
            $$parsedSource["defaultStates"] = $$createField6_0($$parsedSource["defaultStates"]);
        }
        return new PromptTemplateDTO($$parsedSource as Partial<PromptTemplateDTO>);
    }
}

// Private type creation functions
const $$createType0 = ClaimDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = DispatchDTO.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = FeatureLinkedIssue.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = HistoryEntryDTO.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = CommentDTO.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = PRDTO.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = DocLinkDTO.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = ClaimantDTO.createFrom;
const $$createType16 = $Create.Array($$createType15);
