// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MonitorService is the Wails-bound proxy-capture API the desktop Monitor
 * screen talks to. It wraps a local bacio client.Client and serves the
 * BACI-303 per-FQDN rollup of proxy_requests. Read-only. The
 * proxy_requests table is cross-cutting (no repo_id), so — unlike
 * HistoryService — there is no repo prefix: the stats are global.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ProxyStats returns the per-FQDN proxy-traffic rollup, busiest host
 * first (the order the store already returns). sinceDays > 0 windows the
 * rollup to a rolling lookback of that many days; sinceDays == 0 means
 * all-time (no lower bound) — the same 0-sentinel convention the Shipped
 * scope picker uses. The returned slice is always non-nil so the
 * frontend can map over it unconditionally.
 */
export function ProxyStats(sinceDays: number): $CancellablePromise<$models.ProxyFQDNStatDTO[]> {
    return $Call.ByID(56970572, sinceDays).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ProxyFQDNStatDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
