// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MonitorService is the Wails-bound proxy-capture API the desktop Monitor
 * screen talks to. It wraps a local bacio client.Client and serves the
 * BACI-303 per-FQDN rollup of proxy_requests. Read-only. The
 * proxy_requests table is cross-cutting (no repo_id), so — unlike
 * HistoryService — there is no repo prefix: the stats are global.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../internal/model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Capture returns the BACI-306 parsed detail of one captured Anthropic SSE
 * turn (proxy_messages row), keyed on the proxy_requests id. Errors when the
 * capture wasn't parseable. The snake_case model.ProxyMessage shape is aligned
 * to the React transcript types, so the binding returns it directly.
 */
export function Capture(id: number): $CancellablePromise<model$0.ProxyMessage | null> {
    return $Call.ByID(2490313523, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CaptureRaw returns the raw, auth-redacted .http capture text for one
 * proxy_requests id — the escape hatch the sheet falls back to for a capture
 * that isn't a parseable Anthropic turn. Errors (surfaced to the frontend)
 * when the row has no raw file or it's been pruned.
 */
export function CaptureRaw(id: number): $CancellablePromise<string> {
    return $Call.ByID(2488914227, id);
}

/**
 * JobTranscript returns the BACI-306 assembled per-job transcript for a
 * dispatch — the ordered primary-thread messages, summed usage, and auxiliary
 * turns. Errors when the dispatch has no parsed captures. The snake_case
 * model.AnthropicTranscript shape is aligned to the React transcript types, so
 * the adapter consumes it directly.
 */
export function JobTranscript(dispatchID: number): $CancellablePromise<model$0.AnthropicTranscript | null> {
    return $Call.ByID(611803632, dispatchID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ListCaptures returns the BACI-308 filtered capture list the Monitor sheet
 * walks an FQDN row down into — newest-first, capped, each row enriched with
 * its dispatch's issue-key + mode. host scopes to one upstream; dispatchID > 0
 * scopes to one job; anthropicOnly keeps only the parseable message-API
 * captures; sinceDays > 0 windows to a rolling lookback (0 = all-time, the same
 * sentinel ProxyStats uses). The returned slice is always non-nil.
 */
export function ListCaptures(host: string, dispatchID: number, anthropicOnly: boolean, sinceDays: number): $CancellablePromise<$models.ProxyCaptureRowDTO[]> {
    return $Call.ByID(3129455208, host, dispatchID, anthropicOnly, sinceDays).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ListJobTranscripts returns the BACI-322 transcript browser list — one row per
 * distinct dispatch that has parsed captures, the Monitor Transcript page's
 * data. repo scopes to one repo prefix (the active board); issue / mode narrow
 * to one issue / one job mode; session / agent (BACI-348) narrow to one
 * supervisor session / one subagent identity; sinceDays > 0 windows to a
 * rolling lookback (0 = all-time, the same sentinel ProxyStats uses). The
 * returned slice is always non-nil.
 */
export function ListJobTranscripts(repo: string, issue: string, mode: string, session: string, agent: string, sinceDays: number): $CancellablePromise<$models.JobTranscriptRowDTO[]> {
    return $Call.ByID(2401896545, repo, issue, mode, session, agent, sinceDays).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * ProxyStats returns the per-FQDN proxy-traffic rollup, busiest host
 * first (the order the store already returns). sinceDays > 0 windows the
 * rollup to a rolling lookback of that many days; sinceDays == 0 means
 * all-time (no lower bound) — the same 0-sentinel convention the Shipped
 * scope picker uses. The returned slice is always non-nil so the
 * frontend can map over it unconditionally.
 */
export function ProxyStats(sinceDays: number): $CancellablePromise<$models.ProxyFQDNStatDTO[]> {
    return $Call.ByID(56970572, sinceDays).then(($result: any) => {
        return $$createType9($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.ProxyMessage.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.AnthropicTranscript.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.ProxyCaptureRowDTO.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.JobTranscriptRowDTO.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $models.ProxyFQDNStatDTO.createFrom;
const $$createType9 = $Create.Array($$createType8);
