// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService is the Wails-bound API for the desktop Settings panel.
 * It owns the customisable dispatch prompt templates (arbitrary in
 * count and shape — see BACI-31) plus the display / archive / sync
 * preference pairs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddPromptTemplate creates a brand-new template. actionLabel is the
 * BACI-67 imperative override rendered on the dispatch action menus;
 * pass "" to skip the override (the UI derives one from name).
 */
export function AddPromptTemplate(slug: string, name: string, body: string, actionLabel: string): $CancellablePromise<$models.PromptTemplateDTO> {
    return $Call.ByID(2314996611, slug, name, body, actionLabel).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * BacioVersion returns the version string of the bacio binary the
 * desktop app is currently running. Surfaced on the Settings panel so
 * you can cross-check what the desktop client is running against the
 * per-session "Bacio version" the Agents panel shows.
 */
export function BacioVersion(): $CancellablePromise<string> {
    return $Call.ByID(2314822586);
}

/**
 * DeletePromptTemplate removes a template by slug. The historical
 * dispatches that reference the slug are left intact (a dispatch is a
 * snapshot, not a live foreign key) — use RestoreBuiltinPromptTemplates
 * to re-seed a deleted built-in.
 */
export function DeletePromptTemplate(slug: string): $CancellablePromise<$models.PromptTemplateDTO> {
    return $Call.ByID(2109861811, slug).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetArchivePreferences returns the current BACI-162 auto-archive
 * settings. The desktop Settings panel renders the pair on mount and
 * after every flip / numeric change so the UI stays consistent with
 * the persisted row.
 */
export function GetArchivePreferences(): $CancellablePromise<$models.ArchivePreferencesDTO> {
    return $Call.ByID(799256876).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetAudioPreferences returns the current ui.shipped_sfx value
 * (BACI-240). The Pipeline Shipping column's Shipped pill consults this
 * to gate the ka-ching SFX on a genuine ship.
 */
export function GetAudioPreferences(): $CancellablePromise<$models.AudioPreferencesDTO> {
    return $Call.ByID(1490774688).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetDisplayPreferences returns the current display.show_archived
 * value (BACI-68). The desktop Board / Docs / Features views consult
 * this on every refresh — when on, archived rows surface as visibly-
 * muted cards; when off they're hidden entirely.
 */
export function GetDisplayPreferences(): $CancellablePromise<$models.DisplayPreferencesDTO> {
    return $Call.ByID(4223916732).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetSyncPreferences returns the current sync.background_enabled
 * value. Backed by the same client.GetSyncBackgroundEnabled path the
 * CLI and HTTP surfaces use.
 */
export function GetSyncPreferences(): $CancellablePromise<$models.SyncPreferencesDTO> {
    return $Call.ByID(3481112815).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetSyncRegistry returns the registry of sync repos this machine
 * knows plus the tracked project repos that aren't yet attached. Backs
 * the BACI-108 standalone Sync view on desktop. The same payload ships
 * over the wire on `bacio web` via GET /sync/repos.
 */
export function GetSyncRegistry(): $CancellablePromise<$models.SyncRegistryDTO> {
    return $Call.ByID(3389817124).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * LinkPhantomRepo (BACI-112) is the Wails-side entry point for the
 * desktop / web PhantomLinkModal. Thin shim over
 * client.LinkPhantomRepo. dryRun is not exposed on the UI side; if a
 * future "rehearse" affordance is wanted it can pass the bool through.
 * On a typed-error refusal (client.RepoLinkError) the human message is
 * returned verbatim so the modal can render it inline — the kind
 * classification isn't exposed across the Wails bridge today; the modal
 * just renders the message.
 */
export function LinkPhantomRepo(prefix: string, path: string): $CancellablePromise<$models.RepoLinkResultDTO> {
    return $Call.ByID(3604398369, prefix, path).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * ListPromptTemplates returns every registered template in store
 * iteration order — the desktop Settings panel renders them in this
 * order and the per-card action menu in the Board iterates the same
 * list (with reserved-slug filtering applied on the React seam).
 */
export function ListPromptTemplates(): $CancellablePromise<$models.PromptTemplateDTO[]> {
    return $Call.ByID(1001854565).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * PromptPlaceholders returns the placeholder tokens a template body can
 * interpolate (e.g. "issue_id"), so the Settings UI can show them next
 * to the editors. The tokens are wrapped in {{...}} when substituted.
 */
export function PromptPlaceholders(): $CancellablePromise<string[]> {
    return $Call.ByID(1135988516).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * RenamePromptTemplate renames an existing template — either the slug,
 * the display name, or both.
 */
export function RenamePromptTemplate(slug: string, newSlug: string, newName: string): $CancellablePromise<$models.PromptTemplateDTO> {
    return $Call.ByID(1528694734, slug, newSlug, newName).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * RestoreBuiltinPromptTemplates re-seeds any built-in slug that doesn't
 * currently have a row from the embedded defaults. Idempotent. Returns
 * the refreshed full template list so the frontend can update its
 * `templates` state in one shot.
 */
export function RestoreBuiltinPromptTemplates(): $CancellablePromise<$models.PromptTemplateDTO[]> {
    return $Call.ByID(3843909418).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * SavePromptActionLabel (BACI-67) updates a template's imperative
 * override — the verb the dispatch action menus render. An empty
 * actionLabel clears the override (the UI then derives from Name via
 * the gerund→imperative rule).
 */
export function SavePromptActionLabel(slug: string, actionLabel: string): $CancellablePromise<$models.PromptTemplateDTO> {
    return $Call.ByID(2418293349, slug, actionLabel).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SavePromptConcurrency (BACI-51) sets a template's per-(repo, slug)
 * in-flight dispatch cap the matcher enforces. 0 = unlimited.
 */
export function SavePromptConcurrency(slug: string, concurrencyLimit: number): $CancellablePromise<$models.PromptTemplateDTO> {
    return $Call.ByID(1315581830, slug, concurrencyLimit).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SavePromptTemplate stores a new body for one template slug. An empty
 * body reverts a built-in to its embedded default (and is a no-op
 * edit for a user-created template).
 */
export function SavePromptTemplate(slug: string, body: string): $CancellablePromise<$models.PromptTemplateDTO> {
    return $Call.ByID(898182437, slug, body).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetArchivePreferences writes both BACI-162 keys atomically and
 * returns the refreshed DTO. The client records the audit row.
 */
export function SetArchivePreferences(autoEnabled: boolean, retentionDays: number): $CancellablePromise<$models.ArchivePreferencesDTO> {
    return $Call.ByID(3981288536, autoEnabled, retentionDays).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SetAudioPreferences writes ui.shipped_sfx and returns the refreshed
 * DTO (BACI-240). The client records the audit row.
 */
export function SetAudioPreferences(shippedSfx: boolean): $CancellablePromise<$models.AudioPreferencesDTO> {
    return $Call.ByID(2147790516, shippedSfx).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SetDisplayPreferences writes display.show_archived and returns the
 * refreshed DTO (BACI-68).
 */
export function SetDisplayPreferences(showArchived: boolean): $CancellablePromise<$models.DisplayPreferencesDTO> {
    return $Call.ByID(1804218376, showArchived).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * SetSyncPreferences flips sync.background_enabled and returns the
 * refreshed DTO. The client records the audit row.
 */
export function SetSyncPreferences(backgroundEnabled: boolean): $CancellablePromise<$models.SyncPreferencesDTO> {
    return $Call.ByID(2076274475, backgroundEnabled).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * SetupSync sets up sync for the project repo identified by prefix.
 * Three modes — "init", "clone", "attach" — mirror the HTTP layer
 * (POST /repos/{prefix}/sync/setup). On a renumber-collision refusal
 * the returned DTO carries PreviewCollisions (non-nil) and the error
 * is nil; the JS-side seam maps that into a typed
 * SyncSetupCollisionError the modal branches on. Any other failure
 * (validation / engine error / lock timeout) surfaces as a non-nil
 * error and PreviewCollisions stays nil.
 */
export function SetupSync(prefix: string, $in: $models.SetupSyncIn): $CancellablePromise<$models.SyncSetupDTO> {
    return $Call.ByID(3158355382, prefix, $in).then(($result: any) => {
        return $$createType9($result);
    });
}

// Private type creation functions
const $$createType0 = $models.PromptTemplateDTO.createFrom;
const $$createType1 = $models.ArchivePreferencesDTO.createFrom;
const $$createType2 = $models.AudioPreferencesDTO.createFrom;
const $$createType3 = $models.DisplayPreferencesDTO.createFrom;
const $$createType4 = $models.SyncPreferencesDTO.createFrom;
const $$createType5 = $models.SyncRegistryDTO.createFrom;
const $$createType6 = $models.RepoLinkResultDTO.createFrom;
const $$createType7 = $Create.Array($$createType0);
const $$createType8 = $Create.Array($Create.Any);
const $$createType9 = $models.SyncSetupDTO.createFrom;
