// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService is the Wails-bound API for the desktop Settings panel.
 * Today it owns the customisable dispatch prompt templates; it wraps the
 * same local bacio client.Client as the rest of the app.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ListPromptTemplates returns the five dispatch prompt templates in
 * lifecycle order, each with its effective body, the built-in default,
 * and whether the body still matches that default.
 */
export function ListPromptTemplates(): $CancellablePromise<$models.PromptTemplateDTO[]> {
    return $Call.ByID(1001854565).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * PromptPlaceholders returns the placeholder tokens a template body can
 * interpolate (e.g. "issue_id"), so the Settings UI can show them next
 * to the editors. The tokens are wrapped in {{...}} when substituted.
 */
export function PromptPlaceholders(): $CancellablePromise<string[]> {
    return $Call.ByID(1135988516).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SavePromptTemplate stores a custom body for one dispatch stage and
 * returns the refreshed DTO. An empty body resets the stage to its
 * built-in default.
 */
export function SavePromptTemplate(mode: string, body: string): $CancellablePromise<$models.PromptTemplateDTO> {
    return $Call.ByID(898182437, mode, body).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.PromptTemplateDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
