// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService is the Wails-bound API for the desktop Settings panel.
 * Today it owns the customisable dispatch prompt templates; it wraps the
 * same local bacio client.Client as the rest of the app.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BacioVersion returns the version string of the bacio binary the
 * desktop app is currently running. Surfaced on the Settings panel so
 * you can cross-check what the desktop client is running against the
 * per-session "Bacio version" the Agents panel shows — easy way to
 * spot "is this agent's channel an older build than my desktop?".
 * Sources from version.String() so plain `go build` dev binaries get
 * commit-level resolution (e.g. "dev (commit abc1234)").
 */
export function BacioVersion(): $CancellablePromise<string> {
    return $Call.ByID(2314822586);
}

/**
 * GetBoardPreferences returns the persisted desktop Board UI
 * preferences (or the built-in defaults when none are stored).
 */
export function GetBoardPreferences(): $CancellablePromise<$models.BoardPreferencesDTO> {
    return $Call.ByID(749217122).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListPromptTemplates returns the five dispatch prompt templates in
 * lifecycle order, each with its effective body, the built-in default,
 * the effective + default state-gate, and whether each still matches
 * its built-in default.
 */
export function ListPromptTemplates(): $CancellablePromise<$models.PromptTemplateDTO[]> {
    return $Call.ByID(1001854565).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * PromptPlaceholders returns the placeholder tokens a template body can
 * interpolate (e.g. "issue_id"), so the Settings UI can show them next
 * to the editors. The tokens are wrapped in {{...}} when substituted.
 */
export function PromptPlaceholders(): $CancellablePromise<string[]> {
    return $Call.ByID(1135988516).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * SavePromptStates stores a custom state-gate for one dispatch stage —
 * the set of issue states the stage's prompt is valid to run from — and
 * returns the refreshed DTO. An empty slice resets the stage to its
 * built-in default gate.
 */
export function SavePromptStates(mode: string, states: string[]): $CancellablePromise<$models.PromptTemplateDTO> {
    return $Call.ByID(1803653057, mode, states).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SavePromptTemplate stores a custom body for one dispatch stage and
 * returns the refreshed DTO. An empty body resets the stage to its
 * built-in default.
 */
export function SavePromptTemplate(mode: string, body: string): $CancellablePromise<$models.PromptTemplateDTO> {
    return $Call.ByID(898182437, mode, body).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SetBoardPreferences stores the desktop Board's hide-empty-columns
 * preference and returns the refreshed DTO — same "save returns the
 * refreshed DTO" shape as SavePromptTemplate.
 */
export function SetBoardPreferences(hideEmptyColumns: boolean): $CancellablePromise<$models.BoardPreferencesDTO> {
    return $Call.ByID(3601263486, hideEmptyColumns).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.BoardPreferencesDTO.createFrom;
const $$createType1 = $models.PromptTemplateDTO.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
