// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * AgentCard is one agent session shaped for the Agents screen, carrying
 * its open claims and the dispatches aimed at it so the frontend can
 * render the drill-down without a second round trip.
 * 
 * Field tags match the desktop's pre-BACI-50 wire format so the web
 * bundle's TS AgentCard type (in api.http.ts) is structurally
 * identical to the desktop's generated binding.
 */
export class AgentCard {
    "sessionId": string;
    "agentName": string;
    "actor": string;
    "model": string;
    "branch": string;
    "repoPrefix": string;
    "status": string;

    /**
     * ErrorType / ErrorMessage carry the Anthropic API failure that put a
     * session into the "errored" Status (BACI-296). Empty for every other
     * status; surfaced as the errored pill's tooltip in the Agents view.
     */
    "errorType"?: string;
    "errorMessage"?: string;

    /**
     * Busy is true while the session holds an open claim — orthogonal to
     * Status (a session can be active+busy or idle+busy). BusyIssue is
     * the issue key it's working, for a "busy (BACI-12)" label. A busy
     * session is not a valid dispatch target.
     */
    "busy": boolean;
    "busyIssue": string;

    /**
     * HasChannel is true when the bacio channel MCP server has been seen
     * running alongside this session. Only sessions with a live channel
     * can receive push dispatches — sessions without one are interactive
     * (the user hasn't granted channel permission) and should be skipped.
     */
    "hasChannel": boolean;
    "bacioVersion": string;
    "bacioVersionStale": boolean;
    "lastSeenAt": time$0.Time;
    "claims": ClaimDTO[];
    "dispatches": DispatchDTO[];

    /**
     * Todos mirrors the agent's TodoWrite list (BACI-45). TodosDone /
     * TodosTotal are pre-computed server-side so the UI doesn't reduce
     * the array twice per render.
     */
    "todos": SessionTodoDTO[];
    "todosDone": number;
    "todosTotal": number;

    /**
     * OpenQuestions are the BACI-53 ask_user_question rows the agent
     * posed and the user hasn't answered or dismissed yet. Drives the
     * "user input needed" badge and modal trigger in the Agents view.
     */
    "openQuestions": QuestionDTO[];

    /** Creates a new AgentCard instance. */
    constructor($$source: Partial<AgentCard> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("agentName" in $$source)) {
            this["agentName"] = "";
        }
        if (!("actor" in $$source)) {
            this["actor"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("repoPrefix" in $$source)) {
            this["repoPrefix"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("busy" in $$source)) {
            this["busy"] = false;
        }
        if (!("busyIssue" in $$source)) {
            this["busyIssue"] = "";
        }
        if (!("hasChannel" in $$source)) {
            this["hasChannel"] = false;
        }
        if (!("bacioVersion" in $$source)) {
            this["bacioVersion"] = "";
        }
        if (!("bacioVersionStale" in $$source)) {
            this["bacioVersionStale"] = false;
        }
        if (!("lastSeenAt" in $$source)) {
            this["lastSeenAt"] = null;
        }
        if (!("claims" in $$source)) {
            this["claims"] = [];
        }
        if (!("dispatches" in $$source)) {
            this["dispatches"] = [];
        }
        if (!("todos" in $$source)) {
            this["todos"] = [];
        }
        if (!("todosDone" in $$source)) {
            this["todosDone"] = 0;
        }
        if (!("todosTotal" in $$source)) {
            this["todosTotal"] = 0;
        }
        if (!("openQuestions" in $$source)) {
            this["openQuestions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentCard instance from a string or object.
     */
    static createFrom($$source: any = {}): AgentCard {
        const $$createField15_0 = $$createType1;
        const $$createField16_0 = $$createType3;
        const $$createField17_0 = $$createType5;
        const $$createField20_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("claims" in $$parsedSource) {
            $$parsedSource["claims"] = $$createField15_0($$parsedSource["claims"]);
        }
        if ("dispatches" in $$parsedSource) {
            $$parsedSource["dispatches"] = $$createField16_0($$parsedSource["dispatches"]);
        }
        if ("todos" in $$parsedSource) {
            $$parsedSource["todos"] = $$createField17_0($$parsedSource["todos"]);
        }
        if ("openQuestions" in $$parsedSource) {
            $$parsedSource["openQuestions"] = $$createField20_0($$parsedSource["openQuestions"]);
        }
        return new AgentCard($$parsedSource as Partial<AgentCard>);
    }
}

/**
 * ClaimDTO is one open agent claim, shaped for the Agents screen.
 * State is the claimed issue's current state — annotates each claim in
 * the drill-down (e.g. "BACI-12 (in review)").
 */
export class ClaimDTO {
    "issueKey": string;
    "prompt": string;
    "claimedAt": time$0.Time;
    "state": string;

    /** Creates a new ClaimDTO instance. */
    constructor($$source: Partial<ClaimDTO> = {}) {
        if (!("issueKey" in $$source)) {
            this["issueKey"] = "";
        }
        if (!("prompt" in $$source)) {
            this["prompt"] = "";
        }
        if (!("claimedAt" in $$source)) {
            this["claimedAt"] = null;
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClaimDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ClaimDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClaimDTO($$parsedSource as Partial<ClaimDTO>);
    }
}

/**
 * ClaimantDTO is the per-issue claim-history entry the desktop's
 * IssueDetail surfaces. CamelCase JSON tags match the rest of the
 * agentcards DTOs (BACI-50). Open is the derived
 * model.AnyOpenClaim-style flag for a single row — true iff ReleasedAt
 * is nil.
 */
export class ClaimantDTO {
    "sessionId": string;
    "agentName": string;
    "prompt": string;
    "claimedAt": time$0.Time;
    "releasedAt": time$0.Time | null;
    "open": boolean;

    /** Creates a new ClaimantDTO instance. */
    constructor($$source: Partial<ClaimantDTO> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("agentName" in $$source)) {
            this["agentName"] = "";
        }
        if (!("prompt" in $$source)) {
            this["prompt"] = "";
        }
        if (!("claimedAt" in $$source)) {
            this["claimedAt"] = null;
        }
        if (!("releasedAt" in $$source)) {
            this["releasedAt"] = null;
        }
        if (!("open" in $$source)) {
            this["open"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClaimantDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ClaimantDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClaimantDTO($$parsedSource as Partial<ClaimantDTO>);
    }
}

/**
 * DispatchDTO is one queued dispatch — included inside an AgentCard
 * (the agent's drill-down).
 */
export class DispatchDTO {
    "id": number;
    "issueKey": string;
    "targetAgent": string;
    "mode": string;
    "status": string;
    "payload": string;
    "createdBy": string;
    "createdAt": time$0.Time;

    /**
     * NeedsRescue (BACI-190) is true when the dispatch's target
     * session has ended without the dispatch ever being acked — its
     * worker either died mid-job or shut down without replying. The
     * AgentsView surfaces a "Rescue" button on rows with this flag.
     * Only typed per-mode dispatches qualify; rescue / setup / ping
     * dispatches are excluded.
     */
    "needsRescue": boolean;

    /** Creates a new DispatchDTO instance. */
    constructor($$source: Partial<DispatchDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("issueKey" in $$source)) {
            this["issueKey"] = "";
        }
        if (!("targetAgent" in $$source)) {
            this["targetAgent"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("payload" in $$source)) {
            this["payload"] = "";
        }
        if (!("createdBy" in $$source)) {
            this["createdBy"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("needsRescue" in $$source)) {
            this["needsRescue"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DispatchDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): DispatchDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DispatchDTO($$parsedSource as Partial<DispatchDTO>);
    }
}

/**
 * QuestionDTO is one open BACI-53 ask_user_question row — included
 * inside an AgentCard so the desktop and web bundle render the
 * "user input needed" badge and modal in one round trip.
 * 
 * We don't ship the full QuestionPayload over the AgentCard payload —
 * the UI fetches it via /agents/questions/{id} only when the user
 * opens the modal. The bare ID + asked-at + a count of pending
 * questions is what the badge needs.
 */
export class QuestionDTO {
    "id": number;
    "issueKey"?: string;
    "header": string;
    "askedAt": time$0.Time;

    /** Creates a new QuestionDTO instance. */
    constructor($$source: Partial<QuestionDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("header" in $$source)) {
            this["header"] = "";
        }
        if (!("askedAt" in $$source)) {
            this["askedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuestionDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): QuestionDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QuestionDTO($$parsedSource as Partial<QuestionDTO>);
    }
}

/**
 * SessionTodoDTO is one row of the agent's mirrored TodoWrite list,
 * shaped for the Agents screen. Status is one of
 * pending|in_progress|completed, surfaced verbatim so the frontend can
 * pick its glyph. IssueKey carries the BACI-62 per-job scope so a
 * future "history" pane can group prior-job todos without a second
 * fetch; omitted in JSON when empty so the on-wire shape stays
 * back-compatible for callers that don't care. DispatchID (BACI-132)
 * carries the per-dispatch scope so the UI could one day group two
 * dispatches on the same (session, issue) as separate task lists;
 * omitted on pre-BACI-132 rows and orphan rows so the on-wire shape
 * stays back-compatible.
 */
export class SessionTodoDTO {
    "content": string;
    "status": string;
    "issueKey"?: string;
    "dispatch_id"?: number | null;

    /** Creates a new SessionTodoDTO instance. */
    constructor($$source: Partial<SessionTodoDTO> = {}) {
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionTodoDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionTodoDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionTodoDTO($$parsedSource as Partial<SessionTodoDTO>);
    }
}

// Private type creation functions
const $$createType0 = ClaimDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = DispatchDTO.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = SessionTodoDTO.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = QuestionDTO.createFrom;
const $$createType7 = $Create.Array($$createType6);
