package sync

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
)

// IndexFilename is the table-of-contents file at the root of a sync
// repo. Regenerated by every export pass; lists every project repo
// whose data lives under repos/<PREFIX>/. The authoritative data
// stays in the per-repo repo.yaml files — index.yaml is a
// machine-readable convenience for "what's in this sync repo?".
const IndexFilename = "index.yaml"

// IndexSchemaVersion tracks the on-disk schema of index.yaml so we
// can evolve the layout without breaking older readers. Bump when a
// field rename or shape change lands.
const IndexSchemaVersion = 1

// RepoIndexEntry is one row in index.yaml — the per-repo summary the
// export pass accumulates as it walks each repo. Counts are populated
// from in-memory data the export already loaded; we don't re-scan
// the filesystem to derive them.
type RepoIndexEntry struct {
	Prefix    string `yaml:"prefix"`
	UUID      string `yaml:"uuid"`
	Name      string `yaml:"name"`
	Remote    string `yaml:"remote"`
	Issues    int    `yaml:"issues"`
	Features  int    `yaml:"features"`
	Documents int    `yaml:"documents"`
	Comments  int    `yaml:"comments"`
}

// Index is the parsed shape of index.yaml. Used by the sync-repo
// aware CLI commands (repo list, issue list, doc list) to discover
// which prefixes are present without scanning the directory tree.
type Index struct {
	SchemaVersion int              `yaml:"schema_version"`
	Repos         []RepoIndexEntry `yaml:"repos"`
}

// BuildIndex constructs the canonical YAML node tree for index.yaml.
// Entries are sorted by prefix so re-running the export against an
// unchanged DB produces byte-identical output.
func BuildIndex(entries []RepoIndexEntry) Node {
	sorted := make([]RepoIndexEntry, len(entries))
	copy(sorted, entries)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Prefix < sorted[j].Prefix })

	items := make([]Node, len(sorted))
	for i, e := range sorted {
		items[i] = Map(
			Pair{"comments", Int(int64(e.Comments))},
			Pair{"documents", Int(int64(e.Documents))},
			Pair{"features", Int(int64(e.Features))},
			Pair{"issues", Int(int64(e.Issues))},
			Pair{"name", Str(e.Name)},
			Pair{"prefix", Str(e.Prefix)},
			Pair{"remote", Str(e.Remote)},
			Pair{"uuid", Str(e.UUID)},
		)
	}
	return Map(
		Pair{"repos", Seq(items...)},
		Pair{"schema_version", Int(int64(IndexSchemaVersion))},
	)
}

// WriteIndex emits index.yaml at root. Idempotent: re-running with
// the same entries produces byte-identical output, so the next git
// add picks up no change when the export is a no-op.
func WriteIndex(root string, entries []RepoIndexEntry) error {
	bytes, err := Emit(BuildIndex(entries))
	if err != nil {
		return fmt.Errorf("emit index: %w", err)
	}
	abs := filepath.Join(root, IndexFilename)
	if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
		return fmt.Errorf("mkdir index parent: %w", err)
	}
	if err := os.WriteFile(abs, bytes, 0o644); err != nil {
		return fmt.Errorf("write index: %w", err)
	}
	return nil
}

// ReadIndex parses index.yaml at root. Returns ErrNoIndex when the
// file is missing so callers can fall back to scanning repos/ on
// older sync repos that pre-date the index file.
func ReadIndex(root string) (*Index, error) {
	abs := filepath.Join(root, IndexFilename)
	b, err := os.ReadFile(abs)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, ErrNoIndex
		}
		return nil, fmt.Errorf("read index: %w", err)
	}
	var idx Index
	if err := strictDecode(b, &idx); err != nil {
		return nil, fmt.Errorf("parse index: %w", err)
	}
	if idx.SchemaVersion == 0 {
		return nil, errors.New("index: missing or zero schema_version")
	}
	return &idx, nil
}

// ErrNoIndex signals a sync repo that doesn't carry an index.yaml
// yet — older sync repos created before this file existed. CLI
// callers fall back to scanning repos/ in that case.
var ErrNoIndex = errors.New("no index.yaml at sync repo root")
